In [34]:
import pandas as pd
import pickle

with open('Data_human_first_dists_V2.pkl', 'rb') as file:
    data = pickle.load(file)


df = pd.DataFrame(data)

C:\Users\Akrami_Lab5\AppData\Local\Temp\ipykernel_16464\3966253707.py:5: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  data = pickle.load(file)

In [35]:
df

,Local Timestamp,Participant_Private_ID,Participant_ID,Distribution,Trial,Screen Number,Zone Type,Reaction Time,Response,correct,...,previous2,pre_correct,next,next_correct,previous_choice,diff,diff_bin,Previous_dist,performance,No_response
0,1.649458e+12,6266630.0,Human_1,Uniform,1,2.0,response_keyboard,1069.9,A,1.0,...,0.848487,1.0,-0.079873,1.0,1.0,-0.334535,4,NaN,0.792988,False
1,1.649458e+12,6266630.0,Human_1,Uniform,2,2.0,response_keyboard,705.7,A,1.0,...,0.091131,1.0,0.740808,1.0,0.0,0.163531,5,NaN,0.792988,False
2,1.649458e+12,6266630.0,Human_1,Uniform,3,2.0,response_keyboard,758.9,B,1.0,...,-0.243404,1.0,0.646683,1.0,0.0,0.820681,7,NaN,0.792988,False
3,1.649458e+12,6266630.0,Human_1,Uniform,4,2.0,response_keyboard,1233.6,B,1.0,...,-0.079873,1.0,0.860149,1.0,1.0,-0.094125,4,NaN,0.792988,False
4,1.649458e+12,6266630.0,Human_1,Uniform,5,2.0,response_keyboard,1000.9,B,1.0,...,0.740808,1.0,0.310946,0.0,1.0,0.213466,5,NaN,0.792988,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26715,1.649448e+12,6265988.0,Human_30,Uniform,46,2.0,response_keyboard,766.3,B,1.0,...,-0.416997,1.0,-0.106539,1.0,0.0,1.385402,8,Uniform,0.842369,False
26716,1.649448e+12,6265988.0,Human_30,Uniform,47,2.0,response_keyboard,941.1,A,1.0,...,-0.974965,1.0,-0.372719,0.0,1.0,-0.516977,3,Uniform,0.842369,False
26717,1.649448e+12,6265988.0,Human_30,Uniform,48,2.0,response_keyboard,954.9,B,0.0,...,0.410437,1.0,0.311417,0.0,0.0,-0.266179,4,Uniform,0.842369,False
26718,1.649448e+12,6265988.0,Human_30,Uniform,49,2.0,response_keyboard,730.1,A,0.0,...,-0.106539,0.0,-0.353178,1.0,1.0,0.684135,6,Uniform,0.842369,False
26719,1.649448e+12,6265988.0,Human_30,Uniform,50,2.0,response_keyboard,729.0,A,1.0,...,-0.372719,0.0,NaN,NaN,0.0,-0.664594,3,Uniform,0.842369,False

In [36]:
df['Participant_Private_ID'].unique()

array([6266630., 6266742., 6268033., 6268045., 6268034., 6268700.,
       6268705., 6268726., 6268866., 6268864., 6268890., 6268892.,
       6268904., 6268920., 6843859., 6843885., 6843891., 6844091.,
       6846513., 6846501., 6846527., 6846555., 6846644., 6846657.,
       6265060., 6265558., 6265628., 6265983., 6265988.])

In [43]:
import pandas as pd
import pickle

with open('Data_rat_first_dists_V2.pkl', 'rb') as file:
    data = pickle.load(file)


df = pd.DataFrame(data)

C:\Users\Akrami_Lab5\AppData\Local\Temp\ipykernel_16464\3481035726.py:5: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  data = pickle.load(file)

In [44]:
df

,Participant_ID,savetime,stimulus,correct,Answer,Distribution,stim_dur,prestim_time,time_a1_go_cue,go_cue_dur,...,next_bin,previous2,pre_correct,next,next_correct,previous_choice,diff,diff_bin,Previous_dist,No_response
0,EM31,2022-05-06 13:58:01,0.018388,1.0,0,Asym_right,0.4,0.3,0.3,0.2,...,7.0,-0.9868,1.0,0.9532,1.0,0.0,0.5623,6,Asym_right,False
1,EM31,2022-05-06 13:58:01,0.047754,1.0,1,Asym_right,0.4,0.3,0.3,0.2,...,1.0,-0.5798,1.0,-0.6615,1.0,0.0,0.9707,7,Asym_right,False
2,EM31,2022-05-06 13:58:01,0.009764,1.0,0,Asym_right,0.4,0.3,0.3,0.2,...,1.0,-0.0175,1.0,-0.6859,1.0,1.0,-1.6147,0,Asym_right,False
3,EM31,2022-05-06 13:58:01,0.009533,1.0,0,Asym_right,0.4,0.3,0.3,0.2,...,1.0,0.9532,1.0,-0.5739,1.0,0.0,-0.0244,4,Asym_right,False
4,EM31,2022-05-06 13:58:01,0.010642,1.0,0,Asym_right,0.4,0.3,0.3,0.2,...,4.0,-0.6615,1.0,0.0043,0.0,0.0,0.1120,5,Asym_right,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306094,EM73,2023-11-14 11:57:04,0.036529,1.0,1,Asym_left,0.4,0.3,0.2,0.1,...,5.0,-0.7139,1.0,0.4437,1.0,0.0,1.1922,7,Asym_left,False
306095,EM73,2023-11-14 11:57:04,0.028937,1.0,1,Asym_left,0.4,0.3,0.2,0.1,...,5.0,-0.5115,1.0,0.3064,1.0,1.0,-0.2370,4,Asym_left,False
306096,EM73,2023-11-14 11:57:04,0.025284,1.0,1,Asym_left,0.4,0.3,0.2,0.1,...,1.0,0.6807,1.0,-0.6116,1.0,1.0,-0.1373,4,Asym_left,False
306097,EM73,2023-11-14 11:57:04,0.010255,1.0,0,Asym_left,0.4,0.3,0.2,0.1,...,4.0,0.4437,1.0,0.2149,1.0,1.0,-0.9180,2,Asym_left,False
306098,EM73,2023-11-14 11:57:04,0.023109,1.0,1,Asym_left,0.4,0.3,0.2,0.1,...,4.0,0.3064,1.0,0.0483,0.0,0.0,0.8265,7,Asym_left,False

In [46]:
df['Participant_ID'].unique()

array(['EM31', 'EM32', 'EM33', 'EM34', 'EM35', 'EM40', 'EM41', 'EM50',
       'EM51', 'EM54', 'EM55', 'EM56', 'EM57', 'EM58', 'EM59', 'EM60',
       'EM61', 'EM62', 'EM66', 'EM67', 'EM68', 'EM69', 'EM71', 'EM72',
       'EM73'], dtype=object)

In [37]:
import pandas as pd
import pickle

with open('SC_Data_Cleaned.pkl', 'rb') as file:
    data = pickle.load(file)


df = pd.DataFrame(data)

C:\Users\Akrami_Lab5\AppData\Local\Temp\ipykernel_16464\3246374612.py:5: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  data = pickle.load(file)

In [38]:
df

,Participant_ID,Trial,choice,correct,No_response,Response_Latency,Distribution,stim_relative,Sound_Contingency,block
0,QP0100,1,1,1.0,False,49.0,Uniform,0.401625,Low_Left_High_Right,0
1,QP0100,2,1,1.0,False,0.0,Uniform,0.055071,Low_Left_High_Right,0
2,QP0100,3,1,0.0,False,966.0,Uniform,-0.449892,Low_Left_High_Right,0
3,QP0100,4,1,0.0,False,0.0,Uniform,-0.238581,Low_Left_High_Right,0
4,QP0100,5,1,1.0,False,16.0,Uniform,0.074804,Low_Left_High_Right,0
...,...,...,...,...,...,...,...,...,...,...
788674,QP099,629,0,1.0,False,0.0,Asym_left,-0.713513,Low_Left_High_Right,24
788675,QP099,630,0,1.0,False,2133.0,Asym_left,-0.697220,Low_Left_High_Right,24
788676,QP099,631,0,1.0,False,0.0,Asym_left,-0.919791,Low_Left_High_Right,24
788677,QP099,632,0,0.0,False,0.0,Asym_left,0.226604,Low_Left_High_Right,24
788678,QP099,633,0,1.0,False,0.0,Asym_left,-0.066413,Low_Left_High_Right,24

In [41]:
df['Participant_ID'].unique()

array(['QP0100', 'QP0101', 'QP0103', 'QP0120', 'QP0121', 'QP0122',
       'QP0134', 'QP0138', 'QP0140', 'QP0141', 'QP0142', 'QP0151',
       'QP0152', 'QP0153', 'QP0154', 'QP0155', 'QP0156', 'QP0157',
       'QP0161', 'QP0162', 'QP049', 'QP050', 'QP062', 'QP063', 'QP070',
       'QP071', 'QP079', 'QP081', 'QP082', 'QP093', 'QP094', 'QP097',
       'QP098', 'QP099'], dtype=object)

In [47]:
import time

import binned_Hybrid_hpc_utils as hpc

start = time.time()

save_path = r"D:\sc_modelling-amir-2025\Final-Hybrid - Copy\human_test.pkl"

hpc.run_pid_repeated_cv(
    species="human",
    p_id=6266630.0,
    save_path=save_path,
    model_mode="all",
    repetition_seeds=[1],      # only one repetition
    cv_folds=2,
    optuna_trials=200,          # increase later
    sampler_type="TPE",
    model_seed_count=5,
    fit_with="conditional",
)

elapsed = time.time() - start

print(f"\nFinished in {elapsed/60:.2f} minutes")

[I 2026-07-01 13:03:04,760] A new study created in memory with name: no-name-ab093a8e-7b33-4b4c-af6e-53c762b1bfec

  ✱ Running repeated CV
  ✱ Species: human
  ✱ Subject: 6266630.0
  ✱ ID column: Participant_Private_ID
  ✱ Data path: D:\sc_modelling-amir-2025\Final-Hybrid - Copy\Data_human_first_dists_V2.pkl
  ✱ Model mode: all
  ✱ Custom alpha: None
  ✱ Repetitions: 1
  ✱ Folds: 2
  ✱ Model seeds per objective: 5
  ✱ Sampler: TPE

==============================
Running variant: Hybrid
==============================

--- Repetition 1/1, Fold 1/2 ---

[I 2026-07-01 13:03:10,468] Trial 0 finished with value: 0.06837284641213423 and parameters: {'sigma_noise': 0.08159018215585934, 'A_repulsion': 0.37739043882567497, 'gamma': 0.5677678301612995, 'sigma_update': 0.1654324459144433, 'eta_learning': 0.3478491667769279, 'sigma_boundary': 1.5333873569415812, 'alpha': 0.345191215678889}. Best is trial 0 with value: 0.06837284641213423.
[I 2026-07-01 13:03:14,750] Trial 1 finished with value: 0.10770311554283465 and parameters: {'sigma_noise': 0.028336949347424388, 'A_repulsion': 0.12397018705459617, 'gamma': 0.6037750794814256, 'sigma_update': 0.6799702871422885, 'eta_learning': 0.7050432940906743, 'sigma_boundary': 7.202289814735496, 'alpha': 0.19761819488501076}. Best is trial 0 with value: 0.06837284641213423.
[I 2026-07-01 13:03:20,354] Trial 2 finished with value: 0.11847761422122466 and parameters: {'sigma_noise': 0.22815268076549577, 'A_repulsion': 0.1046962058534483, 'gamma': 0.7917811153454742, 'sigma_update': 0.5746881351261827, 'eta_learning': 0.1411806041584652, 'sigma_boundary': 9.26022671518514, 'alpha': 0.08947189610755679}. Best is trial 0 with value: 0.06837284641213423.
[I 2026-07-01 13:03:25,835] Trial 3 finished with value: 0.1592007547385153 and parameters: {'sigma_noise': 0.2516999224057834, 'A_repulsion': 0.04084198586307114, 'gamma': 0.4658883805769573, 'sigma_update': 0.2756597839299866, 'eta_learning': 0.49378053512424686, 'sigma_boundary': 4.744469558215844, 'alpha': 0.257971795822834}. Best is trial 0 with value: 0.06837284641213423.
[I 2026-07-01 13:03:33,710] Trial 4 finished with value: 0.24203835041322472 and parameters: {'sigma_noise': 0.4481755238991748, 'A_repulsion': 0.19224766240446378, 'gamma': 0.43624790131316343, 'sigma_update': 0.6423761148454564, 'eta_learning': 0.9338473375652437, 'sigma_boundary': 9.653829981404058, 'alpha': 0.525249444507877}. Best is trial 0 with value: 0.06837284641213423.
[I 2026-07-01 13:03:41,790] Trial 5 finished with value: 0.14038204108305563 and parameters: {'sigma_noise': 0.4050965726517538, 'A_repulsion': 0.26532002031065316, 'gamma': 0.6065164114808138, 'sigma_update': 0.500551795517497, 'eta_learning': 0.987103256649888, 'sigma_boundary': 3.2799866449045885, 'alpha': 0.687529946679019}. Best is trial 0 with value: 0.06837284641213423.
[I 2026-07-01 13:03:48,114] Trial 6 finished with value: 0.1893690271213312 and parameters: {'sigma_noise': 0.42173929991324877, 'A_repulsion': 0.023514835890982133, 'gamma': 0.5494841403141102, 'sigma_update': 0.4917535135354017, 'eta_learning': 0.27920015081441985, 'sigma_boundary': 9.003956920436321, 'alpha': 0.36037129049980776}. Best is trial 0 with value: 0.06837284641213423.
[I 2026-07-01 13:03:58,149] Trial 7 finished with value: 0.5854502580152474 and parameters: {'sigma_noise': 0.42376319489670955, 'A_repulsion': 0.3092428567289799, 'gamma': 0.6778687560321413, 'sigma_update': 0.07130466643065073, 'eta_learning': 0.7209749537503536, 'sigma_boundary': 3.578790752804061, 'alpha': 0.11191690083480477}. Best is trial 0 with value: 0.06837284641213423.
[I 2026-07-01 13:04:04,856] Trial 8 finished with value: 0.33512863071412813 and parameters: {'sigma_noise': 0.20186791869273799, 'A_repulsion': 0.39794259559465356, 'gamma': 0.5406199369766412, 'sigma_update': 0.17976240876083485, 'eta_learning': 0.37051916155011705, 'sigma_boundary': 3.866546295171387, 'alpha': 0.16032124420670557}. Best is trial 0 with value: 0.06837284641213423.
[I 2026-07-01 13:04:09,692] Trial 9 finished with value: 0.10783091795691914 and parameters: {'sigma_noise': 0.16703620082455636, 'A_repulsion': 0.02931866830892288, 'gamma': 0.47560716888588833, 'sigma_update': 0.43722608827933773, 'eta_learning': 0.18190352970063134, 'sigma_boundary': 3.7508561719845708, 'alpha': 0.06605731391294933}. Best is trial 0 with value: 0.06837284641213423.
[I 2026-07-01 13:04:15,610] Trial 10 finished with value: 0.26780137523162406 and parameters: {'sigma_noise': 0.03223326075523472, 'A_repulsion': 0.49038804501782346, 'gamma': 0.09718053935174914, 'sigma_update': 0.01241565455974733, 'eta_learning': 0.01549888678143968, 'sigma_boundary': 0.4347391136355234, 'alpha': 0.9402551641653798}. Best is trial 0 with value: 0.06837284641213423.
[I 2026-07-01 13:04:19,985] Trial 11 finished with value: 0.062291780255513816 and parameters: {'sigma_noise': 0.021993913887750797, 'A_repulsion': 0.17709871922535994, 'gamma': 0.9746554968774851, 'sigma_update': 0.34127193334667316, 'eta_learning': 0.6822203931254832, 'sigma_boundary': 6.6298682570762, 'alpha': 0.4146918466537833}. Best is trial 11 with value: 0.062291780255513816.
[I 2026-07-01 13:04:25,570] Trial 12 finished with value: 0.06109945316220963 and parameters: {'sigma_noise': 0.11201849213868986, 'A_repulsion': 0.3531635505062218, 'gamma': 0.9924119783732677, 'sigma_update': 0.3005253541537845, 'eta_learning': 0.6562189159774447, 'sigma_boundary': 0.8157674866442273, 'alpha': 0.4826594094809439}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:04:30,687] Trial 13 finished with value: 0.06612552460516921 and parameters: {'sigma_noise': 0.11421200713642483, 'A_repulsion': 0.20904903933894045, 'gamma': 0.9997474960444206, 'sigma_update': 0.3344402053061202, 'eta_learning': 0.6920474401610504, 'sigma_boundary': 6.99748532274522, 'alpha': 0.5850123380777705}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:04:36,370] Trial 14 finished with value: 0.07498635962726333 and parameters: {'sigma_noise': 0.11431544797590673, 'A_repulsion': 0.34898377707082573, 'gamma': 0.9668162530923781, 'sigma_update': 0.2717702597861939, 'eta_learning': 0.5946069772326565, 'sigma_boundary': 6.536402750185382, 'alpha': 0.7623879934990931}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:04:44,873] Trial 15 finished with value: 0.14304962485854855 and parameters: {'sigma_noise': 0.3070288201448284, 'A_repulsion': 0.47347303379807415, 'gamma': 0.8347941116914006, 'sigma_update': 0.39156195578306763, 'eta_learning': 0.8240988331539819, 'sigma_boundary': 2.025390231214584, 'alpha': 0.4507857085526148}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:04:49,462] Trial 16 finished with value: 0.06584918928335871 and parameters: {'sigma_noise': 0.07347183435467511, 'A_repulsion': 0.15312377374018127, 'gamma': 0.8588628957569072, 'sigma_update': 0.2055172342671949, 'eta_learning': 0.50339998187736, 'sigma_boundary': 6.114578082082733, 'alpha': 0.6373648883486248}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:04:53,708] Trial 17 finished with value: 0.08064155964174932 and parameters: {'sigma_noise': 0.012488015496612211, 'A_repulsion': 0.2555512010354033, 'gamma': 0.2843800706575601, 'sigma_update': 0.32409423450358843, 'eta_learning': 0.8365227986508992, 'sigma_boundary': 7.83436943801788, 'alpha': 0.43863535371813517}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:04:59,387] Trial 18 finished with value: 0.0629789340226596 and parameters: {'sigma_noise': 0.14745376470677132, 'A_repulsion': 0.3099235910957444, 'gamma': 0.7432349858390176, 'sigma_update': 0.25563300638455516, 'eta_learning': 0.5945285273910075, 'sigma_boundary': 5.359141537100852, 'alpha': 0.8080881135051008}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:05:07,523] Trial 19 finished with value: 0.10572131550998934 and parameters: {'sigma_noise': 0.3127241363111497, 'A_repulsion': 0.43504738650090946, 'gamma': 0.9514823407063199, 'sigma_update': 0.40810743731389404, 'eta_learning': 0.599253089971026, 'sigma_boundary': 0.20712319398620083, 'alpha': 0.3520152182237094}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:05:12,677] Trial 20 finished with value: 0.08469039726497776 and parameters: {'sigma_noise': 0.07226495153574586, 'A_repulsion': 0.3042804712008014, 'gamma': 0.3656556796926753, 'sigma_update': 0.10282824702870924, 'eta_learning': 0.7885838252518086, 'sigma_boundary': 2.1963579095067725, 'alpha': 0.5582414788606903}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:05:18,502] Trial 21 finished with value: 0.0620190553098846 and parameters: {'sigma_noise': 0.14776365557138132, 'A_repulsion': 0.33154794179078306, 'gamma': 0.7143030526072129, 'sigma_update': 0.25685439592646714, 'eta_learning': 0.5952498281055711, 'sigma_boundary': 4.963116173263714, 'alpha': 0.8130338722755791}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:05:24,169] Trial 22 finished with value: 0.06279408251430346 and parameters: {'sigma_noise': 0.16255842895092606, 'A_repulsion': 0.2102348581932787, 'gamma': 0.8917036513577843, 'sigma_update': 0.34516555865218174, 'eta_learning': 0.4613321579829628, 'sigma_boundary': 8.12499130479649, 'alpha': 0.9360940562581374}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:05:29,694] Trial 23 finished with value: 0.06744898927398721 and parameters: {'sigma_noise': 0.11363015343330408, 'A_repulsion': 0.36808727599415864, 'gamma': 0.7064424202628532, 'sigma_update': 0.22040841125841126, 'eta_learning': 0.6278314413079026, 'sigma_boundary': 5.597999952156876, 'alpha': 0.8256781327200644}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:05:34,745] Trial 24 finished with value: 0.061904508178192236 and parameters: {'sigma_noise': 0.050538117190545295, 'A_repulsion': 0.42122494383916254, 'gamma': 0.901475370400818, 'sigma_update': 0.4682129598474822, 'eta_learning': 0.41924800055287403, 'sigma_boundary': 4.556117615762205, 'alpha': 0.47469523017128756}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:05:39,979] Trial 25 finished with value: 0.06550654598758565 and parameters: {'sigma_noise': 0.062197779583218586, 'A_repulsion': 0.42642426211759965, 'gamma': 0.7826017097940404, 'sigma_update': 0.46445318260648516, 'eta_learning': 0.43782974146043496, 'sigma_boundary': 4.5760194174800635, 'alpha': 0.6917748243792068}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:05:46,776] Trial 26 finished with value: 0.21614122930588697 and parameters: {'sigma_noise': 0.19297944816949164, 'A_repulsion': 0.4200570730640104, 'gamma': 0.9247137315824131, 'sigma_update': 0.5388973686475105, 'eta_learning': 0.35427255190127477, 'sigma_boundary': 2.5890048892670556, 'alpha': 0.2646074074071044}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:05:52,396] Trial 27 finished with value: 0.07138636965132714 and parameters: {'sigma_noise': 0.1322811526200054, 'A_repulsion': 0.3376001377102506, 'gamma': 0.677698142264507, 'sigma_update': 0.13128492266161187, 'eta_learning': 0.5507850281205939, 'sigma_boundary': 1.0946478895542286, 'alpha': 0.5092126380098642}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:06:00,372] Trial 28 finished with value: 0.08080917690201923 and parameters: {'sigma_noise': 0.28332812579051764, 'A_repulsion': 0.4687532755840433, 'gamma': 0.8586286892220152, 'sigma_update': 0.3957281353388774, 'eta_learning': 0.2640766240308391, 'sigma_boundary': 4.477563416827341, 'alpha': 0.6092744098579989}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:06:06,302] Trial 29 finished with value: 0.07272948716683647 and parameters: {'sigma_noise': 0.09401059139454913, 'A_repulsion': 0.38460809369283905, 'gamma': 0.7927117229992858, 'sigma_update': 0.5544564193433498, 'eta_learning': 0.41266405258920186, 'sigma_boundary': 1.183569300727624, 'alpha': 0.8789609031545911}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:06:11,249] Trial 30 finished with value: 0.11756964924665601 and parameters: {'sigma_noise': 0.0550227049524896, 'A_repulsion': 0.29036243640972004, 'gamma': 0.8880768864427057, 'sigma_update': 0.30814025413079715, 'eta_learning': 0.2713167806856961, 'sigma_boundary': 2.8532253260152514, 'alpha': 0.008376288859138992}. Best is trial 12 with value: 0.06109945316220963.
[I 2026-07-01 13:06:16,829] Trial 31 finished with value: 0.05871324002587292 and parameters: {'sigma_noise': 0.08950522638389602, 'A_repulsion': 0.34727563581292265, 'gamma': 0.9910489263831374, 'sigma_update': 0.2418327451823001, 'eta_learning': 0.659966523990043, 'sigma_boundary': 6.002624901564652, 'alpha': 0.4346125532408251}. Best is trial 31 with value: 0.05871324002587292.
[I 2026-07-01 13:06:22,361] Trial 32 finished with value: 0.11419970428227305 and parameters: {'sigma_noise': 0.0888159994604094, 'A_repulsion': 0.3400840555863253, 'gamma': 0.9256927968751538, 'sigma_update': 0.25196299776687514, 'eta_learning': 0.7486809101439984, 'sigma_boundary': 5.952186216138751, 'alpha': 0.29373367533552974}. Best is trial 31 with value: 0.05871324002587292.
[I 2026-07-01 13:06:29,010] Trial 33 finished with value: 0.08963682007903383 and parameters: {'sigma_noise': 0.1881878159123366, 'A_repulsion': 0.39931391738090183, 'gamma': 0.8056595523375435, 'sigma_update': 0.15959068146473082, 'eta_learning': 0.6566969033769365, 'sigma_boundary': 8.000923630366264, 'alpha': 0.47762936289490426}. Best is trial 31 with value: 0.05871324002587292.
[I 2026-07-01 13:06:34,049] Trial 34 finished with value: 0.06330404010628876 and parameters: {'sigma_noise': 0.04761403508187914, 'A_repulsion': 0.3659811223473811, 'gamma': 0.9886553570383516, 'sigma_update': 0.22010342797542293, 'eta_learning': 0.5411133242841557, 'sigma_boundary': 5.1648312571516195, 'alpha': 0.3753268476744196}. Best is trial 31 with value: 0.05871324002587292.
[I 2026-07-01 13:06:40,396] Trial 35 finished with value: 0.06537354146345639 and parameters: {'sigma_noise': 0.13304659324364687, 'A_repulsion': 0.4531674376389545, 'gamma': 0.6082294504579514, 'sigma_update': 0.29231924850458735, 'eta_learning': 0.5374953315620665, 'sigma_boundary': 4.090739280387656, 'alpha': 0.6673017892638025}. Best is trial 31 with value: 0.05871324002587292.
[I 2026-07-01 13:06:47,213] Trial 36 finished with value: 0.07955401983649618 and parameters: {'sigma_noise': 0.22305958470606788, 'A_repulsion': 0.3312352401292489, 'gamma': 0.7441162847698443, 'sigma_update': 0.3669242450843232, 'eta_learning': 0.8652106632395162, 'sigma_boundary': 3.057735116614958, 'alpha': 0.5448976622907266}. Best is trial 31 with value: 0.05871324002587292.
[I 2026-07-01 13:06:51,821] Trial 37 finished with value: 0.07498662653215094 and parameters: {'sigma_noise': 0.04617924704072771, 'A_repulsion': 0.2419972887600303, 'gamma': 0.9219832670975948, 'sigma_update': 0.436056678842371, 'eta_learning': 0.7589273315769862, 'sigma_boundary': 7.555410021784644, 'alpha': 0.7258721923150595}. Best is trial 31 with value: 0.05871324002587292.
[I 2026-07-01 13:06:56,377] Trial 38 finished with value: 0.13388723448342646 and parameters: {'sigma_noise': 0.09830377487252734, 'A_repulsion': 0.09616910280741067, 'gamma': 0.8408189224760384, 'sigma_update': 0.6279808310427799, 'eta_learning': 0.9245502567686613, 'sigma_boundary': 5.826941334970883, 'alpha': 0.3042917985476175}. Best is trial 31 with value: 0.05871324002587292.
[I 2026-07-01 13:07:02,196] Trial 39 finished with value: 0.12904341215452253 and parameters: {'sigma_noise': 0.16562472240698672, 'A_repulsion': 0.2792010176301055, 'gamma': 0.6315381946467492, 'sigma_update': 0.49502108155856045, 'eta_learning': 0.47507914816751895, 'sigma_boundary': 4.33527819733371, 'alpha': 0.38518486311046246}. Best is trial 31 with value: 0.05871324002587292.
[I 2026-07-01 13:07:08,180] Trial 40 finished with value: 0.20471101420710575 and parameters: {'sigma_noise': 0.13977273351144542, 'A_repulsion': 0.40658481143899666, 'gamma': 0.8994767691849899, 'sigma_update': 0.179112195790258, 'eta_learning': 0.393522723995594, 'sigma_boundary': 8.801884748839214, 'alpha': 0.20868006057303912}. Best is trial 31 with value: 0.05871324002587292.
[I 2026-07-01 13:07:12,738] Trial 41 finished with value: 0.07620707448459649 and parameters: {'sigma_noise': 0.010337172621904922, 'A_repulsion': 0.16625275438659717, 'gamma': 0.9883021057460193, 'sigma_update': 0.3003832762921367, 'eta_learning': 0.6769129055399975, 'sigma_boundary': 6.620642849513343, 'alpha': 0.41836968977505434}. Best is trial 31 with value: 0.05871324002587292.
[I 2026-07-01 13:07:18,255] Trial 42 finished with value: 0.057422750774456424 and parameters: {'sigma_noise': 0.08001642646602836, 'A_repulsion': 0.36595930636094864, 'gamma': 0.9442245714347853, 'sigma_update': 0.3475535683919918, 'eta_learning': 0.7098846944451114, 'sigma_boundary': 4.922601852421995, 'alpha': 0.4948522537370893}. Best is trial 42 with value: 0.057422750774456424.
[I 2026-07-01 13:07:23,620] Trial 43 finished with value: 0.05638269777157285 and parameters: {'sigma_noise': 0.0770030127109799, 'A_repulsion': 0.369947490216595, 'gamma': 0.9329076237779329, 'sigma_update': 0.3706861020670691, 'eta_learning': 0.7163825566795031, 'sigma_boundary': 4.7620216970614315, 'alpha': 0.5170677112167815}. Best is trial 43 with value: 0.05638269777157285.
[I 2026-07-01 13:07:28,362] Trial 44 finished with value: 0.06770783798709473 and parameters: {'sigma_noise': 0.03273957184932718, 'A_repulsion': 0.36950199523093186, 'gamma': 0.9369098210325589, 'sigma_update': 0.374699312598348, 'eta_learning': 0.7282088203909551, 'sigma_boundary': 3.447462750515098, 'alpha': 0.5174713041300791}. Best is trial 43 with value: 0.05638269777157285.
[I 2026-07-01 13:07:33,895] Trial 45 finished with value: 0.09898427106514834 and parameters: {'sigma_noise': 0.08628950054624146, 'A_repulsion': 0.3845936757345966, 'gamma': 0.20542654600196064, 'sigma_update': 0.44947994590707957, 'eta_learning': 0.7972962575431792, 'sigma_boundary': 4.952698619464519, 'alpha': 0.46876127179975463}. Best is trial 43 with value: 0.05638269777157285.
[I 2026-07-01 13:07:39,980] Trial 46 finished with value: 0.0608774398168407 and parameters: {'sigma_noise': 0.11418966035437113, 'A_repulsion': 0.44557489115814375, 'gamma': 0.9981102514779233, 'sigma_update': 0.42552381005649903, 'eta_learning': 0.6346044892946427, 'sigma_boundary': 6.193104717883731, 'alpha': 0.5751116049051118}. Best is trial 43 with value: 0.05638269777157285.
[I 2026-07-01 13:07:44,435] Trial 47 finished with value: 0.07385476101383037 and parameters: {'sigma_noise': 0.10868543142510018, 'A_repulsion': 0.0008071449105011286, 'gamma': 0.02160315513662614, 'sigma_update': 0.37350438262654956, 'eta_learning': 0.6397953552771886, 'sigma_boundary': 7.352697089847354, 'alpha': 0.5816032278343727}. Best is trial 43 with value: 0.05638269777157285.
[I 2026-07-01 13:07:50,291] Trial 48 finished with value: 0.06511198028106874 and parameters: {'sigma_noise': 0.1226798888068706, 'A_repulsion': 0.4412530028305057, 'gamma': 0.9646279697598202, 'sigma_update': 0.41319616944710813, 'eta_learning': 0.8825028786860369, 'sigma_boundary': 9.836541548484703, 'alpha': 0.6187813230495839}. Best is trial 43 with value: 0.05638269777157285.
[I 2026-07-01 13:07:56,009] Trial 49 finished with value: 0.0643039614913886 and parameters: {'sigma_noise': 0.07956580033304597, 'A_repulsion': 0.4837311229518419, 'gamma': 0.9961466842825832, 'sigma_update': 0.3266891938433975, 'eta_learning': 0.704311450041226, 'sigma_boundary': 6.312977065970506, 'alpha': 0.5447703191220715}. Best is trial 43 with value: 0.05638269777157285.
[I 2026-07-01 13:08:03,589] Trial 50 finished with value: 0.1682863979440957 and parameters: {'sigma_noise': 0.2613066572558243, 'A_repulsion': 0.460138922324045, 'gamma': 0.8591085337945599, 'sigma_update': 0.28721267775902365, 'eta_learning': 0.7645481905886873, 'sigma_boundary': 6.916127996665199, 'alpha': 0.40763792088908424}. Best is trial 43 with value: 0.05638269777157285.

--- Repetition 1/1, Fold 2/2 ---

[I 2026-07-01 13:22:07,939] Trial 0 finished with value: 0.06081333036134209 and parameters: {'sigma_noise': 0.23130453864636627, 'A_repulsion': 0.18301128532134425, 'gamma': 0.452841141347309, 'sigma_update': 0.25970184790431533, 'eta_learning': 0.6392867793009408, 'sigma_boundary': 5.401778771013789, 'alpha': 0.3486167982943438}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:22:12,108] Trial 1 finished with value: 0.14553790569317787 and parameters: {'sigma_noise': 0.017208828667492883, 'A_repulsion': 0.2707457972784512, 'gamma': 0.03587961860841644, 'sigma_update': 0.07793997913386755, 'eta_learning': 0.8483468574108974, 'sigma_boundary': 8.303441021774777, 'alpha': 0.8837563487755918}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:22:17,431] Trial 2 finished with value: 0.108276252080776 and parameters: {'sigma_noise': 0.26940948843115053, 'A_repulsion': 0.015399236752296985, 'gamma': 0.5950977163681339, 'sigma_update': 0.1358747586738585, 'eta_learning': 0.6310765168478065, 'sigma_boundary': 1.9789875957328684, 'alpha': 0.2576627621396542}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:22:25,750] Trial 3 finished with value: 0.1333179298297155 and parameters: {'sigma_noise': 0.44216332964682853, 'A_repulsion': 0.19876785919484746, 'gamma': 0.5496606567532344, 'sigma_update': 0.11209988747342718, 'eta_learning': 0.6660281605276116, 'sigma_boundary': 9.469043245402597, 'alpha': 0.6087678738096705}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:22:32,631] Trial 4 finished with value: 0.502703990427547 and parameters: {'sigma_noise': 0.4113685825474536, 'A_repulsion': 0.026287693760968123, 'gamma': 0.9423902250678173, 'sigma_update': 0.07200514621890475, 'eta_learning': 0.8927644828019287, 'sigma_boundary': 7.801905612035644, 'alpha': 0.265395331341275}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:22:38,420] Trial 5 finished with value: 0.06435659844147074 and parameters: {'sigma_noise': 0.16223811750247244, 'A_repulsion': 0.23904398873571586, 'gamma': 0.1896154616659259, 'sigma_update': 0.06833875913914035, 'eta_learning': 0.5965238587565677, 'sigma_boundary': 7.9000484349431535, 'alpha': 0.3249140746842085}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:22:43,676] Trial 6 finished with value: 0.10667595582837969 and parameters: {'sigma_noise': 0.2856376173228588, 'A_repulsion': 0.005124619365729943, 'gamma': 0.8263659342490774, 'sigma_update': 0.5059137610156367, 'eta_learning': 0.186235886327391, 'sigma_boundary': 5.268062090462645, 'alpha': 0.9590535762624828}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:22:50,668] Trial 7 finished with value: 0.18437110924898112 and parameters: {'sigma_noise': 0.13791631535468357, 'A_repulsion': 0.4597502378098518, 'gamma': 0.30695984904051493, 'sigma_update': 0.030936483705504315, 'eta_learning': 0.4128121235401722, 'sigma_boundary': 5.445400302506103, 'alpha': 0.8202384808476303}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:22:55,905] Trial 8 finished with value: 0.0713564555904651 and parameters: {'sigma_noise': 0.254513211956344, 'A_repulsion': 0.028885375339675223, 'gamma': 0.2660296925829004, 'sigma_update': 0.36664134287997496, 'eta_learning': 0.2979458415184891, 'sigma_boundary': 5.635151654744328, 'alpha': 0.5365402330536179}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:23:03,997] Trial 9 finished with value: 0.468762966841268 and parameters: {'sigma_noise': 0.42824183694393003, 'A_repulsion': 0.2541568971192354, 'gamma': 0.5167176213814652, 'sigma_update': 0.3375229907487427, 'eta_learning': 0.6644727315721212, 'sigma_boundary': 7.0399563075468645, 'alpha': 0.30676327687408156}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:23:11,843] Trial 10 finished with value: 0.13797921205888902 and parameters: {'sigma_noise': 0.3446002626281236, 'A_repulsion': 0.3624451678646117, 'gamma': 0.7254419772983464, 'sigma_update': 0.6893828277604787, 'eta_learning': 0.03489439212843576, 'sigma_boundary': 2.412420878685662, 'alpha': 0.009252752344869108}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:23:16,903] Trial 11 finished with value: 0.06716631171908881 and parameters: {'sigma_noise': 0.158155455191315, 'A_repulsion': 0.153751072891992, 'gamma': 0.28360053745011526, 'sigma_update': 0.25629994035296716, 'eta_learning': 0.5028064642749974, 'sigma_boundary': 3.8472327990395727, 'alpha': 0.3891014922006204}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:23:22,046] Trial 12 finished with value: 0.15441192505244086 and parameters: {'sigma_noise': 0.15728703819275736, 'A_repulsion': 0.13892370385379765, 'gamma': 0.07160865325845883, 'sigma_update': 0.2304982744298925, 'eta_learning': 0.7386714738557791, 'sigma_boundary': 0.4533098221620637, 'alpha': 0.081400120090249}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:23:26,984] Trial 13 finished with value: 0.11611808203953014 and parameters: {'sigma_noise': 0.0754979549191922, 'A_repulsion': 0.3366897968611488, 'gamma': 0.17506828881790412, 'sigma_update': 0.22009047760987735, 'eta_learning': 0.4900708549499041, 'sigma_boundary': 7.07645616360608, 'alpha': 0.6626769354482099}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:23:32,080] Trial 14 finished with value: 0.0622778522595534 and parameters: {'sigma_noise': 0.19095373412399413, 'A_repulsion': 0.10309484652006817, 'gamma': 0.37478594228500656, 'sigma_update': 0.43626784687186976, 'eta_learning': 0.7841420962642972, 'sigma_boundary': 9.101040281658197, 'alpha': 0.41577748167257195}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:23:37,387] Trial 15 finished with value: 0.08232685450245802 and parameters: {'sigma_noise': 0.2155453186460025, 'A_repulsion': 0.10433369195319235, 'gamma': 0.424901703341489, 'sigma_update': 0.4803207599622127, 'eta_learning': 0.9857719749473575, 'sigma_boundary': 9.861925382420356, 'alpha': 0.43134748466250017}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:23:43,517] Trial 16 finished with value: 0.49610339756483324 and parameters: {'sigma_noise': 0.3433332460232691, 'A_repulsion': 0.07674649073596847, 'gamma': 0.37471959657449544, 'sigma_update': 0.48062725773793635, 'eta_learning': 0.7769079516123001, 'sigma_boundary': 4.008277266349865, 'alpha': 0.15292424731809973}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:23:48,995] Trial 17 finished with value: 0.08478569168880355 and parameters: {'sigma_noise': 0.20788863073983666, 'A_repulsion': 0.1799491829803197, 'gamma': 0.7075522999266877, 'sigma_update': 0.37377800896134983, 'eta_learning': 0.9675109110337572, 'sigma_boundary': 6.458129665277335, 'alpha': 0.6874639157550558}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:23:53,273] Trial 18 finished with value: 0.0735844630872648 and parameters: {'sigma_noise': 0.09747046097034717, 'A_repulsion': 0.09420447077933364, 'gamma': 0.43839159166059427, 'sigma_update': 0.5853031478094547, 'eta_learning': 0.361663226400165, 'sigma_boundary': 3.8991421226310212, 'alpha': 0.49566862922168753}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:24:00,307] Trial 19 finished with value: 0.6612446887588439 and parameters: {'sigma_noise': 0.2997408504332941, 'A_repulsion': 0.3167318658128354, 'gamma': 0.6755352287587544, 'sigma_update': 0.41100373375339183, 'eta_learning': 0.79978910191903, 'sigma_boundary': 8.903707432103213, 'alpha': 0.16233077299156512}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:24:07,092] Trial 20 finished with value: 0.06982656414011446 and parameters: {'sigma_noise': 0.20008790942954, 'A_repulsion': 0.42047879404755395, 'gamma': 0.6223925768391769, 'sigma_update': 0.2949872347443362, 'eta_learning': 0.5501879291447063, 'sigma_boundary': 1.5542473072014351, 'alpha': 0.42636101104601276}. Best is trial 0 with value: 0.06081333036134209.
[I 2026-07-01 13:24:12,512] Trial 21 finished with value: 0.05466158865401532 and parameters: {'sigma_noise': 0.18070872111884648, 'A_repulsion': 0.22193503043307, 'gamma': 0.17352046158687978, 'sigma_update': 0.17180772310107453, 'eta_learning': 0.6269114378447384, 'sigma_boundary': 8.396918804899864, 'alpha': 0.36210852744714467}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:24:18,478] Trial 22 finished with value: 0.09898603943410647 and parameters: {'sigma_noise': 0.23639380530356446, 'A_repulsion': 0.20435697552895676, 'gamma': 0.13911969095001, 'sigma_update': 0.1518778980531632, 'eta_learning': 0.7269316395960553, 'sigma_boundary': 9.038548992783602, 'alpha': 0.5209025649007458}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:24:22,894] Trial 23 finished with value: 0.10503211197711801 and parameters: {'sigma_noise': 0.0863611949994077, 'A_repulsion': 0.12796947430899308, 'gamma': 0.3511622721494807, 'sigma_update': 0.16463582266307977, 'eta_learning': 0.4513271069299162, 'sigma_boundary': 6.478910791512031, 'alpha': 0.3778521870206551}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:24:27,668] Trial 24 finished with value: 0.13814290405885477 and parameters: {'sigma_noise': 0.18936697919289736, 'A_repulsion': 0.06165228445096593, 'gamma': 0.44790525838744005, 'sigma_update': 0.29520194913459075, 'eta_learning': 0.8852833664829811, 'sigma_boundary': 9.954540141699628, 'alpha': 0.20009952053687283}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:24:32,774] Trial 25 finished with value: 0.06754485247692046 and parameters: {'sigma_noise': 0.12057514470984684, 'A_repulsion': 0.288178197726614, 'gamma': 0.2384355611931788, 'sigma_update': 0.4171055209934591, 'eta_learning': 0.5648573536111469, 'sigma_boundary': 8.633218805243116, 'alpha': 0.46658723406318936}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:24:39,229] Trial 26 finished with value: 0.09638799965307793 and parameters: {'sigma_noise': 0.3051473562055649, 'A_repulsion': 0.22211383275214655, 'gamma': 0.10218219976271334, 'sigma_update': 0.19919726951204697, 'eta_learning': 0.6996961236593613, 'sigma_boundary': 7.335761848868539, 'alpha': 0.5666710475017238}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:24:45,233] Trial 27 finished with value: 0.07649387973978308 and parameters: {'sigma_noise': 0.2364098102905055, 'A_repulsion': 0.17154921975853243, 'gamma': 0.3897751477274111, 'sigma_update': 0.3063568907224852, 'eta_learning': 0.8453599803986768, 'sigma_boundary': 4.7971720523820185, 'alpha': 0.7178788358168458}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:24:49,351] Trial 28 finished with value: 0.07300670156531192 and parameters: {'sigma_noise': 0.04784974863064359, 'A_repulsion': 0.13436914716369278, 'gamma': 0.48313153033482453, 'sigma_update': 0.5690297162237645, 'eta_learning': 0.600358343834782, 'sigma_boundary': 6.2098756466589276, 'alpha': 0.3456353872881657}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:24:55,211] Trial 29 finished with value: 0.17455848079789252 and parameters: {'sigma_noise': 0.1698594762966236, 'A_repulsion': 0.28392750682969325, 'gamma': 0.01492911309699213, 'sigma_update': 0.2612691951367439, 'eta_learning': 0.8218243499412972, 'sigma_boundary': 8.289043055301818, 'alpha': 0.23691445758788193}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:25:02,978] Trial 30 finished with value: 0.07904328084605843 and parameters: {'sigma_noise': 0.33550094905064626, 'A_repulsion': 0.3783369033960602, 'gamma': 0.21157159029700928, 'sigma_update': 0.41404109192063154, 'eta_learning': 0.9295655035757702, 'sigma_boundary': 3.255972924957113, 'alpha': 0.6053606784838299}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:25:08,614] Trial 31 finished with value: 0.0826109380556265 and parameters: {'sigma_noise': 0.12083503699358336, 'A_repulsion': 0.250581688335238, 'gamma': 0.17131886760243964, 'sigma_update': 0.032604752236153944, 'eta_learning': 0.6052474733713988, 'sigma_boundary': 7.9501720993890626, 'alpha': 0.32810930818374306}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:25:14,365] Trial 32 finished with value: 0.09721734850897404 and parameters: {'sigma_noise': 0.1807492881562282, 'A_repulsion': 0.23426694140422433, 'gamma': 0.10257202724742437, 'sigma_update': 0.09179991787906837, 'eta_learning': 0.5545222774713362, 'sigma_boundary': 7.623594193042651, 'alpha': 0.2738682731112139}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:25:18,472] Trial 33 finished with value: 0.11526268637600216 and parameters: {'sigma_noise': 0.02298484510276544, 'A_repulsion': 0.2110099526438913, 'gamma': 0.3374874185493614, 'sigma_update': 0.12553980305695878, 'eta_learning': 0.6227173233047933, 'sigma_boundary': 9.30814173935567, 'alpha': 0.42029776287175313}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:25:24,493] Trial 34 finished with value: 0.06604333607914932 and parameters: {'sigma_noise': 0.25895961461566575, 'A_repulsion': 0.18337797239841194, 'gamma': 0.2343084494162196, 'sigma_update': 0.1691921953710463, 'eta_learning': 0.6880661331431244, 'sigma_boundary': 8.425459620562881, 'alpha': 0.3437960358225874}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:25:30,443] Trial 35 finished with value: 0.08098415513345343 and parameters: {'sigma_noise': 0.14078737219694226, 'A_repulsion': 0.30608402809464974, 'gamma': 0.5913579576477576, 'sigma_update': 0.06375378449180197, 'eta_learning': 0.766401669648078, 'sigma_boundary': 7.9830876351780535, 'alpha': 0.46850536143023164}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:25:35,704] Trial 36 finished with value: 0.10385760104387662 and parameters: {'sigma_noise': 0.2350079807422904, 'A_repulsion': 0.0463654023055399, 'gamma': 0.31497933093786756, 'sigma_update': 0.11054742788173894, 'eta_learning': 0.6479872167790596, 'sigma_boundary': 4.807290848146998, 'alpha': 0.25298585475045104}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:25:41,505] Trial 37 finished with value: 0.1525909431886872 and parameters: {'sigma_noise': 0.1816471829270999, 'A_repulsion': 0.2570077598392262, 'gamma': 0.5252682795050886, 'sigma_update': 0.19257740991979672, 'eta_learning': 0.38558598049577963, 'sigma_boundary': 5.934684473924328, 'alpha': 0.18946943603621003}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:25:47,687] Trial 38 finished with value: 0.3403856359836695 and parameters: {'sigma_noise': 0.21647299450623325, 'A_repulsion': 0.11097424876098101, 'gamma': 0.16579753041661222, 'sigma_update': 0.023191891214672175, 'eta_learning': 0.4543701653226527, 'sigma_boundary': 9.531447284551291, 'alpha': 0.09243817182581487}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:25:53,924] Trial 39 finished with value: 0.07958710047223566 and parameters: {'sigma_noise': 0.2772288650142058, 'A_repulsion': 0.15501773722601125, 'gamma': 0.8399945731971818, 'sigma_update': 0.33716133525218883, 'eta_learning': 0.3138386361761888, 'sigma_boundary': 6.848899250644778, 'alpha': 0.2965632885580113}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:26:04,601] Trial 40 finished with value: 0.2023752474852401 and parameters: {'sigma_noise': 0.37506585737003434, 'A_repulsion': 0.488689623774597, 'gamma': 0.28354511664054505, 'sigma_update': 0.06404194465224194, 'eta_learning': 0.889788326676598, 'sigma_boundary': 7.565537093896346, 'alpha': 0.9970837331364546}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:26:10,617] Trial 41 finished with value: 0.06612803122163405 and parameters: {'sigma_noise': 0.2603728316398123, 'A_repulsion': 0.18410931563551655, 'gamma': 0.21473078929584205, 'sigma_update': 0.14859556019528783, 'eta_learning': 0.6867596729443476, 'sigma_boundary': 8.518644038971038, 'alpha': 0.35063711600067277}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:26:17,044] Trial 42 finished with value: 0.06854612398002943 and parameters: {'sigma_noise': 0.26363992322847996, 'A_repulsion': 0.22557952640368, 'gamma': 0.23121966830658702, 'sigma_update': 0.1816235101884961, 'eta_learning': 0.7166567456845214, 'sigma_boundary': 8.284250850214821, 'alpha': 0.379680337479386}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:26:22,530] Trial 43 finished with value: 0.0560359104945282 and parameters: {'sigma_noise': 0.16015050942465875, 'A_repulsion': 0.19601694427772673, 'gamma': 0.05183252903825886, 'sigma_update': 0.24812275032249514, 'eta_learning': 0.6465479670942591, 'sigma_boundary': 9.285638015350278, 'alpha': 0.31216521301368627}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:26:27,886] Trial 44 finished with value: 0.05655116741462663 and parameters: {'sigma_noise': 0.14503434721293823, 'A_repulsion': 0.26986088279130666, 'gamma': 0.06331572096248954, 'sigma_update': 0.2510659124929293, 'eta_learning': 0.5818550887508329, 'sigma_boundary': 9.250128468551898, 'alpha': 0.29663058754717486}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:26:33,422] Trial 45 finished with value: 0.11949000592222495 and parameters: {'sigma_noise': 0.14348063846785547, 'A_repulsion': 0.2676620819468809, 'gamma': 0.07164017661155103, 'sigma_update': 0.25598184828748377, 'eta_learning': 0.6387105192695204, 'sigma_boundary': 9.388184078906896, 'alpha': 0.22142642820669856}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:26:38,264] Trial 46 finished with value: 0.05888506645951474 and parameters: {'sigma_noise': 0.12182742013077566, 'A_repulsion': 0.16241428394620122, 'gamma': 0.03422778504792219, 'sigma_update': 0.22074350671512077, 'eta_learning': 0.572336118188337, 'sigma_boundary': 8.859587951316046, 'alpha': 0.2817717974781454}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:26:43,014] Trial 47 finished with value: 0.07772612208649297 and parameters: {'sigma_noise': 0.10616572877545688, 'A_repulsion': 0.1486103884407739, 'gamma': 0.049663863437108144, 'sigma_update': 0.22487360526006617, 'eta_learning': 0.5246330482972548, 'sigma_boundary': 9.763644882170945, 'alpha': 0.13101471597942518}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:26:47,507] Trial 48 finished with value: 0.07534347863903379 and parameters: {'sigma_noise': 0.07307177945170394, 'A_repulsion': 0.16849832146586285, 'gamma': 0.1192153877558646, 'sigma_update': 0.27053891574246486, 'eta_learning': 0.5832744304933202, 'sigma_boundary': 8.73860054219681, 'alpha': 0.2886226809649308}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:26:52,500] Trial 49 finished with value: 0.05480386721189728 and parameters: {'sigma_noise': 0.12726415838541924, 'A_repulsion': 0.19526503785866228, 'gamma': 0.025999407311734328, 'sigma_update': 0.2290660905441766, 'eta_learning': 0.46017228615537764, 'sigma_boundary': 9.158354675901597, 'alpha': 0.25168542815780665}. Best is trial 21 with value: 0.05466158865401532.
[I 2026-07-01 13:26:57,423] Trial 50 finished with value: 0.21954415718140732 and parameters: {'sigma_noise': 0.11918983873060923, 'A_repulsion': 0.19468978714771293, 'gamma': 0.03400184604076217, 'sigma_update': 0.20032673717051802, 'eta_learning': 0.4716059721387301, 'sigma_boundary': 9.247830229185283, 'alpha': 0.0064026113564863985}. Best is trial 21 with value: 0.05466158865401532.

==============================
Running variant: Hybrid_alpha0_BE
==============================

--- Repetition 1/1, Fold 1/2 ---

[I 2026-07-01 13:41:33,598] Trial 0 finished with value: 0.33467525321297764 and parameters: {'sigma_noise': 0.08159018215585934, 'A_repulsion': 0.37739043882567497, 'eta_learning': 0.5677678301612995, 'sigma_boundary': 2.2603914995438967}. Best is trial 0 with value: 0.33467525321297764.
[I 2026-07-01 13:41:38,742] Trial 1 finished with value: 0.13822715591210152 and parameters: {'sigma_noise': 0.16015518523419017, 'A_repulsion': 0.0762456134605396, 'eta_learning': 0.3517393035221001, 'sigma_boundary': 0.42633209995629456}. Best is trial 1 with value: 0.13822715591210152.
[I 2026-07-01 13:41:44,489] Trial 2 finished with value: 0.4519567985785391 and parameters: {'sigma_noise': 0.11909376460804462, 'A_repulsion': 0.2998864037784978, 'eta_learning': 0.9712617163345879, 'sigma_boundary': 7.023618694914987}. Best is trial 1 with value: 0.13822715591210152.
[I 2026-07-01 13:41:51,146] Trial 3 finished with value: 0.5106521632980423 and parameters: {'sigma_noise': 0.3267775293777396, 'A_repulsion': 0.09880909744250538, 'eta_learning': 0.5008435317223655, 'sigma_boundary': 2.1018301929518968}. Best is trial 1 with value: 0.13822715591210152.
[I 2026-07-01 13:42:00,287] Trial 4 finished with value: 0.303751564785928 and parameters: {'sigma_noise': 0.3574582734868774, 'A_repulsion': 0.40919430081607444, 'eta_learning': 0.1411806041584652, 'sigma_boundary': 9.26022671518514}. Best is trial 1 with value: 0.13822715591210152.
[I 2026-07-01 13:42:05,225] Trial 5 finished with value: 0.07769818483156944 and parameters: {'sigma_noise': 0.04936763428732499, 'A_repulsion': 0.2746590027338448, 'eta_learning': 0.09086713200888086, 'sigma_boundary': 4.610328204003842}. Best is trial 5 with value: 0.07769818483156944.
[I 2026-07-01 13:42:11,134] Trial 6 finished with value: 0.41716422598464686 and parameters: {'sigma_noise': 0.17940623902781755, 'A_repulsion': 0.24433360359810447, 'eta_learning': 0.47918166793129985, 'sigma_boundary': 2.5871382402701117}. Best is trial 5 with value: 0.07769818483156944.
[I 2026-07-01 13:42:19,633] Trial 7 finished with value: 0.5623663972337117 and parameters: {'sigma_noise': 0.4481755238991748, 'A_repulsion': 0.19224766240446378, 'eta_learning': 0.43624790131316343, 'sigma_boundary': 9.165706358414651}. Best is trial 5 with value: 0.07769818483156944.
[I 2026-07-01 13:42:30,085] Trial 8 finished with value: 0.585241016833459 and parameters: {'sigma_noise': 0.4205988166956639, 'A_repulsion': 0.48267417324344636, 'eta_learning': 0.5299969500627982, 'sigma_boundary': 8.980488092706864}. Best is trial 5 with value: 0.07769818483156944.
[I 2026-07-01 13:42:36,926] Trial 9 finished with value: 0.5745955419829348 and parameters: {'sigma_noise': 0.2434816178733748, 'A_repulsion': 0.3012709148892999, 'eta_learning': 0.7138351848729305, 'sigma_boundary': 9.869860135285233}. Best is trial 5 with value: 0.07769818483156944.
[I 2026-07-01 13:42:40,848] Trial 10 finished with value: 0.07878726548519073 and parameters: {'sigma_noise': 0.03223326075523472, 'A_repulsion': 0.014965546694533177, 'eta_learning': 0.0296359583001155, 'sigma_boundary': 5.188627214833757}. Best is trial 5 with value: 0.07769818483156944.
[I 2026-07-01 13:42:45,023] Trial 11 finished with value: 0.09702110242604159 and parameters: {'sigma_noise': 0.010786795030699882, 'A_repulsion': 0.15442159483666734, 'eta_learning': 0.015647286836952552, 'sigma_boundary': 5.1489519114163995}. Best is trial 5 with value: 0.07769818483156944.
[I 2026-07-01 13:42:48,861] Trial 12 finished with value: 0.07392709495121708 and parameters: {'sigma_noise': 0.02103330016162034, 'A_repulsion': 0.023372799952104378, 'eta_learning': 0.19560978303068954, 'sigma_boundary': 5.301778103019326}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:42:53,158] Trial 13 finished with value: 0.07906126144955022 and parameters: {'sigma_noise': 0.0808013354415905, 'A_repulsion': 0.011866364908733135, 'eta_learning': 0.23954160731205215, 'sigma_boundary': 6.839747588549498}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:42:59,447] Trial 14 finished with value: 0.22640160931671596 and parameters: {'sigma_noise': 0.23865360195737356, 'A_repulsion': 0.2083928214628949, 'eta_learning': 0.20392941860203945, 'sigma_boundary': 3.5778191767824827}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:43:04,550] Trial 15 finished with value: 0.13033356487021733 and parameters: {'sigma_noise': 0.07428911594755858, 'A_repulsion': 0.30848078286376307, 'eta_learning': 0.2863405173827279, 'sigma_boundary': 6.4233096114593655}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:43:09,730] Trial 16 finished with value: 0.0974268069584767 and parameters: {'sigma_noise': 0.16592987028395698, 'A_repulsion': 0.12497193646750032, 'eta_learning': 0.10918019822492844, 'sigma_boundary': 4.085896186133885}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:43:14,328] Trial 17 finished with value: 0.10918591293320899 and parameters: {'sigma_noise': 0.013370693630184526, 'A_repulsion': 0.36792382989905825, 'eta_learning': 0.3443404310377909, 'sigma_boundary': 7.932773224832324}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:43:19,764] Trial 18 finished with value: 0.37392949867687264 and parameters: {'sigma_noise': 0.12437798211606357, 'A_repulsion': 0.2523622392645234, 'eta_learning': 0.6950424910706555, 'sigma_boundary': 5.666299187690124}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:43:25,802] Trial 19 finished with value: 0.14371457123796785 and parameters: {'sigma_noise': 0.2983058193508315, 'A_repulsion': 0.053420301787642344, 'eta_learning': 0.10819887095046969, 'sigma_boundary': 3.666490418282812}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:43:30,340] Trial 20 finished with value: 0.08315206529488899 and parameters: {'sigma_noise': 0.049567198240725, 'A_repulsion': 0.1661884104170201, 'eta_learning': 0.18473116213067026, 'sigma_boundary': 0.5295826996398025}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:43:34,259] Trial 21 finished with value: 0.0778806218648854 and parameters: {'sigma_noise': 0.039854516481249075, 'A_repulsion': 0.021456646905551158, 'eta_learning': 0.028563532970287762, 'sigma_boundary': 4.636278903279286}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:43:38,732] Trial 22 finished with value: 0.0750879389484296 and parameters: {'sigma_noise': 0.10465681952243522, 'A_repulsion': 0.05876031775313387, 'eta_learning': 0.0219555071447392, 'sigma_boundary': 4.3545139648264115}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:43:43,562] Trial 23 finished with value: 0.08042469448206804 and parameters: {'sigma_noise': 0.1226027301059589, 'A_repulsion': 0.11506351815427579, 'eta_learning': 0.09694152412089091, 'sigma_boundary': 5.6563539824979685}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:43:48,101] Trial 24 finished with value: 0.10576493003731575 and parameters: {'sigma_noise': 0.09249757135259282, 'A_repulsion': 0.06434077930954718, 'eta_learning': 0.2658072894663958, 'sigma_boundary': 3.093442246202616}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:43:54,046] Trial 25 finished with value: 0.3474535329567499 and parameters: {'sigma_noise': 0.19724548416441265, 'A_repulsion': 0.238670554944088, 'eta_learning': 0.36603210472533193, 'sigma_boundary': 4.366708755698376}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:43:58,555] Trial 26 finished with value: 0.08303723888593914 and parameters: {'sigma_noise': 0.05304502906612335, 'A_repulsion': 0.13916414916670478, 'eta_learning': 0.17842807867442528, 'sigma_boundary': 1.4898917558089062}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:44:03,242] Trial 27 finished with value: 0.07897305537634593 and parameters: {'sigma_noise': 0.10607287614295172, 'A_repulsion': 0.051851750648414824, 'eta_learning': 0.07176882590419363, 'sigma_boundary': 5.972363092440841}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:44:08,399] Trial 28 finished with value: 0.07669472997627769 and parameters: {'sigma_noise': 0.06368970992183977, 'A_repulsion': 0.3357331985633768, 'eta_learning': 0.15957467745849518, 'sigma_boundary': 7.765517112746814}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:44:15,228] Trial 29 finished with value: 0.572055540358669 and parameters: {'sigma_noise': 0.2163008435095139, 'A_repulsion': 0.3744570674189046, 'eta_learning': 0.6156484210470684, 'sigma_boundary': 7.76191773882338}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:44:21,590] Trial 30 finished with value: 0.5733266377032552 and parameters: {'sigma_noise': 0.15159160299368554, 'A_repulsion': 0.42805796913572175, 'eta_learning': 0.9619047516521761, 'sigma_boundary': 7.785681267139098}. Best is trial 12 with value: 0.07392709495121708.
[I 2026-07-01 13:44:26,641] Trial 31 finished with value: 0.07330478028168659 and parameters: {'sigma_noise': 0.06953849557813785, 'A_repulsion': 0.3376047102455324, 'eta_learning': 0.14120315254600446, 'sigma_boundary': 4.862614392659848}. Best is trial 31 with value: 0.07330478028168659.
[I 2026-07-01 13:44:31,674] Trial 32 finished with value: 0.13019074361263203 and parameters: {'sigma_noise': 0.07083056005615666, 'A_repulsion': 0.34864956935801394, 'eta_learning': 0.28667699997670537, 'sigma_boundary': 6.6287289306947175}. Best is trial 31 with value: 0.07330478028168659.
[I 2026-07-01 13:44:37,475] Trial 33 finished with value: 0.1272412820840606 and parameters: {'sigma_noise': 0.14073379374990788, 'A_repulsion': 0.32927255686140017, 'eta_learning': 0.16850597489513847, 'sigma_boundary': 7.332891855388585}. Best is trial 31 with value: 0.07330478028168659.
[I 2026-07-01 13:44:42,921] Trial 34 finished with value: 0.1636440598725216 and parameters: {'sigma_noise': 0.09585975508019112, 'A_repulsion': 0.4128390663600322, 'eta_learning': 0.23992796189333654, 'sigma_boundary': 3.6280501244244103}. Best is trial 31 with value: 0.07330478028168659.
[I 2026-07-01 13:44:47,273] Trial 35 finished with value: 0.11831633438666271 and parameters: {'sigma_noise': 0.0672819075279178, 'A_repulsion': 0.08350534634098926, 'eta_learning': 0.389941920840326, 'sigma_boundary': 6.1385835441535574}. Best is trial 31 with value: 0.07330478028168659.
[I 2026-07-01 13:44:52,290] Trial 36 finished with value: 0.1445685746247537 and parameters: {'sigma_noise': 0.0360643264692939, 'A_repulsion': 0.4876918133047552, 'eta_learning': 0.32110945386805634, 'sigma_boundary': 1.9836628980085855}. Best is trial 31 with value: 0.07330478028168659.
[I 2026-07-01 13:44:57,654] Trial 37 finished with value: 0.10504324308439669 and parameters: {'sigma_noise': 0.11063175923675614, 'A_repulsion': 0.2778727549646822, 'eta_learning': 0.1378770801950399, 'sigma_boundary': 2.8796875470435728}. Best is trial 31 with value: 0.07330478028168659.
[I 2026-07-01 13:45:02,494] Trial 38 finished with value: 0.08636130798263733 and parameters: {'sigma_noise': 0.018819423508750877, 'A_repulsion': 0.45333448233390294, 'eta_learning': 0.07498094958426338, 'sigma_boundary': 5.181320999136146}. Best is trial 31 with value: 0.07330478028168659.
[I 2026-07-01 13:45:08,635] Trial 39 finished with value: 0.38456819223868455 and parameters: {'sigma_noise': 0.14221642027395065, 'A_repulsion': 0.3940525941126544, 'eta_learning': 0.4274081461232522, 'sigma_boundary': 8.611219729501467}. Best is trial 31 with value: 0.07330478028168659.
[I 2026-07-01 13:45:14,038] Trial 40 finished with value: 0.18214036351363194 and parameters: {'sigma_noise': 0.2608787123155647, 'A_repulsion': 0.036985381183127816, 'eta_learning': 0.20680662071358577, 'sigma_boundary': 4.709870913110788}. Best is trial 31 with value: 0.07330478028168659.
[I 2026-07-01 13:45:18,731] Trial 41 finished with value: 0.07721301515147802 and parameters: {'sigma_noise': 0.05262818453249057, 'A_repulsion': 0.2742845058376704, 'eta_learning': 0.06945470944907065, 'sigma_boundary': 4.099833346865852}. Best is trial 31 with value: 0.07330478028168659.
[I 2026-07-01 13:45:23,670] Trial 42 finished with value: 0.07263992068780749 and parameters: {'sigma_noise': 0.05641906062584586, 'A_repulsion': 0.3385627202835674, 'eta_learning': 0.1402536337207132, 'sigma_boundary': 4.038441516722843}. Best is trial 42 with value: 0.07263992068780749.
[I 2026-07-01 13:45:28,635] Trial 43 finished with value: 0.07343672617473421 and parameters: {'sigma_noise': 0.06345865615720914, 'A_repulsion': 0.3344058271104626, 'eta_learning': 0.14345800316760535, 'sigma_boundary': 3.4234114914146696}. Best is trial 42 with value: 0.07263992068780749.
[I 2026-07-01 13:45:34,114] Trial 44 finished with value: 0.08745307748607133 and parameters: {'sigma_noise': 0.08812347246868307, 'A_repulsion': 0.3560734193032463, 'eta_learning': 0.13371738317531423, 'sigma_boundary': 3.233286698438065}. Best is trial 42 with value: 0.07263992068780749.
[I 2026-07-01 13:45:38,696] Trial 45 finished with value: 0.0969218000018503 and parameters: {'sigma_noise': 0.02838705264386872, 'A_repulsion': 0.31785570256544116, 'eta_learning': 0.015267552698541131, 'sigma_boundary': 2.4356300148245693}. Best is trial 42 with value: 0.07263992068780749.
[I 2026-07-01 13:45:43,913] Trial 46 finished with value: 0.12727081389996822 and parameters: {'sigma_noise': 0.12614079141586493, 'A_repulsion': 0.210726531695923, 'eta_learning': 0.21735142520546386, 'sigma_boundary': 4.0885542287336}. Best is trial 42 with value: 0.07263992068780749.
[I 2026-07-01 13:45:49,925] Trial 47 finished with value: 0.0768095587637181 and parameters: {'sigma_noise': 0.17835766933351235, 'A_repulsion': 0.28771048733488713, 'eta_learning': 0.04735038683368309, 'sigma_boundary': 5.553936626881793}. Best is trial 42 with value: 0.07263992068780749.
[I 2026-07-01 13:45:53,928] Trial 48 finished with value: 0.07516850836876042 and parameters: {'sigma_noise': 0.010260187617255778, 'A_repulsion': 0.08906652552424038, 'eta_learning': 0.13443244277041813, 'sigma_boundary': 4.930506042783937}. Best is trial 42 with value: 0.07263992068780749.
[I 2026-07-01 13:46:03,127] Trial 49 finished with value: 0.5646594252002693 and parameters: {'sigma_noise': 0.4048834907951614, 'A_repulsion': 0.38621595055865326, 'eta_learning': 0.25725910487097375, 'sigma_boundary': 3.4095216267277006}. Best is trial 42 with value: 0.07263992068780749.
[I 2026-07-01 13:46:08,666] Trial 50 finished with value: 0.23510178412342636 and parameters: {'sigma_noise': 0.09093767083589424, 'A_repulsion': 0.4384309084562832, 'eta_learning': 0.3155987007272094, 'sigma_boundary': 1.649945862359309}. Best is trial 42 with value: 0.07263992068780749.
[I 2026-07-01 13:46:12,657] Trial 51 finished with value: 0.07496593756640606 and parameters: {'sigma_noise': 0.013372895663336886, 'A_repulsion': 0.08699776310253497, 'eta_learning': 0.12751405229459153, 'sigma_boundary': 5.007274633486743}. Best is trial 42 with value: 0.07263992068780749.
[I 2026-07-01 13:46:16,899] Trial 52 finished with value: 0.14567032154534043 and parameters: {'sigma_noise': 0.030182895188579494, 'A_repulsion': 0.10380596115046449, 'eta_learning': 0.8857298420808366, 'sigma_boundary': 4.302509355969477}. Best is trial 42 with value: 0.07263992068780749.
[I 2026-07-01 13:46:20,895] Trial 53 finished with value: 0.0736400291569753 and parameters: {'sigma_noise': 0.060325770585943975, 'A_repulsion': 0.006251850734608346, 'eta_learning': 0.09695895560008827, 'sigma_boundary': 5.181138707067888}. Best is trial 42 with value: 0.07263992068780749.
[I 2026-07-01 13:46:24,888] Trial 54 finished with value: 0.07183761729407345 and parameters: {'sigma_noise': 0.05327264274670454, 'A_repulsion': 0.011659731730157734, 'eta_learning': 0.11504798524188718, 'sigma_boundary': 5.472595379505671}. Best is trial 54 with value: 0.07183761729407345.
[I 2026-07-01 13:46:28,886] Trial 55 finished with value: 0.0619660414036577 and parameters: {'sigma_noise': 0.05346778062272986, 'A_repulsion': 0.0010548193117985542, 'eta_learning': 0.18950727099378634, 'sigma_boundary': 6.07672041938597}. Best is trial 55 with value: 0.0619660414036577.
[I 2026-07-01 13:46:32,993] Trial 56 finished with value: 0.07477580269352457 and parameters: {'sigma_noise': 0.06040688729418481, 'A_repulsion': 0.00027649176890112584, 'eta_learning': 0.06200473227995318, 'sigma_boundary': 6.349297319643352}. Best is trial 55 with value: 0.0619660414036577.
[I 2026-07-01 13:46:37,342] Trial 57 finished with value: 0.07576537821583336 and parameters: {'sigma_noise': 0.07653814184548298, 'A_repulsion': 0.03453090921371469, 'eta_learning': 0.10390492861806044, 'sigma_boundary': 6.997153934572545}. Best is trial 55 with value: 0.0619660414036577.
[I 2026-07-01 13:46:41,428] Trial 58 finished with value: 0.06200964017511151 and parameters: {'sigma_noise': 0.045325820925688466, 'A_repulsion': 0.0018581751905639475, 'eta_learning': 0.21885314664378314, 'sigma_boundary': 5.863831214718736}. Best is trial 55 with value: 0.0619660414036577.
[I 2026-07-01 13:46:45,615] Trial 59 finished with value: 0.06241719834196388 and parameters: {'sigma_noise': 0.0439753053727994, 'A_repulsion': 0.036321855450902114, 'eta_learning': 0.21981339545587764, 'sigma_boundary': 5.759731155261309}. Best is trial 55 with value: 0.0619660414036577.
[I 2026-07-01 13:46:49,682] Trial 60 finished with value: 0.06279677513200148 and parameters: {'sigma_noise': 0.04230362272908009, 'A_repulsion': 0.034807220885374676, 'eta_learning': 0.21396062208745847, 'sigma_boundary': 5.99551241822929}. Best is trial 55 with value: 0.0619660414036577.
[I 2026-07-01 13:46:53,748] Trial 61 finished with value: 0.06653807283199845 and parameters: {'sigma_noise': 0.04969094890552856, 'A_repulsion': 0.0348221704752804, 'eta_learning': 0.2247566207093427, 'sigma_boundary': 5.8954847465008715}. Best is trial 55 with value: 0.0619660414036577.
[I 2026-07-01 13:46:57,788] Trial 62 finished with value: 0.06275798185819137 and parameters: {'sigma_noise': 0.04345513300146109, 'A_repulsion': 0.036991610722296474, 'eta_learning': 0.23360365808042813, 'sigma_boundary': 5.814777965006257}. Best is trial 55 with value: 0.0619660414036577.
[I 2026-07-01 13:47:01,814] Trial 63 finished with value: 0.07671611196108385 and parameters: {'sigma_noise': 0.042182070345009114, 'A_repulsion': 0.037714517834894476, 'eta_learning': 0.29210915982609487, 'sigma_boundary': 5.846276435611678}. Best is trial 55 with value: 0.0619660414036577.
[I 2026-07-01 13:47:05,912] Trial 64 finished with value: 0.06092920900230467 and parameters: {'sigma_noise': 0.029616686854023508, 'A_repulsion': 0.06919588408761974, 'eta_learning': 0.22353424987802492, 'sigma_boundary': 6.309196577276248}. Best is trial 64 with value: 0.06092920900230467.
[I 2026-07-01 13:47:09,987] Trial 65 finished with value: 0.06304002845881784 and parameters: {'sigma_noise': 0.03425143258066571, 'A_repulsion': 0.07331614682272741, 'eta_learning': 0.22304766989368402, 'sigma_boundary': 7.338111574449497}. Best is trial 64 with value: 0.06092920900230467.
[I 2026-07-01 13:47:13,928] Trial 66 finished with value: 0.06290178057958012 and parameters: {'sigma_noise': 0.028384187142289283, 'A_repulsion': 0.06620440403125355, 'eta_learning': 0.2604070589783286, 'sigma_boundary': 6.654966702599892}. Best is trial 64 with value: 0.06092920900230467.
[I 2026-07-01 13:47:17,893] Trial 67 finished with value: 0.07973638249918072 and parameters: {'sigma_noise': 0.027917759301361124, 'A_repulsion': 0.05102376125351637, 'eta_learning': 0.36165266926356704, 'sigma_boundary': 6.255314538221148}. Best is trial 64 with value: 0.06092920900230467.

--- Repetition 1/1, Fold 2/2 ---

[I 2026-07-01 13:56:47,537] Trial 0 finished with value: 0.5415095755648924 and parameters: {'sigma_noise': 0.23130453864636627, 'A_repulsion': 0.18301128532134425, 'eta_learning': 0.452841141347309, 'sigma_boundary': 3.625248493571174}. Best is trial 0 with value: 0.5415095755648924.
[I 2026-07-01 13:56:54,929] Trial 1 finished with value: 0.3354729581974687 and parameters: {'sigma_noise': 0.2896830130226404, 'A_repulsion': 0.26985879734803747, 'eta_learning': 0.35513063031140035, 'sigma_boundary': 0.17367317815512254}. Best is trial 1 with value: 0.3354729581974687.
[I 2026-07-01 13:57:00,418] Trial 2 finished with value: 0.10214010665188505 and parameters: {'sigma_noise': 0.2482563016050371, 'A_repulsion': 0.01307051444869517, 'eta_learning': 0.10747910049641866, 'sigma_boundary': 8.469681924782693}. Best is trial 2 with value: 0.10214010665188505.
[I 2026-07-01 13:57:09,757] Trial 3 finished with value: 0.7139002267378138 and parameters: {'sigma_noise': 0.37527668163972994, 'A_repulsion': 0.4418781743877959, 'eta_learning': 0.5936713489700887, 'sigma_boundary': 0.31767675031089376}. Best is trial 2 with value: 0.10214010665188505.
[I 2026-07-01 13:57:15,764] Trial 4 finished with value: 0.5770723988516879 and parameters: {'sigma_noise': 0.27004342949694843, 'A_repulsion': 0.09121359324192646, 'eta_learning': 0.6310765168478065, 'sigma_boundary': 1.9789875957328684}. Best is trial 2 with value: 0.10214010665188505.
[I 2026-07-01 13:57:22,086] Trial 5 finished with value: 0.48493826994777467 and parameters: {'sigma_noise': 0.12337161534144786, 'A_repulsion': 0.49109469278048695, 'eta_learning': 0.40356036120579797, 'sigma_boundary': 5.455666627237184}. Best is trial 2 with value: 0.10214010665188505.
[I 2026-07-01 13:57:27,232] Trial 6 finished with value: 0.3777843418601735 and parameters: {'sigma_noise': 0.07510717462073618, 'A_repulsion': 0.33132735380182404, 'eta_learning': 0.9473826639588159, 'sigma_boundary': 6.091591059358608}. Best is trial 2 with value: 0.10214010665188505.
[I 2026-07-01 13:57:33,896] Trial 7 finished with value: 0.668203515808338 and parameters: {'sigma_noise': 0.4113685825474536, 'A_repulsion': 0.026287693760968123, 'eta_learning': 0.9423902250678173, 'sigma_boundary': 0.9077266822128384}. Best is trial 2 with value: 0.10214010665188505.
[I 2026-07-01 13:57:43,047] Trial 8 finished with value: 0.7020294034267102 and parameters: {'sigma_noise': 0.40233977013419053, 'A_repulsion': 0.38998526586764987, 'eta_learning': 0.2727413780278623, 'sigma_boundary': 3.466497258749317}. Best is trial 2 with value: 0.10214010665188505.
[I 2026-07-01 13:57:48,540] Trial 9 finished with value: 0.11131510901125051 and parameters: {'sigma_noise': 0.22035871008742997, 'A_repulsion': 0.09071487962925551, 'eta_learning': 0.09370343702572312, 'sigma_boundary': 5.9285589383617285}. Best is trial 2 with value: 0.10214010665188505.
[I 2026-07-01 13:57:53,433] Trial 10 finished with value: 0.087928645512129 and parameters: {'sigma_noise': 0.1633272895373476, 'A_repulsion': 0.0012154227291707453, 'eta_learning': 0.14854906742184681, 'sigma_boundary': 9.726122221163088}. Best is trial 10 with value: 0.087928645512129.
[I 2026-07-01 13:57:58,334] Trial 11 finished with value: 0.1256524717116598 and parameters: {'sigma_noise': 0.1670125070332722, 'A_repulsion': 0.0009002239173387938, 'eta_learning': 0.019160224821420435, 'sigma_boundary': 9.797744162785973}. Best is trial 10 with value: 0.087928645512129.
[I 2026-07-01 13:58:02,834] Trial 12 finished with value: 0.12126058928308038 and parameters: {'sigma_noise': 0.028456391108282464, 'A_repulsion': 0.15942555168444555, 'eta_learning': 0.16648503678435356, 'sigma_boundary': 9.803952104254865}. Best is trial 10 with value: 0.087928645512129.
[I 2026-07-01 13:58:09,198] Trial 13 finished with value: 0.21033919608246437 and parameters: {'sigma_noise': 0.3272607392366206, 'A_repulsion': 0.08432599036404262, 'eta_learning': 0.1818177900839777, 'sigma_boundary': 8.264484258807961}. Best is trial 10 with value: 0.087928645512129.
[I 2026-07-01 13:58:14,826] Trial 14 finished with value: 0.1188871767150946 and parameters: {'sigma_noise': 0.1472241855528878, 'A_repulsion': 0.18588421076255757, 'eta_learning': 0.2398285134318222, 'sigma_boundary': 7.894100457677789}. Best is trial 10 with value: 0.087928645512129.
[I 2026-07-01 13:58:20,053] Trial 15 finished with value: 0.12986323213549406 and parameters: {'sigma_noise': 0.20983931794526856, 'A_repulsion': 0.04245776462368783, 'eta_learning': 0.016675257202362903, 'sigma_boundary': 7.866752479290457}. Best is trial 10 with value: 0.087928645512129.
[I 2026-07-01 13:58:24,946] Trial 16 finished with value: 0.21841140773235815 and parameters: {'sigma_noise': 0.10230556314905162, 'A_repulsion': 0.1336319577187981, 'eta_learning': 0.7669391626678903, 'sigma_boundary': 8.88109643259659}. Best is trial 10 with value: 0.087928645512129.
[I 2026-07-01 13:58:31,116] Trial 17 finished with value: 0.3111697417536048 and parameters: {'sigma_noise': 0.183045176256389, 'A_repulsion': 0.2566740751893141, 'eta_learning': 0.30247733784870845, 'sigma_boundary': 6.904953537870068}. Best is trial 10 with value: 0.087928645512129.
[I 2026-07-01 13:58:37,323] Trial 18 finished with value: 0.17587948032930004 and parameters: {'sigma_noise': 0.3354750374350527, 'A_repulsion': 0.06880601354718228, 'eta_learning': 0.14328413672113288, 'sigma_boundary': 6.984557562766412}. Best is trial 10 with value: 0.087928645512129.
[I 2026-07-01 13:58:42,725] Trial 19 finished with value: 0.39577388730052065 and parameters: {'sigma_noise': 0.25114434333495006, 'A_repulsion': 0.0064246786791272706, 'eta_learning': 0.5768823397162868, 'sigma_boundary': 4.350398657886668}. Best is trial 10 with value: 0.087928645512129.
[I 2026-07-01 13:58:47,449] Trial 20 finished with value: 0.13618595516350346 and parameters: {'sigma_noise': 0.052959214781045705, 'A_repulsion': 0.2205062920184933, 'eta_learning': 0.7321159079184695, 'sigma_boundary': 9.043616053090284}. Best is trial 10 with value: 0.087928645512129.
[I 2026-07-01 13:58:53,037] Trial 21 finished with value: 0.11012699387820055 and parameters: {'sigma_noise': 0.20424720627538553, 'A_repulsion': 0.11352632604907582, 'eta_learning': 0.09316626507832905, 'sigma_boundary': 6.205236291842352}. Best is trial 10 with value: 0.087928645512129.
[I 2026-07-01 13:58:58,702] Trial 22 finished with value: 0.10793494638892141 and parameters: {'sigma_noise': 0.1868568704691009, 'A_repulsion': 0.12565358074941757, 'eta_learning': 0.09797561502292937, 'sigma_boundary': 6.895290516171794}. Best is trial 10 with value: 0.087928645512129.
[I 2026-07-01 13:59:03,442] Trial 23 finished with value: 0.08522805728022861 and parameters: {'sigma_noise': 0.14180291200256168, 'A_repulsion': 0.04290802570726043, 'eta_learning': 0.23911460530195, 'sigma_boundary': 6.950337411677577}. Best is trial 23 with value: 0.08522805728022861.
[I 2026-07-01 13:59:08,360] Trial 24 finished with value: 0.08415977182911717 and parameters: {'sigma_noise': 0.13347984486939765, 'A_repulsion': 0.04793466520626258, 'eta_learning': 0.22601835417293992, 'sigma_boundary': 8.897788255844423}. Best is trial 24 with value: 0.08415977182911717.
[I 2026-07-01 13:59:13,025] Trial 25 finished with value: 0.08972206859926056 and parameters: {'sigma_noise': 0.11696034774240265, 'A_repulsion': 0.05084653914167177, 'eta_learning': 0.34176948749059066, 'sigma_boundary': 9.904414418745409}. Best is trial 24 with value: 0.08415977182911717.
[I 2026-07-01 13:59:17,995] Trial 26 finished with value: 0.08735006849138019 and parameters: {'sigma_noise': 0.14705742209044537, 'A_repulsion': 0.06069261066436115, 'eta_learning': 0.23032514391662331, 'sigma_boundary': 7.474658049398404}. Best is trial 24 with value: 0.08415977182911717.
[I 2026-07-01 13:59:22,537] Trial 27 finished with value: 0.09569565740543688 and parameters: {'sigma_noise': 0.09768559043206618, 'A_repulsion': 0.05489012706970583, 'eta_learning': 0.47325458847618357, 'sigma_boundary': 7.4953913333308115}. Best is trial 24 with value: 0.08415977182911717.
[I 2026-07-01 13:59:26,777] Trial 28 finished with value: 0.11101208283299063 and parameters: {'sigma_noise': 0.01217116133970056, 'A_repulsion': 0.2182031704882113, 'eta_learning': 0.23356204832849944, 'sigma_boundary': 4.970748852618075}. Best is trial 24 with value: 0.08415977182911717.
[I 2026-07-01 13:59:31,388] Trial 29 finished with value: 0.0826276124432436 and parameters: {'sigma_noise': 0.06252554693694008, 'A_repulsion': 0.1741476522613656, 'eta_learning': 0.3710476211934355, 'sigma_boundary': 7.405360291478555}. Best is trial 29 with value: 0.0826276124432436.
[I 2026-07-01 13:59:36,526] Trial 30 finished with value: 0.10076175217616447 and parameters: {'sigma_noise': 0.06179105637001629, 'A_repulsion': 0.3016949418779565, 'eta_learning': 0.4048647595032241, 'sigma_boundary': 8.942445323275855}. Best is trial 29 with value: 0.0826276124432436.
[I 2026-07-01 13:59:41,851] Trial 31 finished with value: 0.10412413444197863 and parameters: {'sigma_noise': 0.1425390624437451, 'A_repulsion': 0.1550447887160695, 'eta_learning': 0.2276239416133749, 'sigma_boundary': 7.300878333816969}. Best is trial 29 with value: 0.0826276124432436.
[I 2026-07-01 13:59:46,714] Trial 32 finished with value: 0.1000737256212071 and parameters: {'sigma_noise': 0.0801037358702483, 'A_repulsion': 0.19635758349179797, 'eta_learning': 0.32227007846634526, 'sigma_boundary': 6.360075852755742}. Best is trial 29 with value: 0.0826276124432436.
[I 2026-07-01 13:59:50,968] Trial 33 finished with value: 0.08668919322179379 and parameters: {'sigma_noise': 0.040536642793832775, 'A_repulsion': 0.10982044007734235, 'eta_learning': 0.4066835607425523, 'sigma_boundary': 8.438184155860164}. Best is trial 29 with value: 0.0826276124432436.
[I 2026-07-01 13:59:55,435] Trial 34 finished with value: 0.08245848003898947 and parameters: {'sigma_noise': 0.0579117286174579, 'A_repulsion': 0.11103281322769051, 'eta_learning': 0.4176530184664674, 'sigma_boundary': 8.470766812056025}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:00:00,338] Trial 35 finished with value: 0.13479013028496495 and parameters: {'sigma_noise': 0.09311669610790788, 'A_repulsion': 0.15012996191138916, 'eta_learning': 0.5153542340326895, 'sigma_boundary': 9.004121198289548}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:00:05,278] Trial 36 finished with value: 0.17144077755871814 and parameters: {'sigma_noise': 0.12244270677233406, 'A_repulsion': 0.08798538727733535, 'eta_learning': 0.5385070080159056, 'sigma_boundary': 8.147034890608023}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:00:09,759] Trial 37 finished with value: 0.08434205376170491 and parameters: {'sigma_noise': 0.01389343565257934, 'A_repulsion': 0.2196009933685045, 'eta_learning': 0.42876718126237273, 'sigma_boundary': 5.079311892737167}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:00:14,352] Trial 38 finished with value: 0.09135764293284201 and parameters: {'sigma_noise': 0.017636970333172654, 'A_repulsion': 0.28930071853659656, 'eta_learning': 0.44358857500578314, 'sigma_boundary': 3.1916212142901452}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:00:19,176] Trial 39 finished with value: 0.08729539512899237 and parameters: {'sigma_noise': 0.051478108461891894, 'A_repulsion': 0.2308160769708631, 'eta_learning': 0.37496989909483136, 'sigma_boundary': 4.321015106109137}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:00:24,406] Trial 40 finished with value: 0.2055270221924763 and parameters: {'sigma_noise': 0.07148331513302938, 'A_repulsion': 0.3501437454713421, 'eta_learning': 0.4586982925496891, 'sigma_boundary': 2.8679054174535357}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:00:31,357] Trial 41 finished with value: 0.49557768227810867 and parameters: {'sigma_noise': 0.4493276154811531, 'A_repulsion': 0.0322322713336807, 'eta_learning': 0.29073138698231404, 'sigma_boundary': 5.756111208962119}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:00:35,688] Trial 42 finished with value: 0.08496443742518224 and parameters: {'sigma_noise': 0.02957030078244903, 'A_repulsion': 0.17255176214404666, 'eta_learning': 0.36255984272038916, 'sigma_boundary': 4.988120088346455}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:00:40,161] Trial 43 finished with value: 0.08496443742518224 and parameters: {'sigma_noise': 0.028558713370549608, 'A_repulsion': 0.18141179049364936, 'eta_learning': 0.3617722060251205, 'sigma_boundary': 5.058948419096273}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:00:44,619] Trial 44 finished with value: 0.09516052459105269 and parameters: {'sigma_noise': 0.03718429330832385, 'A_repulsion': 0.17536224226579603, 'eta_learning': 0.6623353142472207, 'sigma_boundary': 2.4616647361905333}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:00:49,624] Trial 45 finished with value: 0.13757395834056801 and parameters: {'sigma_noise': 0.08706282154396479, 'A_repulsion': 0.2039678861760564, 'eta_learning': 0.4419420351790258, 'sigma_boundary': 3.9920997893940786}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:00:54,519] Trial 46 finished with value: 0.12327065524262722 and parameters: {'sigma_noise': 0.0559544663208356, 'A_repulsion': 0.24100966338819368, 'eta_learning': 0.5508873676125732, 'sigma_boundary': 1.2829751831553229}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:00:58,993] Trial 47 finished with value: 0.08834968957172855 and parameters: {'sigma_noise': 0.01126446204714852, 'A_repulsion': 0.26528230302455624, 'eta_learning': 0.4970595860298193, 'sigma_boundary': 5.133497331628193}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:01:04,051] Trial 48 finished with value: 0.11139393832943038 and parameters: {'sigma_noise': 0.111098437498882, 'A_repulsion': 0.14058490873175117, 'eta_learning': 0.38040626300954883, 'sigma_boundary': 9.391909036078117}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:01:08,865] Trial 49 finished with value: 0.134203554984973 and parameters: {'sigma_noise': 0.07212328239505139, 'A_repulsion': 0.17055599321986722, 'eta_learning': 0.6254755230830602, 'sigma_boundary': 6.50748306198122}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:01:13,176] Trial 50 finished with value: 0.11097238272314389 and parameters: {'sigma_noise': 0.03854294813674496, 'A_repulsion': 0.10331557576549483, 'eta_learning': 0.28760361784516864, 'sigma_boundary': 4.6326208474366934}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:01:17,652] Trial 51 finished with value: 0.08637041833218642 and parameters: {'sigma_noise': 0.02710039855326802, 'A_repulsion': 0.20652779766776508, 'eta_learning': 0.35385562566251333, 'sigma_boundary': 5.40596961659975}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:01:22,099] Trial 52 finished with value: 0.08677254504027282 and parameters: {'sigma_noise': 0.03244272984509384, 'A_repulsion': 0.18789590967250383, 'eta_learning': 0.4258899626344852, 'sigma_boundary': 4.892032205491944}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:01:26,769] Trial 53 finished with value: 0.08306266803409917 and parameters: {'sigma_noise': 0.06046275967864313, 'A_repulsion': 0.1669591973867263, 'eta_learning': 0.33223167936956743, 'sigma_boundary': 5.579523680616528}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:01:31,339] Trial 54 finished with value: 0.08350781555605996 and parameters: {'sigma_noise': 0.0610997595118336, 'A_repulsion': 0.1266302588586559, 'eta_learning': 0.3251225591640973, 'sigma_boundary': 8.635133302261007}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:01:36,105] Trial 55 finished with value: 0.08809123576983316 and parameters: {'sigma_noise': 0.06326683803568339, 'A_repulsion': 0.12213740252376178, 'eta_learning': 0.3115795265711955, 'sigma_boundary': 8.581153646584639}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:01:40,803] Trial 56 finished with value: 0.09390867177173026 and parameters: {'sigma_noise': 0.08388747319609546, 'A_repulsion': 0.08715033455514698, 'eta_learning': 0.1950539639325696, 'sigma_boundary': 9.390763914439091}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:01:47,452] Trial 57 finished with value: 0.35096246923132907 and parameters: {'sigma_noise': 0.29558785480641236, 'A_repulsion': 0.13757641198056475, 'eta_learning': 0.2628561799523418, 'sigma_boundary': 7.944673473573454}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:01:52,651] Trial 58 finished with value: 0.12524152855172127 and parameters: {'sigma_noise': 0.12768695130907923, 'A_repulsion': 0.15908431975702153, 'eta_learning': 0.32821879502643203, 'sigma_boundary': 8.62591435154738}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:01:56,924] Trial 59 finished with value: 0.12464973669832578 and parameters: {'sigma_noise': 0.04788736127451932, 'A_repulsion': 0.0714149171931782, 'eta_learning': 0.18945003815174813, 'sigma_boundary': 9.394852128236126}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:02:01,692] Trial 60 finished with value: 0.1076242169963579 and parameters: {'sigma_noise': 0.10154628494463042, 'A_repulsion': 0.09844339471920505, 'eta_learning': 0.4883542563708305, 'sigma_boundary': 7.766364163042647}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:02:06,355] Trial 61 finished with value: 0.08982844742292026 and parameters: {'sigma_noise': 0.06475151076502855, 'A_repulsion': 0.165817576929702, 'eta_learning': 0.38646563854578075, 'sigma_boundary': 5.703189014413015}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:02:10,590] Trial 62 finished with value: 0.09709144007244973 and parameters: {'sigma_noise': 0.022066466974284972, 'A_repulsion': 0.12834918163525494, 'eta_learning': 0.9844000412524825, 'sigma_boundary': 3.7992277665008727}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:02:15,246] Trial 63 finished with value: 0.09226101807287017 and parameters: {'sigma_noise': 0.04631868710884706, 'A_repulsion': 0.22168631568670213, 'eta_learning': 0.2619482040131843, 'sigma_boundary': 6.609712706446918}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:02:20,266] Trial 64 finished with value: 0.10391357196696176 and parameters: {'sigma_noise': 0.08603544508658502, 'A_repulsion': 0.248094536029752, 'eta_learning': 0.33559310423934013, 'sigma_boundary': 6.031515869331745}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:02:27,182] Trial 65 finished with value: 0.6068720457094384 and parameters: {'sigma_noise': 0.17175297024841502, 'A_repulsion': 0.46708411554290286, 'eta_learning': 0.4096639073563281, 'sigma_boundary': 5.405366904227774}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:02:31,148] Trial 66 finished with value: 0.13089361042348058 and parameters: {'sigma_noise': 0.011088915695759947, 'A_repulsion': 0.07562142042715482, 'eta_learning': 0.11872366286282386, 'sigma_boundary': 8.216088131689672}. Best is trial 34 with value: 0.08245848003898947.
[I 2026-07-01 14:02:37,357] Trial 67 finished with value: 0.6210031634733487 and parameters: {'sigma_noise': 0.24206939447337505, 'A_repulsion': 0.14785437180087752, 'eta_learning': 0.8494141321993636, 'sigma_boundary': 4.389921655064977}. Best is trial 34 with value: 0.08245848003898947.

==============================
Running variant: Hybrid_alpha1_SC
==============================

--- Repetition 1/1, Fold 1/2 ---

[I 2026-07-01 14:13:29,682] Trial 0 finished with value: 0.08239920825138705 and parameters: {'sigma_noise': 0.08159018215585934, 'A_repulsion': 0.37739043882567497, 'gamma': 0.5677678301612995, 'sigma_update': 0.1654324459144433}. Best is trial 0 with value: 0.08239920825138705.
[I 2026-07-01 14:13:35,047] Trial 1 finished with value: 0.18942241022540598 and parameters: {'sigma_noise': 0.16015518523419017, 'A_repulsion': 0.0762456134605396, 'gamma': 0.3517393035221001, 'sigma_update': 0.03875567056755187}. Best is trial 0 with value: 0.08239920825138705.
[I 2026-07-01 14:13:40,497] Trial 2 finished with value: 0.07847283096080872 and parameters: {'sigma_noise': 0.11909376460804462, 'A_repulsion': 0.2998864037784978, 'gamma': 0.9712617163345879, 'sigma_update': 0.49442411406319725}. Best is trial 2 with value: 0.07847283096080872.
[I 2026-07-01 14:13:46,851] Trial 3 finished with value: 0.09933688702870332 and parameters: {'sigma_noise': 0.3267775293777396, 'A_repulsion': 0.09880909744250538, 'gamma': 0.5008435317223655, 'sigma_update': 0.15448076407775865}. Best is trial 2 with value: 0.07847283096080872.
[I 2026-07-01 14:13:55,462] Trial 4 finished with value: 0.14023429793232198 and parameters: {'sigma_noise': 0.3574582734868774, 'A_repulsion': 0.40919430081607444, 'gamma': 0.1411806041584652, 'sigma_update': 0.6489045478956703}. Best is trial 2 with value: 0.07847283096080872.
[I 2026-07-01 14:14:00,172] Trial 5 finished with value: 0.07252263279512475 and parameters: {'sigma_noise': 0.04936763428732499, 'A_repulsion': 0.2746590027338448, 'gamma': 0.09086713200888086, 'sigma_update': 0.3277403864627278}. Best is trial 5 with value: 0.07252263279512475.
[I 2026-07-01 14:14:06,203] Trial 6 finished with value: 0.06147713749227457 and parameters: {'sigma_noise': 0.17940623902781755, 'A_repulsion': 0.24433360359810447, 'gamma': 0.47918166793129985, 'sigma_update': 0.18800053911775547}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:14:14,171] Trial 7 finished with value: 0.14884371569011756 and parameters: {'sigma_noise': 0.4481755238991748, 'A_repulsion': 0.19224766240446378, 'gamma': 0.43624790131316343, 'sigma_update': 0.6423761148454564}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:14:24,327] Trial 8 finished with value: 0.13291249122790255 and parameters: {'sigma_noise': 0.4205988166956639, 'A_repulsion': 0.48267417324344636, 'gamma': 0.5299969500627982, 'sigma_update': 0.629583261658432}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:14:30,933] Trial 9 finished with value: 0.06370335977212946 and parameters: {'sigma_noise': 0.2434816178733748, 'A_repulsion': 0.3012709148892999, 'gamma': 0.7138351848729305, 'sigma_update': 0.6910113606953765}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:14:37,389] Trial 10 finished with value: 0.06622946160237042 and parameters: {'sigma_noise': 0.21898474401516152, 'A_repulsion': 0.17034704368768558, 'gamma': 0.796963339874093, 'sigma_update': 0.30957622757853154}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:14:44,271] Trial 11 finished with value: 0.07027831080305548 and parameters: {'sigma_noise': 0.24713626664609778, 'A_repulsion': 0.31253888907657495, 'gamma': 0.7638637810631838, 'sigma_update': 0.4496044381860713}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:14:50,242] Trial 12 finished with value: 0.06428595242322842 and parameters: {'sigma_noise': 0.22864150540616335, 'A_repulsion': 0.19335595902383737, 'gamma': 0.7097140589251708, 'sigma_update': 0.2188509456170638}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:14:57,890] Trial 13 finished with value: 0.10182108836300678 and parameters: {'sigma_noise': 0.2884015911867297, 'A_repulsion': 0.3629064786311435, 'gamma': 0.2741173948025045, 'sigma_update': 0.4937663006168844}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:15:02,736] Trial 14 finished with value: 0.11749231923250943 and parameters: {'sigma_noise': 0.1674242971654028, 'A_repulsion': 0.01591558193919146, 'gamma': 0.6562189159774447, 'sigma_update': 0.06565361018864035}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:15:07,102] Trial 15 finished with value: 0.09424378457277151 and parameters: {'sigma_noise': 0.01814278691791399, 'A_repulsion': 0.24792358540936557, 'gamma': 0.8852994833648443, 'sigma_update': 0.4111651049537409}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:15:13,706] Trial 16 finished with value: 0.06866963854884935 and parameters: {'sigma_noise': 0.16644079331284875, 'A_repulsion': 0.4549155437711736, 'gamma': 0.6236058882198257, 'sigma_update': 0.2501119632750383}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:15:20,264] Trial 17 finished with value: 0.10093127554154868 and parameters: {'sigma_noise': 0.2724760731246218, 'A_repulsion': 0.21300687566769802, 'gamma': 0.23963633617785474, 'sigma_update': 0.5742536242747944}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:15:26,769] Trial 18 finished with value: 0.09079700168029839 and parameters: {'sigma_noise': 0.1981648130255134, 'A_repulsion': 0.3341107050117893, 'gamma': 0.3880673383422387, 'sigma_update': 0.11380632408082156}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:15:31,809] Trial 19 finished with value: 0.06618500045029187 and parameters: {'sigma_noise': 0.11529517118162691, 'A_repulsion': 0.13785668104033044, 'gamma': 0.863932047164816, 'sigma_update': 0.24995901065114007}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:15:39,512] Trial 20 finished with value: 0.13071122411758876 and parameters: {'sigma_noise': 0.35933724168112646, 'A_repulsion': 0.22896034298143336, 'gamma': 0.4733262425318877, 'sigma_update': 0.6921479157737931}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:15:46,021] Trial 21 finished with value: 0.06855295175543454 and parameters: {'sigma_noise': 0.24548532792501784, 'A_repulsion': 0.2655664501573127, 'gamma': 0.6781842125877088, 'sigma_update': 0.23754324620170503}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:15:52,436] Trial 22 finished with value: 0.09409728616144976 and parameters: {'sigma_noise': 0.29672934184569066, 'A_repulsion': 0.16543726619327465, 'gamma': 0.7318012887418315, 'sigma_update': 0.18778478328337916}. Best is trial 6 with value: 0.06147713749227457.
[I 2026-07-01 14:15:57,932] Trial 23 finished with value: 0.05726826970622302 and parameters: {'sigma_noise': 0.20768965468893902, 'A_repulsion': 0.12097276546748026, 'gamma': 0.5856047830509442, 'sigma_update': 0.34178689288402947}. Best is trial 23 with value: 0.05726826970622302.
[I 2026-07-01 14:16:03,274] Trial 24 finished with value: 0.06048135100082235 and parameters: {'sigma_noise': 0.1857699606228093, 'A_repulsion': 0.09773954207547669, 'gamma': 0.6149730935318395, 'sigma_update': 0.3761079092810461}. Best is trial 23 with value: 0.05726826970622302.
[I 2026-07-01 14:16:07,813] Trial 25 finished with value: 0.06222767477525065 and parameters: {'sigma_noise': 0.12508463685297527, 'A_repulsion': 0.0138023876135525, 'gamma': 0.5908911000043484, 'sigma_update': 0.3832163270998988}. Best is trial 23 with value: 0.05726826970622302.
[I 2026-07-01 14:16:13,093] Trial 26 finished with value: 0.059853302873074415 and parameters: {'sigma_noise': 0.19527859209501977, 'A_repulsion': 0.07338616814432342, 'gamma': 0.3145523901862684, 'sigma_update': 0.3057434927883997}. Best is trial 23 with value: 0.05726826970622302.
[I 2026-07-01 14:16:18,600] Trial 27 finished with value: 0.05861593340383623 and parameters: {'sigma_noise': 0.20293897172391875, 'A_repulsion': 0.08648829534428025, 'gamma': 0.31056226893872707, 'sigma_update': 0.3063732423785514}. Best is trial 23 with value: 0.05726826970622302.
[I 2026-07-01 14:16:23,465] Trial 28 finished with value: 0.059848158247169624 and parameters: {'sigma_noise': 0.14081858420034107, 'A_repulsion': 0.05699320945038021, 'gamma': 0.2527851841745533, 'sigma_update': 0.29898249280459716}. Best is trial 23 with value: 0.05726826970622302.
[I 2026-07-01 14:16:27,913] Trial 29 finished with value: 0.06008484766151537 and parameters: {'sigma_noise': 0.0881805945000714, 'A_repulsion': 0.059252196512184496, 'gamma': 0.03290350598494901, 'sigma_update': 0.2761695338684874}. Best is trial 23 with value: 0.05726826970622302.
[I 2026-07-01 14:16:32,674] Trial 30 finished with value: 0.06228015632856366 and parameters: {'sigma_noise': 0.1315582259122895, 'A_repulsion': 0.045329747049274144, 'gamma': 0.18708363476321327, 'sigma_update': 0.44415433339663746}. Best is trial 23 with value: 0.05726826970622302.
[I 2026-07-01 14:16:38,445] Trial 31 finished with value: 0.05981851405155833 and parameters: {'sigma_noise': 0.20644152845375804, 'A_repulsion': 0.12754011566788134, 'gamma': 0.31780803827558146, 'sigma_update': 0.31612219245343565}. Best is trial 23 with value: 0.05726826970622302.
[I 2026-07-01 14:16:44,441] Trial 32 finished with value: 0.05657090509515506 and parameters: {'sigma_noise': 0.21059207021465012, 'A_repulsion': 0.12616629340978758, 'gamma': 0.394058994712709, 'sigma_update': 0.3429963946043163}. Best is trial 32 with value: 0.05657090509515506.
[I 2026-07-01 14:16:50,128] Trial 33 finished with value: 0.05742846581600197 and parameters: {'sigma_noise': 0.21414363325381355, 'A_repulsion': 0.12754322652860206, 'gamma': 0.3891354522624305, 'sigma_update': 0.3464394281096841}. Best is trial 32 with value: 0.05657090509515506.
[I 2026-07-01 14:16:56,352] Trial 34 finished with value: 0.07910063257722716 and parameters: {'sigma_noise': 0.2690476655785396, 'A_repulsion': 0.12284063396018925, 'gamma': 0.39472195382861697, 'sigma_update': 0.3738195122850291}. Best is trial 32 with value: 0.05657090509515506.
[I 2026-07-01 14:17:02,055] Trial 35 finished with value: 0.06075174196851304 and parameters: {'sigma_noise': 0.22625450341841866, 'A_repulsion': 0.09660610197328824, 'gamma': 0.5490246269775566, 'sigma_update': 0.3428179726464388}. Best is trial 32 with value: 0.05657090509515506.
[I 2026-07-01 14:17:07,217] Trial 36 finished with value: 0.06081952044167832 and parameters: {'sigma_noise': 0.1547286586733174, 'A_repulsion': 0.12376409699661944, 'gamma': 0.41181868427797447, 'sigma_update': 0.5140628478963435}. Best is trial 32 with value: 0.05657090509515506.
[I 2026-07-01 14:17:13,938] Trial 37 finished with value: 0.09538033926829712 and parameters: {'sigma_noise': 0.31685706776439937, 'A_repulsion': 0.16906362000359948, 'gamma': 0.363387457536939, 'sigma_update': 0.42028584645705114}. Best is trial 32 with value: 0.05657090509515506.
[I 2026-07-01 14:17:18,643] Trial 38 finished with value: 0.07614681845667158 and parameters: {'sigma_noise': 0.08206254639785726, 'A_repulsion': 0.042837745684784684, 'gamma': 0.481357103261334, 'sigma_update': 0.14088635779353378}. Best is trial 32 with value: 0.05657090509515506.
[I 2026-07-01 14:17:24,540] Trial 39 finished with value: 0.08203367907346708 and parameters: {'sigma_noise': 0.2625856686552751, 'A_repulsion': 0.08970508783020546, 'gamma': 0.16259183801139293, 'sigma_update': 0.35755839283499163}. Best is trial 32 with value: 0.05657090509515506.
[I 2026-07-01 14:17:29,313] Trial 40 finished with value: 0.06107662727976277 and parameters: {'sigma_noise': 0.10025366655965941, 'A_repulsion': 0.13370172542365652, 'gamma': 0.4413718290405315, 'sigma_update': 0.5181416078331932}. Best is trial 32 with value: 0.05657090509515506.
[I 2026-07-01 14:17:35,033] Trial 41 finished with value: 0.06173959487745526 and parameters: {'sigma_noise': 0.20372751658827254, 'A_repulsion': 0.13712599915630125, 'gamma': 0.3167401661864064, 'sigma_update': 0.28813296180771053}. Best is trial 32 with value: 0.05657090509515506.
[I 2026-07-01 14:17:40,881] Trial 42 finished with value: 0.05952426653102752 and parameters: {'sigma_noise': 0.20722587186629193, 'A_repulsion': 0.15742831986584305, 'gamma': 0.3210971760999403, 'sigma_update': 0.33795182064212603}. Best is trial 32 with value: 0.05657090509515506.
[I 2026-07-01 14:17:46,579] Trial 43 finished with value: 0.06261957819698057 and parameters: {'sigma_noise': 0.17990326470668036, 'A_repulsion': 0.19218872954974198, 'gamma': 0.23367126266405627, 'sigma_update': 0.40412924813098383}. Best is trial 32 with value: 0.05657090509515506.
[I 2026-07-01 14:17:52,298] Trial 44 finished with value: 0.05975690828483028 and parameters: {'sigma_noise': 0.2141687146857212, 'A_repulsion': 0.15450500356371488, 'gamma': 0.5418010322755378, 'sigma_update': 0.3428848932611296}. Best is trial 32 with value: 0.05657090509515506.
[I 2026-07-01 14:17:57,390] Trial 45 finished with value: 0.05517684770701315 and parameters: {'sigma_noise': 0.15583315338091377, 'A_repulsion': 0.11156370252537622, 'gamma': 0.12115149286304144, 'sigma_update': 0.26875971856042347}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:18:02,514] Trial 46 finished with value: 0.06261268681504273 and parameters: {'sigma_noise': 0.15029355613393847, 'A_repulsion': 0.11058966096448213, 'gamma': 0.07382126660478744, 'sigma_update': 0.2070438589324655}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:18:07,726] Trial 47 finished with value: 0.07732386075038905 and parameters: {'sigma_noise': 0.23894683924394422, 'A_repulsion': 0.00147286884238218, 'gamma': 0.11884071793276618, 'sigma_update': 0.26333208632297733}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:18:13,009] Trial 48 finished with value: 0.06627423601443916 and parameters: {'sigma_noise': 0.17322217937081075, 'A_repulsion': 0.07602129244649003, 'gamma': 0.19868851803692594, 'sigma_update': 0.4564634084806405}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:18:18,479] Trial 49 finished with value: 0.07369218928707888 and parameters: {'sigma_noise': 0.2592041328129232, 'A_repulsion': 0.032967166422479224, 'gamma': 0.441616172365074, 'sigma_update': 0.21790116792086162}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:18:23,084] Trial 50 finished with value: 0.06223699061794959 and parameters: {'sigma_noise': 0.06492711368658688, 'A_repulsion': 0.19334220076316294, 'gamma': 0.49932070043610033, 'sigma_update': 0.2782097302416964}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:18:28,868] Trial 51 finished with value: 0.05764380079840126 and parameters: {'sigma_noise': 0.21724665701470516, 'A_repulsion': 0.15039397344824806, 'gamma': 0.3553926767241249, 'sigma_update': 0.33021682254694174}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:18:34,495] Trial 52 finished with value: 0.05953681493654031 and parameters: {'sigma_noise': 0.22705959187060357, 'A_repulsion': 0.1089577630873412, 'gamma': 0.36220437685327955, 'sigma_update': 0.32478948059714335}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:18:39,715] Trial 53 finished with value: 0.06439602456052311 and parameters: {'sigma_noise': 0.18816495308573356, 'A_repulsion': 0.07897649654494093, 'gamma': 0.26839276034249715, 'sigma_update': 0.3962011115787493}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:18:46,074] Trial 54 finished with value: 0.09017062493822384 and parameters: {'sigma_noise': 0.2918174211105201, 'A_repulsion': 0.1485573377019312, 'gamma': 0.4172012042287047, 'sigma_update': 0.4258719730191658}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:18:51,829] Trial 55 finished with value: 0.05729151988901659 and parameters: {'sigma_noise': 0.16265142584621756, 'A_repulsion': 0.21272093098382042, 'gamma': 0.5181967720431933, 'sigma_update': 0.23870216971632932}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:18:57,325] Trial 56 finished with value: 0.06328044893237174 and parameters: {'sigma_noise': 0.1517848776114162, 'A_repulsion': 0.2152657184266339, 'gamma': 0.5159836758741781, 'sigma_update': 0.16213167965563688}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:19:02,780] Trial 57 finished with value: 0.059864976017456696 and parameters: {'sigma_noise': 0.16960712709532888, 'A_repulsion': 0.1832170046772288, 'gamma': 0.5729262581439165, 'sigma_update': 0.23668941430785423}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:19:07,918] Trial 58 finished with value: 0.06483510273035793 and parameters: {'sigma_noise': 0.11111732163185803, 'A_repulsion': 0.21555748061819413, 'gamma': 0.6514335798252486, 'sigma_update': 0.3619743115797065}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:19:13,986] Trial 59 finished with value: 0.0983822615174762 and parameters: {'sigma_noise': 0.23868945007239403, 'A_repulsion': 0.17716580563464404, 'gamma': 0.4721399563786417, 'sigma_update': 0.11022633469327703}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:19:20,144] Trial 60 finished with value: 0.06026859068063771 and parameters: {'sigma_noise': 0.2205422676106982, 'A_repulsion': 0.2383812315249912, 'gamma': 0.6096307994871034, 'sigma_update': 0.19875183919980288}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:19:26,200] Trial 61 finished with value: 0.05986869284252753 and parameters: {'sigma_noise': 0.19052930004957214, 'A_repulsion': 0.2718042885465109, 'gamma': 0.3703969041067783, 'sigma_update': 0.3014514794445039}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:19:31,304] Trial 62 finished with value: 0.057398988990956294 and parameters: {'sigma_noise': 0.1336331296735499, 'A_repulsion': 0.1144661136158013, 'gamma': 0.010335227280767773, 'sigma_update': 0.25535405038039605}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:19:36,436] Trial 63 finished with value: 0.05770465917494552 and parameters: {'sigma_noise': 0.13119846164470803, 'A_repulsion': 0.14642780411131126, 'gamma': 0.021167973914832335, 'sigma_update': 0.2613811374725691}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:19:41,681] Trial 64 finished with value: 0.0569690730548882 and parameters: {'sigma_noise': 0.1615126011213037, 'A_repulsion': 0.10865474375555947, 'gamma': 0.11617698150653878, 'sigma_update': 0.23594096892106203}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:19:46,814] Trial 65 finished with value: 0.06541770211370274 and parameters: {'sigma_noise': 0.16115305238470207, 'A_repulsion': 0.11784579236187012, 'gamma': 0.11518018047121797, 'sigma_update': 0.18516913716573355}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:19:51,637] Trial 66 finished with value: 0.05847530969708644 and parameters: {'sigma_noise': 0.14135711946410187, 'A_repulsion': 0.07241442586804217, 'gamma': 0.07516127246837245, 'sigma_update': 0.23501839922416484}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:19:55,792] Trial 67 finished with value: 0.0839110285127873 and parameters: {'sigma_noise': 0.04052368394694336, 'A_repulsion': 0.10747249138880656, 'gamma': 0.015437760842207918, 'sigma_update': 0.14018168565855488}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:20:00,510] Trial 68 finished with value: 0.0606697415687423 and parameters: {'sigma_noise': 0.11675217989164745, 'A_repulsion': 0.06209359120624545, 'gamma': 0.1329680828922178, 'sigma_update': 0.2761508067214488}. Best is trial 45 with value: 0.05517684770701315.
[I 2026-07-01 14:20:05,406] Trial 69 finished with value: 0.056238397002631745 and parameters: {'sigma_noise': 0.14285605481157823, 'A_repulsion': 0.09385154819363199, 'gamma': 0.05204330300100321, 'sigma_update': 0.230130716959957}. Best is trial 45 with value: 0.05517684770701315.

--- Repetition 1/1, Fold 2/2 ---

[I 2026-07-01 14:30:33,829] Trial 0 finished with value: 0.1096319463611117 and parameters: {'sigma_noise': 0.23130453864636627, 'A_repulsion': 0.18301128532134425, 'gamma': 0.452841141347309, 'sigma_update': 0.25970184790431533}. Best is trial 0 with value: 0.1096319463611117.
[I 2026-07-01 14:30:42,457] Trial 1 finished with value: 0.27795045084091435 and parameters: {'sigma_noise': 0.2896830130226404, 'A_repulsion': 0.26985879734803747, 'gamma': 0.35513063031140035, 'sigma_update': 0.021304754046750203}. Best is trial 0 with value: 0.1096319463611117.
[I 2026-07-01 14:30:47,812] Trial 2 finished with value: 0.06978685756124257 and parameters: {'sigma_noise': 0.2482563016050371, 'A_repulsion': 0.01307051444869517, 'gamma': 0.10747910049641866, 'sigma_update': 0.5943023551651709}. Best is trial 2 with value: 0.06978685756124257.
[I 2026-07-01 14:30:59,577] Trial 3 finished with value: 0.2784561825997613 and parameters: {'sigma_noise': 0.37527668163972994, 'A_repulsion': 0.4418781743877959, 'gamma': 0.5936713489700887, 'sigma_update': 0.03125094671816984}. Best is trial 2 with value: 0.06978685756124257.
[I 2026-07-01 14:31:05,576] Trial 4 finished with value: 0.12168795728743742 and parameters: {'sigma_noise': 0.27004342949694843, 'A_repulsion': 0.09121359324192646, 'gamma': 0.6310765168478065, 'sigma_update': 0.14599614024581373}. Best is trial 2 with value: 0.06978685756124257.
[I 2026-07-01 14:31:11,896] Trial 5 finished with value: 0.12343315100857745 and parameters: {'sigma_noise': 0.12337161534144786, 'A_repulsion': 0.49109469278048695, 'gamma': 0.40356036120579797, 'sigma_update': 0.3861271244037694}. Best is trial 2 with value: 0.06978685756124257.
[I 2026-07-01 14:31:17,282] Trial 6 finished with value: 0.17702828332696074 and parameters: {'sigma_noise': 0.07510717462073618, 'A_repulsion': 0.33132735380182404, 'gamma': 0.9473826639588159, 'sigma_update': 0.4300498329286726}. Best is trial 2 with value: 0.06978685756124257.
[I 2026-07-01 14:31:24,319] Trial 7 finished with value: 0.15336456200610257 and parameters: {'sigma_noise': 0.4113685825474536, 'A_repulsion': 0.026287693760968123, 'gamma': 0.9423902250678173, 'sigma_update': 0.07200514621890475}. Best is trial 2 with value: 0.06978685756124257.
[I 2026-07-01 14:31:33,478] Trial 8 finished with value: 0.14213897935184336 and parameters: {'sigma_noise': 0.40233977013419053, 'A_repulsion': 0.38998526586764987, 'gamma': 0.2727413780278623, 'sigma_update': 0.24873704790160447}. Best is trial 2 with value: 0.06978685756124257.
[I 2026-07-01 14:31:39,103] Trial 9 finished with value: 0.07977655567491315 and parameters: {'sigma_noise': 0.22035871008742997, 'A_repulsion': 0.09071487962925551, 'gamma': 0.09370343702572312, 'sigma_update': 0.4187893561030623}. Best is trial 2 with value: 0.06978685756124257.
[I 2026-07-01 14:31:43,921] Trial 10 finished with value: 0.06759744918578546 and parameters: {'sigma_noise': 0.1633272895373476, 'A_repulsion': 0.0012154227291707453, 'gamma': 0.14854906742184681, 'sigma_update': 0.6810835167770299}. Best is trial 10 with value: 0.06759744918578546.
[I 2026-07-01 14:31:48,790] Trial 11 finished with value: 0.057782680935834205 and parameters: {'sigma_noise': 0.1670125070332722, 'A_repulsion': 0.0009002239173387938, 'gamma': 0.019160224821420435, 'sigma_update': 0.686030377609842}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:31:54,079] Trial 12 finished with value: 0.06906087367033281 and parameters: {'sigma_noise': 0.14530094414495298, 'A_repulsion': 0.15942555168444555, 'gamma': 0.012137938340453621, 'sigma_update': 0.6867636382071782}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:31:58,038] Trial 13 finished with value: 0.10950178761188648 and parameters: {'sigma_noise': 0.03241516845456971, 'A_repulsion': 0.0012780038504112763, 'gamma': 0.23908835836708187, 'sigma_update': 0.5820585341207991}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:32:03,235] Trial 14 finished with value: 0.06577834283446252 and parameters: {'sigma_noise': 0.1472241855528878, 'A_repulsion': 0.12483423198072961, 'gamma': 0.18500435430457912, 'sigma_update': 0.6701720121261976}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:32:08,188] Trial 15 finished with value: 0.07816105121398753 and parameters: {'sigma_noise': 0.09236739366284921, 'A_repulsion': 0.109961735343817, 'gamma': 0.016675257202362903, 'sigma_update': 0.5526585796506922}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:32:13,975] Trial 16 finished with value: 0.07858910232807732 and parameters: {'sigma_noise': 0.18482988998656377, 'A_repulsion': 0.21231649508677392, 'gamma': 0.2486563867201857, 'sigma_update': 0.5127568216006032}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:32:20,590] Trial 17 finished with value: 0.11098865080975075 and parameters: {'sigma_noise': 0.3300698547609178, 'A_repulsion': 0.1293136737174957, 'gamma': 0.7818305649435049, 'sigma_update': 0.6404020711468295}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:32:24,552] Trial 18 finished with value: 0.09851555407446436 and parameters: {'sigma_noise': 0.02125949222231155, 'A_repulsion': 0.0688669258437741, 'gamma': 0.1802893047472873, 'sigma_update': 0.4917261980289113}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:32:30,576] Trial 19 finished with value: 0.10966358425349754 and parameters: {'sigma_noise': 0.1821469650657464, 'A_repulsion': 0.23913840170016232, 'gamma': 0.31107511967212786, 'sigma_update': 0.30978729468886895}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:32:35,261] Trial 20 finished with value: 0.11980865249549846 and parameters: {'sigma_noise': 0.09953035091198766, 'A_repulsion': 0.057505807025735406, 'gamma': 0.5422403554655646, 'sigma_update': 0.6372492700373732}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:32:40,123] Trial 21 finished with value: 0.06194334301332945 and parameters: {'sigma_noise': 0.1672575648001244, 'A_repulsion': 0.03978578477983746, 'gamma': 0.13214862954937567, 'sigma_update': 0.6760864587824882}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:32:45,697] Trial 22 finished with value: 0.07372259789731195 and parameters: {'sigma_noise': 0.20189078002913502, 'A_repulsion': 0.135333591808165, 'gamma': 0.07922392239558686, 'sigma_update': 0.6949211054864909}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:32:50,396] Trial 23 finished with value: 0.06789447643479087 and parameters: {'sigma_noise': 0.13955576382652893, 'A_repulsion': 0.04995616182702123, 'gamma': 0.2066980663527986, 'sigma_update': 0.5053523071286087}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:32:54,568] Trial 24 finished with value: 0.09121773541318282 and parameters: {'sigma_noise': 0.0642947510922578, 'A_repulsion': 0.04793466520626258, 'gamma': 0.13449027151003354, 'sigma_update': 0.6205448131457776}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:32:59,772] Trial 25 finished with value: 0.07335053058138401 and parameters: {'sigma_noise': 0.12122556719330504, 'A_repulsion': 0.17787466471958668, 'gamma': 0.023648721239411696, 'sigma_update': 0.5468223860976333}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:33:05,995] Trial 26 finished with value: 0.08956672842320788 and parameters: {'sigma_noise': 0.3097455835380666, 'A_repulsion': 0.09013528908183695, 'gamma': 0.3389117927804226, 'sigma_update': 0.6421305175424504}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:33:12,061] Trial 27 finished with value: 0.08689633163845956 and parameters: {'sigma_noise': 0.16854090179981263, 'A_repulsion': 0.279391361699477, 'gamma': 0.17228602969881704, 'sigma_update': 0.47582666068631146}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:33:17,735] Trial 28 finished with value: 0.11760642530741323 and parameters: {'sigma_noise': 0.2049797433576537, 'A_repulsion': 0.14727839124876113, 'gamma': 0.6967663868096801, 'sigma_update': 0.5847517963062988}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:33:24,026] Trial 29 finished with value: 0.11289639784289275 and parameters: {'sigma_noise': 0.22950918384686164, 'A_repulsion': 0.20799606816678953, 'gamma': 0.4817566709052783, 'sigma_update': 0.2491346973787989}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:33:29,450] Trial 30 finished with value: 0.06484134810781879 and parameters: {'sigma_noise': 0.2520842524761483, 'A_repulsion': 0.04040384023919724, 'gamma': 0.3961386194580214, 'sigma_update': 0.6654475840403188}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:33:34,966] Trial 31 finished with value: 0.06985699213851641 and parameters: {'sigma_noise': 0.257453809306667, 'A_repulsion': 0.03214433472277134, 'gamma': 0.4045294852010759, 'sigma_update': 0.6948065098228291}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:33:40,018] Trial 32 finished with value: 0.06354421311827192 and parameters: {'sigma_noise': 0.15279593293099158, 'A_repulsion': 0.07026705291408514, 'gamma': 0.07884740699115383, 'sigma_update': 0.646941979049878}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:33:45,819] Trial 33 finished with value: 0.08797530155481399 and parameters: {'sigma_noise': 0.2819144299831441, 'A_repulsion': 0.06335778604727567, 'gamma': 0.09497304488692211, 'sigma_update': 0.6175695920244616}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:33:51,282] Trial 34 finished with value: 0.06706894856002775 and parameters: {'sigma_noise': 0.24144000200475813, 'A_repulsion': 0.026975299979907247, 'gamma': 0.419406140837059, 'sigma_update': 0.5680771645150348}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:33:57,632] Trial 35 finished with value: 0.11876504302345667 and parameters: {'sigma_noise': 0.31874785773196945, 'A_repulsion': 0.10234226777608553, 'gamma': 0.06669261020985184, 'sigma_update': 0.6530941969140149}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:34:03,702] Trial 36 finished with value: 0.09945112106566316 and parameters: {'sigma_noise': 0.35030941666070925, 'A_repulsion': 1.3674359520555665e-05, 'gamma': 0.2949251300320105, 'sigma_update': 0.5941044146060656}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:34:09,367] Trial 37 finished with value: 0.10790267036335513 and parameters: {'sigma_noise': 0.20771936826423607, 'A_repulsion': 0.08256163801127113, 'gamma': 0.5327963293046311, 'sigma_update': 0.2064208784313653}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:34:13,860] Trial 38 finished with value: 0.07506644598723121 and parameters: {'sigma_noise': 0.11756873606965892, 'A_repulsion': 0.034282494969538405, 'gamma': 0.06092018367846397, 'sigma_update': 0.5337142018070955}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:34:19,908] Trial 39 finished with value: 0.0943183970445596 and parameters: {'sigma_noise': 0.18304497335963804, 'A_repulsion': 0.2776917040953726, 'gamma': 0.12655306710462877, 'sigma_update': 0.35425684240566413}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:34:27,348] Trial 40 finished with value: 0.10955618986999273 and parameters: {'sigma_noise': 0.25313434642822713, 'A_repulsion': 0.37299938406182254, 'gamma': 0.6638537643197648, 'sigma_update': 0.6165170927019595}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:34:34,477] Trial 41 finished with value: 0.18359750308778225 and parameters: {'sigma_noise': 0.4493276154811531, 'A_repulsion': 0.06804492863675854, 'gamma': 0.18906907513189286, 'sigma_update': 0.659281229464468}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:34:39,617] Trial 42 finished with value: 0.06923147293436388 and parameters: {'sigma_noise': 0.15218267557596793, 'A_repulsion': 0.12267099883069113, 'gamma': 0.22969889931582083, 'sigma_update': 0.6657158439306115}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:34:44,378] Trial 43 finished with value: 0.08073982629132968 and parameters: {'sigma_noise': 0.13412238303398813, 'A_repulsion': 0.02220507398256388, 'gamma': 0.36733846914072055, 'sigma_update': 0.6995579382123875}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:34:49,431] Trial 44 finished with value: 0.07453878603456225 and parameters: {'sigma_noise': 0.16543997071045746, 'A_repulsion': 0.04356645222835337, 'gamma': 0.12392872484909837, 'sigma_update': 0.4478348587933574}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:34:54,256] Trial 45 finished with value: 0.07406578574417598 and parameters: {'sigma_noise': 0.1023400884293128, 'A_repulsion': 0.1680060675282648, 'gamma': 0.03966492923076195, 'sigma_update': 0.606730565325017}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:34:58,567] Trial 46 finished with value: 0.11718458078285046 and parameters: {'sigma_noise': 0.05831454096295215, 'A_repulsion': 0.07536709968274455, 'gamma': 0.15798169532793963, 'sigma_update': 0.08454472575061306}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:35:04,266] Trial 47 finished with value: 0.07192376077686463 and parameters: {'sigma_noise': 0.2225821456795722, 'A_repulsion': 0.11036285348822517, 'gamma': 0.2773989127554541, 'sigma_update': 0.6677034104491444}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:35:09,769] Trial 48 finished with value: 0.11027015952287006 and parameters: {'sigma_noise': 0.2768794377025555, 'A_repulsion': 0.019854381394481646, 'gamma': 0.8695554368721976, 'sigma_update': 0.5898223458976166}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:35:15,149] Trial 49 finished with value: 0.06807814880526387 and parameters: {'sigma_noise': 0.19066562047507946, 'A_repulsion': 0.09913832036987463, 'gamma': 0.09559236330189255, 'sigma_update': 0.5368484208210784}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:35:21,087] Trial 50 finished with value: 0.0899102557398007 and parameters: {'sigma_noise': 0.08313840039193575, 'A_repulsion': 0.4670826600552419, 'gamma': 0.23379684295626377, 'sigma_update': 0.6696209728569262}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:35:26,600] Trial 51 finished with value: 0.06816933574105893 and parameters: {'sigma_noise': 0.24953999393433268, 'A_repulsion': 0.02194692464767644, 'gamma': 0.43449819906118814, 'sigma_update': 0.5641615927849446}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:35:32,485] Trial 52 finished with value: 0.08483954734855008 and parameters: {'sigma_noise': 0.29696044344613554, 'A_repulsion': 0.04346853661392753, 'gamma': 0.3605506117463424, 'sigma_update': 0.6400581163192943}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:35:37,677] Trial 53 finished with value: 0.07500645567589408 and parameters: {'sigma_noise': 0.23288012679389164, 'A_repulsion': 6.445578906069454e-05, 'gamma': 0.46494942122355065, 'sigma_update': 0.5770918407714337}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:35:42,646] Trial 54 finished with value: 0.08447532601018923 and parameters: {'sigma_noise': 0.15548043713515314, 'A_repulsion': 0.05749782045745776, 'gamma': 0.41954566792178155, 'sigma_update': 0.6328911090454652}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:35:47,278] Trial 55 finished with value: 0.11844119231370626 and parameters: {'sigma_noise': 0.11412984680553363, 'A_repulsion': 0.0813849145620914, 'gamma': 0.5553736414045005, 'sigma_update': 0.6783311595681771}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:35:51,814] Trial 56 finished with value: 0.11268296610571121 and parameters: {'sigma_noise': 0.1345432603759122, 'A_repulsion': 0.01567923947517719, 'gamma': 0.5961395955062616, 'sigma_update': 0.6985021962053924}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:35:57,026] Trial 57 finished with value: 0.06010147189876357 and parameters: {'sigma_noise': 0.172312042014258, 'A_repulsion': 0.11373104898228856, 'gamma': 0.05897063665272524, 'sigma_update': 0.6154318838452497}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:36:02,576] Trial 58 finished with value: 0.06429405439348534 and parameters: {'sigma_noise': 0.17918896601856385, 'A_repulsion': 0.14960344249745902, 'gamma': 0.04975675852455675, 'sigma_update': 0.604160907141621}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:36:08,208] Trial 59 finished with value: 0.06572777284164613 and parameters: {'sigma_noise': 0.17047541478622963, 'A_repulsion': 0.20008330357888787, 'gamma': 0.01616321334067044, 'sigma_update': 0.6067396571541089}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:36:13,800] Trial 60 finished with value: 0.07828660829383584 and parameters: {'sigma_noise': 0.20219141451285638, 'A_repulsion': 0.11532985504649712, 'gamma': 0.051244974045513314, 'sigma_update': 0.46605311471649125}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:36:19,408] Trial 61 finished with value: 0.06509884172163538 and parameters: {'sigma_noise': 0.17447838115650563, 'A_repulsion': 0.1976151326790018, 'gamma': 0.04078800945599134, 'sigma_update': 0.6266386892544931}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:36:25,113] Trial 62 finished with value: 0.0648512815976763 and parameters: {'sigma_noise': 0.17781200828870675, 'A_repulsion': 0.18761824693529427, 'gamma': 0.08073993549459052, 'sigma_update': 0.6476127873393046}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:36:31,124] Trial 63 finished with value: 0.0720812248771037 and parameters: {'sigma_noise': 0.2160217539302612, 'A_repulsion': 0.1613174527205682, 'gamma': 0.10630756214892563, 'sigma_update': 0.6578061403139333}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:36:36,950] Trial 64 finished with value: 0.06417170738238728 and parameters: {'sigma_noise': 0.19561557142937366, 'A_repulsion': 0.13878955049726316, 'gamma': 0.07437192768454325, 'sigma_update': 0.6412360833673253}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:36:43,044] Trial 65 finished with value: 0.06660592866867213 and parameters: {'sigma_noise': 0.19755491331256067, 'A_repulsion': 0.1475350316012597, 'gamma': 0.14411524888627164, 'sigma_update': 0.6041230926063562}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:36:48,606] Trial 66 finished with value: 0.07731188211824667 and parameters: {'sigma_noise': 0.1544600297110315, 'A_repulsion': 0.22557952640368, 'gamma': 0.011654449285953522, 'sigma_update': 0.5205016845456425}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:36:54,802] Trial 67 finished with value: 0.06792346326888411 and parameters: {'sigma_noise': 0.2612206477474289, 'A_repulsion': 0.14372068562634188, 'gamma': 0.20141271002795158, 'sigma_update': 0.5560754745743843}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:37:00,174] Trial 68 finished with value: 0.0675914372553213 and parameters: {'sigma_noise': 0.21553809300580085, 'A_repulsion': 0.05942865288539341, 'gamma': 0.07601539365377077, 'sigma_update': 0.6300370393896604}. Best is trial 11 with value: 0.057782680935834205.
[I 2026-07-01 14:37:06,310] Trial 69 finished with value: 0.0928600675746066 and parameters: {'sigma_noise': 0.19025395380067417, 'A_repulsion': 0.25626700321297263, 'gamma': 0.13598113005506104, 'sigma_update': 0.39666936099852934}. Best is trial 11 with value: 0.057782680935834205.

  ✔ Results saved to D:\sc_modelling-amir-2025\Final-Hybrid - Copy\human_test.pkl
  ✔ Completed human subject 6266630.0
run_pid_repeated_cv executed in 6326.06 seconds.

Finished in 105.43 minutes

In [ ]:
import time

import binned_Hybrid_hpc_utils as hpc

start = time.time()

save_path = r"D:\sc_modelling-amir-2025\Final-Hybrid - Copy\rat_test.pkl"

hpc.run_pid_repeated_cv(
    species="rat",
    p_id="EM57",
    save_path=save_path,
    model_mode="all",
    repetition_seeds=[1],      # only one repetition
    cv_folds=2,
    optuna_trials=200,          # increase later
    sampler_type="TPE",
    model_seed_count=5,
    fit_with="conditional",
)

elapsed = time.time() - start

print(f"\nFinished in {elapsed/60:.2f} minutes")

  ✱ Running repeated CV
  ✱ Species: rat
  ✱ Subject: EM57
  ✱ ID column: Participant_ID
  ✱ Data path: D:\sc_modelling-amir-2025\Final-Hybrid - Copy\Data_rat_first_dists_V2.pkl
  ✱ Model mode: all
  ✱ Custom alpha: None
  ✱ Repetitions: 1
  ✱ Folds: 2
  ✱ Model seeds per objective: 5
  ✱ Sampler: TPE

==============================
Running variant: Hybrid
==============================

--- Repetition 1/1, Fold 1/2 ---

[I 2026-07-01 14:49:20,516] A new study created in memory with name: no-name-cc434b16-171f-46b6-b281-7e78129f0784
[I 2026-07-01 14:50:14,847] Trial 0 finished with value: 0.028881883634828534 and parameters: {'sigma_noise': 0.08159018215585934, 'A_repulsion': 0.37739043882567497, 'gamma': 0.5677678301612995, 'sigma_update': 0.1654324459144433, 'eta_learning': 0.3478491667769279, 'sigma_boundary': 1.5333873569415812, 'alpha': 0.345191215678889}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 14:50:56,305] Trial 1 finished with value: 0.07611672677976596 and parameters: {'sigma_noise': 0.028336949347424388, 'A_repulsion': 0.12397018705459617, 'gamma': 0.6037750794814256, 'sigma_update': 0.6799702871422885, 'eta_learning': 0.7050432940906743, 'sigma_boundary': 7.202289814735496, 'alpha': 0.19761819488501076}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 14:51:53,381] Trial 2 finished with value: 0.054873921135624414 and parameters: {'sigma_noise': 0.22815268076549577, 'A_repulsion': 0.1046962058534483, 'gamma': 0.7917811153454742, 'sigma_update': 0.5746881351261827, 'eta_learning': 0.1411806041584652, 'sigma_boundary': 9.26022671518514, 'alpha': 0.08947189610755679}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 14:52:48,242] Trial 3 finished with value: 0.15618353378379873 and parameters: {'sigma_noise': 0.2516999224057834, 'A_repulsion': 0.04084198586307114, 'gamma': 0.4658883805769573, 'sigma_update': 0.2756597839299866, 'eta_learning': 0.49378053512424686, 'sigma_boundary': 4.744469558215844, 'alpha': 0.257971795822834}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 14:54:12,045] Trial 4 finished with value: 0.3662083012119572 and parameters: {'sigma_noise': 0.4481755238991748, 'A_repulsion': 0.19224766240446378, 'gamma': 0.43624790131316343, 'sigma_update': 0.6423761148454564, 'eta_learning': 0.9338473375652437, 'sigma_boundary': 9.653829981404058, 'alpha': 0.525249444507877}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 14:55:35,935] Trial 5 finished with value: 0.11350629465349993 and parameters: {'sigma_noise': 0.4050965726517538, 'A_repulsion': 0.26532002031065316, 'gamma': 0.6065164114808138, 'sigma_update': 0.500551795517497, 'eta_learning': 0.987103256649888, 'sigma_boundary': 3.2799866449045885, 'alpha': 0.687529946679019}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 14:56:43,157] Trial 6 finished with value: 0.20939910295238193 and parameters: {'sigma_noise': 0.42173929991324877, 'A_repulsion': 0.023514835890982133, 'gamma': 0.5494841403141102, 'sigma_update': 0.4917535135354017, 'eta_learning': 0.27920015081441985, 'sigma_boundary': 9.003956920436321, 'alpha': 0.36037129049980776}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 14:58:24,827] Trial 7 finished with value: 0.9942907024833889 and parameters: {'sigma_noise': 0.42376319489670955, 'A_repulsion': 0.3092428567289799, 'gamma': 0.6778687560321413, 'sigma_update': 0.07130466643065073, 'eta_learning': 0.7209749537503536, 'sigma_boundary': 3.578790752804061, 'alpha': 0.11191690083480477}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 14:59:33,825] Trial 8 finished with value: 0.571569587322962 and parameters: {'sigma_noise': 0.20186791869273799, 'A_repulsion': 0.39794259559465356, 'gamma': 0.5406199369766412, 'sigma_update': 0.17976240876083485, 'eta_learning': 0.37051916155011705, 'sigma_boundary': 3.866546295171387, 'alpha': 0.16032124420670557}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:00:23,376] Trial 9 finished with value: 0.049336326672028384 and parameters: {'sigma_noise': 0.16703620082455636, 'A_repulsion': 0.02931866830892288, 'gamma': 0.47560716888588833, 'sigma_update': 0.43722608827933773, 'eta_learning': 0.18190352970063134, 'sigma_boundary': 3.7508561719845708, 'alpha': 0.06605731391294933}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:01:24,067] Trial 10 finished with value: 0.32109178199180094 and parameters: {'sigma_noise': 0.03223326075523472, 'A_repulsion': 0.49038804501782346, 'gamma': 0.09718053935174914, 'sigma_update': 0.01241565455974733, 'eta_learning': 0.01549888678143968, 'sigma_boundary': 0.4347391136355234, 'alpha': 0.9402551641653798}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:02:23,831] Trial 11 finished with value: 0.04131667475797873 and parameters: {'sigma_noise': 0.12848548552321948, 'A_repulsion': 0.36711328319377234, 'gamma': 0.24150066169402917, 'sigma_update': 0.34929463129443017, 'eta_learning': 0.27000478650794696, 'sigma_boundary': 1.0219881140315104, 'alpha': 0.419423763977641}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:03:20,960] Trial 12 finished with value: 0.044407189338864644 and parameters: {'sigma_noise': 0.11201849213868986, 'A_repulsion': 0.37147102247597014, 'gamma': 0.2023106556901177, 'sigma_update': 0.3081843881069266, 'eta_learning': 0.4652669428227667, 'sigma_boundary': 0.6157011537654375, 'alpha': 0.4826594094809439}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:04:23,302] Trial 13 finished with value: 0.06122148470336269 and parameters: {'sigma_noise': 0.11421200713642483, 'A_repulsion': 0.48578895693904284, 'gamma': 0.9988511996213604, 'sigma_update': 0.18148070320882287, 'eta_learning': 0.3195937722689767, 'sigma_boundary': 1.686690455771476, 'alpha': 0.5850123380777705}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:05:18,769] Trial 14 finished with value: 0.07428004870420227 and parameters: {'sigma_noise': 0.09851872350399088, 'A_repulsion': 0.36792382989905825, 'gamma': 0.2915873231278914, 'sigma_update': 0.37543561226606104, 'eta_learning': 0.5659951095412146, 'sigma_boundary': 1.947795510558461, 'alpha': 0.36056425415118176}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:06:41,861] Trial 15 finished with value: 0.04985985721484894 and parameters: {'sigma_noise': 0.28596835789250447, 'A_repulsion': 0.4357875748393728, 'gamma': 0.3142492813883595, 'sigma_update': 0.20252886488190316, 'eta_learning': 0.18724139779039037, 'sigma_boundary': 5.947507566719847, 'alpha': 0.7696313024700112}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:07:59,138] Trial 16 finished with value: 0.035830489560916126 and parameters: {'sigma_noise': 0.3187772905814066, 'A_repulsion': 0.3079736427057119, 'gamma': 0.05633894562759109, 'sigma_update': 0.2545117575513075, 'eta_learning': 0.06668444095354234, 'sigma_boundary': 1.8658099042871155, 'alpha': 0.38380359874361514}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:09:24,388] Trial 17 finished with value: 0.03204272219219751 and parameters: {'sigma_noise': 0.34180733854744844, 'A_repulsion': 0.2947961690512748, 'gamma': 0.032013823141453235, 'sigma_update': 0.09801617877934254, 'eta_learning': 0.015114958657066857, 'sigma_boundary': 2.3463369857205674, 'alpha': 0.26046257863170713}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:10:39,549] Trial 18 finished with value: 0.9841075136576245 and parameters: {'sigma_noise': 0.32506905887262316, 'A_repulsion': 0.21703561369640456, 'gamma': 0.7432349858390176, 'sigma_update': 0.10761050388482954, 'eta_learning': 0.6363029810205708, 'sigma_boundary': 2.4983958913063153, 'alpha': 0.003573697519395458}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:12:04,109] Trial 19 finished with value: 0.8276489613776878 and parameters: {'sigma_noise': 0.3314648549662138, 'A_repulsion': 0.2944670476418878, 'gamma': 0.9007412583117724, 'sigma_update': 0.09634975581517552, 'eta_learning': 0.43031191661230783, 'sigma_boundary': 5.172498068621802, 'alpha': 0.26249118947533406}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:13:34,060] Trial 20 finished with value: 0.7946059870745338 and parameters: {'sigma_noise': 0.36866411692983364, 'A_repulsion': 0.18360412692265002, 'gamma': 0.35640978813039004, 'sigma_update': 0.014768673373259184, 'eta_learning': 0.7945617919715787, 'sigma_boundary': 2.4932842726481312, 'alpha': 0.26175637814853936}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:14:48,286] Trial 21 finished with value: 0.040609878264664015 and parameters: {'sigma_noise': 0.2904165476477643, 'A_repulsion': 0.30519611989496326, 'gamma': 0.0127748863879832, 'sigma_update': 0.2514720221450171, 'eta_learning': 0.030356466001873708, 'sigma_boundary': 1.4274649481165147, 'alpha': 0.36150122862243733}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:16:13,388] Trial 22 finished with value: 0.06788781358018253 and parameters: {'sigma_noise': 0.3613220935812965, 'A_repulsion': 0.3235416973019941, 'gamma': 0.1193274103906432, 'sigma_update': 0.16110531080836787, 'eta_learning': 0.10303477125938122, 'sigma_boundary': 2.750555688869457, 'alpha': 0.6349778722115773}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:17:32,253] Trial 23 finished with value: 0.053790691140199215 and parameters: {'sigma_noise': 0.2627491387306829, 'A_repulsion': 0.43566611018843615, 'gamma': 0.06661736372343377, 'sigma_update': 0.2197105437897789, 'eta_learning': 0.11095731850026702, 'sigma_boundary': 0.31820644419488486, 'alpha': 0.4451247701208414}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:18:46,674] Trial 24 finished with value: 0.0783457390716103 and parameters: {'sigma_noise': 0.3215121496469606, 'A_repulsion': 0.24229935611448067, 'gamma': 0.40837004695627555, 'sigma_update': 0.13065833459750412, 'eta_learning': 0.22053930776339625, 'sigma_boundary': 1.8486498231627118, 'alpha': 0.3171971664568714}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:19:38,206] Trial 25 finished with value: 0.05508841693970081 and parameters: {'sigma_noise': 0.07282370800644195, 'A_repulsion': 0.2727883620956549, 'gamma': 0.16480284877741802, 'sigma_update': 0.3134268920685833, 'eta_learning': 0.04838776950816661, 'sigma_boundary': 0.02727203998290184, 'alpha': 0.5326190533959503}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:20:48,058] Trial 26 finished with value: 0.253974865982033 and parameters: {'sigma_noise': 0.17420253174627992, 'A_repulsion': 0.337935742389036, 'gamma': 0.05566698701095822, 'sigma_update': 0.06090282681944309, 'eta_learning': 0.3518979026711367, 'sigma_boundary': 4.488398351348094, 'alpha': 0.18987116293479528}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:22:18,846] Trial 27 finished with value: 0.05804541730237874 and parameters: {'sigma_noise': 0.35848697679204206, 'A_repulsion': 0.41850441781088155, 'gamma': 0.18504122981099252, 'sigma_update': 0.2304068898759404, 'eta_learning': 0.23985818804342754, 'sigma_boundary': 5.78400923617368, 'alpha': 0.42454658189923933}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:23:29,033] Trial 28 finished with value: 0.12635662270356868 and parameters: {'sigma_noise': 0.2838311323306457, 'A_repulsion': 0.23989222817555064, 'gamma': 0.2564298221424888, 'sigma_update': 0.13526389068225292, 'eta_learning': 0.4135643571073418, 'sigma_boundary': 1.090606560841024, 'alpha': 0.30244283451226583}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:24:15,797] Trial 29 finished with value: 0.03370511772844744 and parameters: {'sigma_noise': 0.01683343628942413, 'A_repulsion': 0.3433250712983739, 'gamma': 0.3682117972069703, 'sigma_update': 0.3905448384552304, 'eta_learning': 0.09815815516450005, 'sigma_boundary': 7.190646733158463, 'alpha': 0.20646159374282072}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:24:56,890] Trial 30 finished with value: 0.04212621536999216 and parameters: {'sigma_noise': 0.01128055841172404, 'A_repulsion': 0.13535404508541632, 'gamma': 0.6371181108835207, 'sigma_update': 0.42490521417997157, 'eta_learning': 0.54907323101053, 'sigma_boundary': 7.761743135037798, 'alpha': 0.17062829972121307}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:25:46,490] Trial 31 finished with value: 0.048401914157792145 and parameters: {'sigma_noise': 0.04831770780485017, 'A_repulsion': 0.3460766210017971, 'gamma': 0.010807276449666676, 'sigma_update': 0.28335907088, 'eta_learning': 0.08629374649421802, 'sigma_boundary': 6.831616808441135, 'alpha': 0.24353750531701568}. Best is trial 0 with value: 0.028881883634828534.
[I 2026-07-01 15:26:42,566] Trial 32 finished with value: 0.02845734303463819 and parameters: {'sigma_noise': 0.07183818359923755, 'A_repulsion': 0.40295289767387243, 'gamma': 0.13736747210032288, 'sigma_update': 0.36656842393215877, 'eta_learning': 0.1571631011375315, 'sigma_boundary': 7.566719287152969, 'alpha': 0.127919155729751}. Best is trial 32 with value: 0.02845734303463819.
[I 2026-07-01 15:27:39,221] Trial 33 finished with value: 0.03259777594531071 and parameters: {'sigma_noise': 0.079800716079378, 'A_repulsion': 0.4015869818058281, 'gamma': 0.37916850299806315, 'sigma_update': 0.3963602351375767, 'eta_learning': 0.15284889866863308, 'sigma_boundary': 8.000923630366264, 'alpha': 0.012534843881826463}. Best is trial 32 with value: 0.02845734303463819.
[I 2026-07-01 15:28:35,700] Trial 34 finished with value: 0.03859153840050042 and parameters: {'sigma_noise': 0.07316325828215287, 'A_repulsion': 0.4529657602001028, 'gamma': 0.13717828583787672, 'sigma_update': 0.49536054878739766, 'eta_learning': 0.17253518635244602, 'sigma_boundary': 8.693247362153947, 'alpha': 0.07941680705864991}. Best is trial 32 with value: 0.02845734303463819.
[I 2026-07-01 15:29:38,626] Trial 35 finished with value: 0.08244801565703466 and parameters: {'sigma_noise': 0.1439740490401544, 'A_repulsion': 0.39697885396638266, 'gamma': 0.5237200372395101, 'sigma_update': 0.4423519861822706, 'eta_learning': 0.1449102347644412, 'sigma_boundary': 8.222736880762712, 'alpha': 0.0031189519295792}. Best is trial 32 with value: 0.02845734303463819.
[I 2026-07-01 15:30:34,546] Trial 36 finished with value: 0.06374632191681177 and parameters: {'sigma_noise': 0.07450474752944913, 'A_repulsion': 0.4614288542190139, 'gamma': 0.726988846498953, 'sigma_update': 0.3326899765007223, 'eta_learning': 0.2975092728401818, 'sigma_boundary': 9.931532287097653, 'alpha': 0.12055257282072529}. Best is trial 32 with value: 0.02845734303463819.
[I 2026-07-01 15:31:48,440] Trial 37 finished with value: 0.4979384128346545 and parameters: {'sigma_noise': 0.22857220030998512, 'A_repulsion': 0.3988580251035094, 'gamma': 0.4238958851104588, 'sigma_update': 0.5326763496157378, 'eta_learning': 0.2359910341863639, 'sigma_boundary': 6.258653103234815, 'alpha': 0.04260685892751659}. Best is trial 32 with value: 0.02845734303463819.
[I 2026-07-01 15:32:36,979] Trial 38 finished with value: 0.01471133197308892 and parameters: {'sigma_noise': 0.051254739002801544, 'A_repulsion': 0.27435661311541815, 'gamma': 0.5915443098646271, 'sigma_update': 0.6279808310427799, 'eta_learning': 0.1428440815643896, 'sigma_boundary': 8.223722434601235, 'alpha': 0.10952303761958204}. Best is trial 38 with value: 0.01471133197308892.
[I 2026-07-01 15:33:44,193] Trial 39 finished with value: 0.060983793647465825 and parameters: {'sigma_noise': 0.049420657939746405, 'A_repulsion': 0.2792010176301055, 'gamma': 0.614960145831036, 'sigma_update': 0.6889931443028962, 'eta_learning': 0.3921158226430401, 'sigma_boundary': 9.165654510531914, 'alpha': 0.15722957701031465}. Best is trial 38 with value: 0.01471133197308892.
[I 2026-07-01 15:34:55,844] Trial 40 finished with value: 0.12242370139297959 and parameters: {'sigma_noise': 0.20845872733421383, 'A_repulsion': 0.07614731611304165, 'gamma': 0.4828121085447137, 'sigma_update': 0.6222532787535899, 'eta_learning': 0.3260960168550559, 'sigma_boundary': 6.72382722217802, 'alpha': 0.3080203939146968}. Best is trial 38 with value: 0.01471133197308892.
[I 2026-07-01 15:35:47,204] Trial 41 finished with value: 0.012277508215513407 and parameters: {'sigma_noise': 0.09142072461273426, 'A_repulsion': 0.17992123159855417, 'gamma': 0.6854004326589406, 'sigma_update': 0.5757390135801574, 'eta_learning': 0.13256227716217744, 'sigma_boundary': 8.290776546024155, 'alpha': 0.12104655049576549}. Best is trial 41 with value: 0.012277508215513407.
[I 2026-07-01 15:36:32,101] Trial 42 finished with value: 0.04030863008905932 and parameters: {'sigma_noise': 0.04031671902806093, 'A_repulsion': 0.15235394439595829, 'gamma': 0.5737387832111456, 'sigma_update': 0.6224972721469905, 'eta_learning': 0.013863738704865403, 'sigma_boundary': 7.602236023539442, 'alpha': 0.22792230038618727}. Best is trial 41 with value: 0.012277508215513407.
[I 2026-07-01 15:37:27,893] Trial 43 finished with value: 0.056469214506142985 and parameters: {'sigma_noise': 0.15502385467901159, 'A_repulsion': 0.17710146248445763, 'gamma': 0.6874394541975486, 'sigma_update': 0.5708005634317578, 'eta_learning': 0.20859257440072862, 'sigma_boundary': 8.437526725568592, 'alpha': 0.12955767238352764}. Best is trial 41 with value: 0.012277508215513407.
[I 2026-07-01 15:38:22,542] Trial 44 finished with value: 0.014152744950182157 and parameters: {'sigma_noise': 0.10066096683105555, 'A_repulsion': 0.22007834353982725, 'gamma': 0.6625153628217743, 'sigma_update': 0.6573242172417725, 'eta_learning': 0.12559842218013106, 'sigma_boundary': 8.878434408907628, 'alpha': 0.09405980788029436}. Best is trial 41 with value: 0.012277508215513407.
[I 2026-07-01 15:39:17,903] Trial 45 finished with value: 0.056048699355793374 and parameters: {'sigma_noise': 0.09917438353213774, 'A_repulsion': 0.21427458875380037, 'gamma': 0.8224145541007718, 'sigma_update': 0.5802075507212396, 'eta_learning': 0.26477586716985496, 'sigma_boundary': 9.46178784879976, 'alpha': 0.07675995248916362}. Best is trial 41 with value: 0.012277508215513407.
[I 2026-07-01 15:40:11,856] Trial 46 finished with value: 0.01546420246050985 and parameters: {'sigma_noise': 0.12774625481538984, 'A_repulsion': 0.11519514394577879, 'gamma': 0.8083170508312492, 'sigma_update': 0.6610712693547214, 'eta_learning': 0.13588131407682275, 'sigma_boundary': 8.826794948416891, 'alpha': 0.1021224497408953}. Best is trial 41 with value: 0.012277508215513407.
[I 2026-07-01 15:40:58,665] Trial 47 finished with value: 0.012673294838077583 and parameters: {'sigma_noise': 0.058206881542636986, 'A_repulsion': 0.09442382531287971, 'gamma': 0.8161901843212812, 'sigma_update': 0.6605439113048202, 'eta_learning': 0.1314405270411453, 'sigma_boundary': 8.763508448814617, 'alpha': 0.14056643283356574}. Best is trial 41 with value: 0.012277508215513407.
[I 2026-07-01 15:41:53,005] Trial 48 finished with value: 0.01646539231034088 and parameters: {'sigma_noise': 0.1311313263489986, 'A_repulsion': 0.09235978004081398, 'gamma': 0.8276485842378465, 'sigma_update': 0.6556112484494633, 'eta_learning': 0.1330042714697943, 'sigma_boundary': 8.858487258163176, 'alpha': 0.054424115547983515}. Best is trial 41 with value: 0.012277508215513407.
[I 2026-07-01 15:42:45,919] Trial 49 finished with value: 0.03024055883537416 and parameters: {'sigma_noise': 0.09814102292220983, 'A_repulsion': 0.05609171589404982, 'gamma': 0.8923063036124581, 'sigma_update': 0.6669967352365036, 'eta_learning': 0.06386079934555622, 'sigma_boundary': 9.891496556562375, 'alpha': 0.9641095532906515}. Best is trial 41 with value: 0.012277508215513407.

--- Repetition 1/1, Fold 2/2 ---

[I 2026-07-01 15:46:18,255] A new study created in memory with name: no-name-6dd00a8d-2e01-488e-9a02-a7ab5fc76081
[W 2026-07-01 15:46:59,063] Trial 0 failed with parameters: {'sigma_noise': 0.23130453864636627, 'A_repulsion': 0.18301128532134425, 'gamma': 0.452841141347309, 'sigma_update': 0.25970184790431533, 'eta_learning': 0.6392867793009408, 'sigma_boundary': 5.401778771013789, 'alpha': 0.3486167982943438} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "c:\Users\Akrami_Lab5\AppData\Local\python\pythoncore-3.14-64\Lib\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
  File "d:\sc_modelling-amir-2025\Final-Hybrid - Copy\binned_Models\binned_Gradient_free_Opt.py", line 389, in <lambda>
    objective = lambda trial: train_objective_pooled(
                              ~~~~~~~~~~~~~~~~~~~~~~^
        trial=trial,
        ^^^^^^^^^^^^
    ...<10 lines>...
        n_bins=n_bins,
        ^^^^^^^^^^^^^^
    )
    ^
  File "d:\sc_modelling-amir-2025\Final-Hybrid - Copy\binned_Models\binned_Gradient_free_Opt.py", line 324, in train_objective_pooled
    matrices = _pooled_model_matrices(
        df=train_df,
    ...<7 lines>...
        n_bins=n_bins,
    )
  File "d:\sc_modelling-amir-2025\Final-Hybrid - Copy\binned_Models\binned_Gradient_free_Opt.py", line 165, in _pooled_model_matrices
    counts_sc = post_correct_binned_counts(
        s=out["s"],
    ...<4 lines>...
        n_bins=n_bins,
    )
  File "d:\sc_modelling-amir-2025\Final-Hybrid - Copy\binned_Models\Fitter.py", line 1105, in post_correct_binned_counts
    B_total[i_cur] += ch
    ~~~~~~~^^^^^^^
KeyboardInterrupt
[W 2026-07-01 15:46:59,075] Trial 0 failed with value None.

KeyboardInterrupt:

In [49]:
import time

import binned_Hybrid_hpc_utils as hpc

start = time.time()

save_path = r"D:\sc_modelling-amir-2025\Final-Hybrid - Copy\rat_test.pkl"

hpc.run_pid_repeated_cv(
    species="rat",
    p_id="EM57",
    save_path=save_path,
    model_mode="fixed_alpha",
    custom_alpha=0.3,
    repetition_seeds=[1],      # only one repetition
    cv_folds=2,
    optuna_trials=200,
    sampler_type="TPE",
    model_seed_count=5,
    fit_with="conditional",
)

elapsed = time.time() - start

print(f"\nFinished in {elapsed/60:.2f} minutes")

  ✱ Running repeated CV
  ✱ Species: rat
  ✱ Subject: EM57
  ✱ ID column: Participant_ID
  ✱ Data path: D:\sc_modelling-amir-2025\Final-Hybrid - Copy\Data_rat_first_dists_V2.pkl
  ✱ Model mode: fixed_alpha
  ✱ Custom alpha: 0.3
  ✱ Repetitions: 1
  ✱ Folds: 2
  ✱ Model seeds per objective: 5
  ✱ Sampler: TPE

==============================
Running variant: Hybrid_fixed_alpha_0p300
==============================

--- Repetition 1/1, Fold 1/2 ---

[I 2026-07-01 15:47:21,316] A new study created in memory with name: no-name-1b7ee135-4008-4af2-b817-d194d10a9404
[I 2026-07-01 15:48:20,327] Trial 0 finished with value: 0.03436421131921108 and parameters: {'sigma_noise': 0.08159018215585934, 'A_repulsion': 0.37739043882567497, 'eta_learning': 0.5677678301612995, 'sigma_boundary': 2.2603914995438967, 'gamma': 0.3478491667769279, 'sigma_update': 0.11521894657554463}. Best is trial 0 with value: 0.03436421131921108.
[I 2026-07-01 15:49:11,878] Trial 1 finished with value: 0.021558787506590352 and parameters: {'sigma_noise': 0.16188413489871117, 'A_repulsion': 0.020837442440254983, 'eta_learning': 0.2554609703681004, 'sigma_boundary': 6.0017303474943855, 'gamma': 0.9712617163345879, 'sigma_update': 0.49442411406319725}. Best is trial 1 with value: 0.021558787506590352.
[I 2026-07-01 15:50:20,689] Trial 2 finished with value: 0.31847769018454136 and parameters: {'sigma_noise': 0.3267775293777396, 'A_repulsion': 0.09880909744250538, 'eta_learning': 0.5008435317223655, 'sigma_boundary': 2.1018301929518968, 'gamma': 0.7917811153454742, 'sigma_update': 0.5746881351261827}. Best is trial 1 with value: 0.021558787506590352.
[I 2026-07-01 15:51:20,230] Trial 3 finished with value: 0.04788741509990281 and parameters: {'sigma_noise': 0.06830249073709564, 'A_repulsion': 0.4629743100693264, 'eta_learning': 0.09857717714648122, 'sigma_boundary': 5.497686874622219, 'gamma': 0.09086713200888086, 'sigma_update': 0.3277403864627278}. Best is trial 1 with value: 0.021558787506590352.
[I 2026-07-01 15:52:24,763] Trial 4 finished with value: 0.08559600908288667 and parameters: {'sigma_noise': 0.17940623902781755, 'A_repulsion': 0.24433360359810447, 'eta_learning': 0.47918166793129985, 'sigma_boundary': 2.5871382402701117, 'gamma': 0.9958949287731433, 'sigma_update': 0.27530177411816}. Best is trial 1 with value: 0.021558787506590352.
[I 2026-07-01 15:53:42,848] Trial 5 finished with value: 0.5941954179305045 and parameters: {'sigma_noise': 0.1994435116947393, 'A_repulsion': 0.4582435614822148, 'eta_learning': 0.9338473375652437, 'sigma_boundary': 9.653829981404058, 'gamma': 0.5299969500627982, 'sigma_update': 0.629583261658432}. Best is trial 1 with value: 0.021558787506590352.
[I 2026-07-01 15:54:56,343] Trial 6 finished with value: 0.4378884648198061 and parameters: {'sigma_noise': 0.2434816178733748, 'A_repulsion': 0.3012709148892999, 'eta_learning': 0.7138351848729305, 'sigma_boundary': 9.869860135285233, 'gamma': 0.3340527305761304, 'sigma_update': 0.48439566320852306}. Best is trial 1 with value: 0.021558787506590352.
[I 2026-07-01 15:56:06,289] Trial 7 finished with value: 0.4985885612545356 and parameters: {'sigma_noise': 0.42173929991324877, 'A_repulsion': 0.023514835890982133, 'eta_learning': 0.5494841403141102, 'sigma_boundary': 6.984953043795164, 'gamma': 0.27920015081441985, 'sigma_update': 0.6312042317418479}. Best is trial 1 with value: 0.021558787506590352.
[I 2026-07-01 15:57:20,904] Trial 8 finished with value: 0.3363927394102944 and parameters: {'sigma_noise': 0.16856336781991543, 'A_repulsion': 0.47018544874626084, 'eta_learning': 0.6223008563233802, 'sigma_boundary': 6.74940290177888, 'gamma': 0.09795886922658582, 'sigma_update': 0.5055279980684282}. Best is trial 1 with value: 0.021558787506590352.
[I 2026-07-01 15:58:16,039] Trial 9 finished with value: 0.028630622686565944 and parameters: {'sigma_noise': 0.16718397710047916, 'A_repulsion': 0.05595845041740238, 'eta_learning': 0.4417028170586605, 'sigma_boundary': 7.960893059981178, 'gamma': 0.5406199369766412, 'sigma_update': 0.17976240876083485}. Best is trial 1 with value: 0.021558787506590352.
[I 2026-07-01 15:59:26,809] Trial 10 finished with value: 0.01462680793976701 and parameters: {'sigma_noise': 0.3096329125694326, 'A_repulsion': 0.1565099771069034, 'eta_learning': 0.1299907866807393, 'sigma_boundary': 0.16505518496140148, 'gamma': 0.9941074032930145, 'sigma_update': 0.41753430017806037}. Best is trial 10 with value: 0.01462680793976701.
[I 2026-07-01 16:00:37,767] Trial 11 finished with value: 0.013803018684861277 and parameters: {'sigma_noise': 0.3079962965715247, 'A_repulsion': 0.14946591021740233, 'eta_learning': 0.14225679111977263, 'sigma_boundary': 0.47784021426595163, 'gamma': 0.967450338066088, 'sigma_update': 0.4234671322018286}. Best is trial 11 with value: 0.013803018684861277.
[I 2026-07-01 16:01:50,257] Trial 12 finished with value: 0.016268649227136216 and parameters: {'sigma_noise': 0.3182735446022875, 'A_repulsion': 0.15155931058179878, 'eta_learning': 0.01670027460383347, 'sigma_boundary': 0.8397701578335027, 'gamma': 0.7233202225408608, 'sigma_update': 0.38858510362794757}. Best is trial 11 with value: 0.013803018684861277.
[I 2026-07-01 16:03:04,675] Trial 13 finished with value: 0.022508025614869347 and parameters: {'sigma_noise': 0.321533358971723, 'A_repulsion': 0.1829016680933289, 'eta_learning': 0.2722463980212039, 'sigma_boundary': 0.11872581889840816, 'gamma': 0.8238277116558506, 'sigma_update': 0.39246671050389065}. Best is trial 11 with value: 0.013803018684861277.
[I 2026-07-01 16:04:31,351] Trial 14 finished with value: 0.23553995359973906 and parameters: {'sigma_noise': 0.4302970643753903, 'A_repulsion': 0.20074826449746452, 'eta_learning': 0.19524093628315511, 'sigma_boundary': 3.9086671184021387, 'gamma': 0.6900909771988831, 'sigma_update': 0.2542955825056299}. Best is trial 11 with value: 0.013803018684861277.
[I 2026-07-01 16:05:49,635] Trial 15 finished with value: 0.4360419049629987 and parameters: {'sigma_noise': 0.27141026129152446, 'A_repulsion': 0.13265937952885076, 'eta_learning': 0.3415631255274282, 'sigma_boundary': 4.017164950380231, 'gamma': 0.8916234726890347, 'sigma_update': 0.012931458551380226}. Best is trial 11 with value: 0.013803018684861277.
[I 2026-07-01 16:07:17,194] Trial 16 finished with value: 0.12174853475178055 and parameters: {'sigma_noise': 0.3593814935585211, 'A_repulsion': 0.31227805473311054, 'eta_learning': 0.11753909125463335, 'sigma_boundary': 1.1386180335133722, 'gamma': 0.653493425115643, 'sigma_update': 0.4409207737226015}. Best is trial 11 with value: 0.013803018684861277.
[I 2026-07-01 16:08:33,657] Trial 17 finished with value: 0.20986783709272333 and parameters: {'sigma_noise': 0.37216060190006917, 'A_repulsion': 0.0941872269678847, 'eta_learning': 0.35674041957178027, 'sigma_boundary': 3.8081928033594687, 'gamma': 0.8820554703981097, 'sigma_update': 0.3119602403571156}. Best is trial 11 with value: 0.013803018684861277.
[W 2026-07-01 16:09:10,713] Trial 18 failed with parameters: {'sigma_noise': 0.29044055087339493, 'A_repulsion': 0.22737401395512294, 'eta_learning': 0.02625282602152479, 'sigma_boundary': 0.23213964764432224, 'gamma': 0.9769510456527681, 'sigma_update': 0.695399672438453} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "c:\Users\Akrami_Lab5\AppData\Local\python\pythoncore-3.14-64\Lib\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
  File "d:\sc_modelling-amir-2025\Final-Hybrid - Copy\binned_Models\binned_Gradient_free_Opt.py", line 389, in <lambda>
    objective = lambda trial: train_objective_pooled(
                              ~~~~~~~~~~~~~~~~~~~~~~^
        trial=trial,
        ^^^^^^^^^^^^
    ...<10 lines>...
        n_bins=n_bins,
        ^^^^^^^^^^^^^^
    )
    ^
  File "d:\sc_modelling-amir-2025\Final-Hybrid - Copy\binned_Models\binned_Gradient_free_Opt.py", line 324, in train_objective_pooled
    matrices = _pooled_model_matrices(
        df=train_df,
    ...<7 lines>...
        n_bins=n_bins,
    )
  File "d:\sc_modelling-amir-2025\Final-Hybrid - Copy\binned_Models\binned_Gradient_free_Opt.py", line 134, in _pooled_model_matrices
    out = model_outputs(
        x=x,
    ...<17 lines>...
        mode=mode_pre,
    )
  File "d:\sc_modelling-amir-2025\Final-Hybrid - Copy\binned_Models\Hybrid.py", line 320, in Hybrid_model_outputs
    ) = hybrid_calc(
        ~~~~~~~~~~~^
        x=x,
        ^^^^
    ...<11 lines>...
        seed=seed
        ^^^^^^^^^
    )
    ^
  File "d:\sc_modelling-amir-2025\Final-Hybrid - Copy\binned_Models\Hybrid.py", line 82, in hybrid_calc
    g = norm.pdf(x, loc=x[j], scale=sigma_update)
  File "c:\Users\Akrami_Lab5\AppData\Local\python\pythoncore-3.14-64\Lib\site-packages\scipy\stats\_distn_infrastructure.py", line 2065, in pdf
    x = np.asarray((x - loc)/scale, dtype=dtyp)
KeyboardInterrupt
[W 2026-07-01 16:09:10,727] Trial 18 failed with value None.

KeyboardInterrupt:

In [50]:
import time

import binned_Hybrid_hpc_utils as hpc

start = time.time()

save_path = r"D:\sc_modelling-amir-2025\Final-Hybrid - Copy\mouse_test.pkl"

hpc.run_pid_repeated_cv(
    species="mouse",
    p_id="QP0101",
    save_path=save_path,
    model_mode="all",
    repetition_seeds=[1],      # only one repetition
    cv_folds=2,
    optuna_trials=200,          # increase later
    sampler_type="TPE",
    model_seed_count=5,
    fit_with="conditional",
)

elapsed = time.time() - start

print(f"\nFinished in {elapsed/60:.2f} minutes")

  ✱ Running repeated CV
  ✱ Species: mouse
  ✱ Subject: QP0101
  ✱ ID column: Participant_ID
  ✱ Data path: D:\sc_modelling-amir-2025\Final-Hybrid - Copy\SC_Data_Cleaned.pkl
  ✱ Model mode: all
  ✱ Custom alpha: None
  ✱ Repetitions: 1
  ✱ Folds: 2
  ✱ Model seeds per objective: 5
  ✱ Sampler: TPE

==============================
Running variant: Hybrid
==============================

--- Repetition 1/1, Fold 1/2 ---

[I 2026-07-01 16:09:53,223] A new study created in memory with name: no-name-eb0810dd-17a5-46bf-8253-97b9ea1585bf
[I 2026-07-01 16:11:37,033] Trial 0 finished with value: 0.06992882165968768 and parameters: {'sigma_noise': 0.08159018215585934, 'A_repulsion': 0.37739043882567497, 'gamma': 0.5677678301612995, 'sigma_update': 0.1654324459144433, 'eta_learning': 0.3478491667769279, 'sigma_boundary': 1.5333873569415812, 'alpha': 0.345191215678889}. Best is trial 0 with value: 0.06992882165968768.
[I 2026-07-01 16:12:52,205] Trial 1 finished with value: 0.07193229135996017 and parameters: {'sigma_noise': 0.028336949347424388, 'A_repulsion': 0.12397018705459617, 'gamma': 0.6037750794814256, 'sigma_update': 0.6799702871422885, 'eta_learning': 0.7050432940906743, 'sigma_boundary': 7.202289814735496, 'alpha': 0.19761819488501076}. Best is trial 0 with value: 0.06992882165968768.
[I 2026-07-01 16:14:48,990] Trial 2 finished with value: 0.06029130100505398 and parameters: {'sigma_noise': 0.22815268076549577, 'A_repulsion': 0.1046962058534483, 'gamma': 0.7917811153454742, 'sigma_update': 0.5746881351261827, 'eta_learning': 0.1411806041584652, 'sigma_boundary': 9.26022671518514, 'alpha': 0.08947189610755679}. Best is trial 2 with value: 0.06029130100505398.
[I 2026-07-01 16:16:41,564] Trial 3 finished with value: 0.13230650392407028 and parameters: {'sigma_noise': 0.2516999224057834, 'A_repulsion': 0.04084198586307114, 'gamma': 0.4658883805769573, 'sigma_update': 0.2756597839299866, 'eta_learning': 0.49378053512424686, 'sigma_boundary': 4.744469558215844, 'alpha': 0.257971795822834}. Best is trial 2 with value: 0.06029130100505398.
[I 2026-07-01 16:19:18,111] Trial 4 finished with value: 0.3057837459622503 and parameters: {'sigma_noise': 0.4481755238991748, 'A_repulsion': 0.19224766240446378, 'gamma': 0.43624790131316343, 'sigma_update': 0.6423761148454564, 'eta_learning': 0.9338473375652437, 'sigma_boundary': 9.653829981404058, 'alpha': 0.525249444507877}. Best is trial 2 with value: 0.06029130100505398.
[I 2026-07-01 16:21:58,468] Trial 5 finished with value: 0.10367080500294391 and parameters: {'sigma_noise': 0.4050965726517538, 'A_repulsion': 0.26532002031065316, 'gamma': 0.6065164114808138, 'sigma_update': 0.500551795517497, 'eta_learning': 0.987103256649888, 'sigma_boundary': 3.2799866449045885, 'alpha': 0.687529946679019}. Best is trial 2 with value: 0.06029130100505398.
[I 2026-07-01 16:24:05,303] Trial 6 finished with value: 0.1766672056395678 and parameters: {'sigma_noise': 0.42173929991324877, 'A_repulsion': 0.023514835890982133, 'gamma': 0.5494841403141102, 'sigma_update': 0.4917535135354017, 'eta_learning': 0.27920015081441985, 'sigma_boundary': 9.003956920436321, 'alpha': 0.36037129049980776}. Best is trial 2 with value: 0.06029130100505398.
[I 2026-07-01 16:27:17,780] Trial 7 finished with value: 0.9044948734434374 and parameters: {'sigma_noise': 0.42376319489670955, 'A_repulsion': 0.3092428567289799, 'gamma': 0.6778687560321413, 'sigma_update': 0.07130466643065073, 'eta_learning': 0.7209749537503536, 'sigma_boundary': 3.578790752804061, 'alpha': 0.11191690083480477}. Best is trial 2 with value: 0.06029130100505398.
[I 2026-07-01 16:29:28,629] Trial 8 finished with value: 0.5013341762421176 and parameters: {'sigma_noise': 0.20186791869273799, 'A_repulsion': 0.39794259559465356, 'gamma': 0.5406199369766412, 'sigma_update': 0.17976240876083485, 'eta_learning': 0.37051916155011705, 'sigma_boundary': 3.866546295171387, 'alpha': 0.16032124420670557}. Best is trial 2 with value: 0.06029130100505398.
[I 2026-07-01 16:31:02,189] Trial 9 finished with value: 0.05247111529439998 and parameters: {'sigma_noise': 0.16703620082455636, 'A_repulsion': 0.02931866830892288, 'gamma': 0.47560716888588833, 'sigma_update': 0.43722608827933773, 'eta_learning': 0.18190352970063134, 'sigma_boundary': 3.7508561719845708, 'alpha': 0.06605731391294933}. Best is trial 9 with value: 0.05247111529439998.
[I 2026-07-01 16:33:11,249] Trial 10 finished with value: 0.10673470503005367 and parameters: {'sigma_noise': 0.1529220986938244, 'A_repulsion': 0.4830342679265962, 'gamma': 0.07219970893385114, 'sigma_update': 0.36768296078431356, 'eta_learning': 0.01315547356761071, 'sigma_boundary': 0.805236547334768, 'alpha': 0.9402551641653798}. Best is trial 9 with value: 0.05247111529439998.
[I 2026-07-01 16:35:09,604] Trial 11 finished with value: 0.05057660763842327 and parameters: {'sigma_noise': 0.2903274678287991, 'A_repulsion': 0.11850948006688618, 'gamma': 0.9426906646027546, 'sigma_update': 0.49816524267252366, 'eta_learning': 0.056248858293625956, 'sigma_boundary': 6.860828225218604, 'alpha': 0.015481622778266764}. Best is trial 11 with value: 0.05057660763842327.
[I 2026-07-01 16:37:07,608] Trial 12 finished with value: 0.0369212436400414 and parameters: {'sigma_noise': 0.32027385301534006, 'A_repulsion': 0.14329147821367455, 'gamma': 0.9914772683219888, 'sigma_update': 0.3945731732035201, 'eta_learning': 0.01864073678747838, 'sigma_boundary': 6.466174617726917, 'alpha': 0.009607315893751432}. Best is trial 12 with value: 0.0369212436400414.
[I 2026-07-01 16:39:09,284] Trial 13 finished with value: 0.03642645817167751 and parameters: {'sigma_noise': 0.3134361176363229, 'A_repulsion': 0.17174791353480706, 'gamma': 0.9997469348039819, 'sigma_update': 0.3392156666324724, 'eta_learning': 0.020281129217423352, 'sigma_boundary': 6.54948622578431, 'alpha': 0.03055491654215814}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 16:41:13,201] Trial 14 finished with value: 0.04465024898245988 and parameters: {'sigma_noise': 0.3238660274382589, 'A_repulsion': 0.18783542608249737, 'gamma': 0.9675368158963923, 'sigma_update': 0.32979795684765767, 'eta_learning': 0.20680852463297755, 'sigma_boundary': 6.622564429265314, 'alpha': 0.5427923299668371}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 16:43:22,146] Trial 15 finished with value: 0.06060212732102732 and parameters: {'sigma_noise': 0.34384133224647506, 'A_repulsion': 0.18674320814265657, 'gamma': 0.827787700533229, 'sigma_update': 0.2492563005201891, 'eta_learning': 0.025858242782273756, 'sigma_boundary': 5.673318934600397, 'alpha': 0.7711516796467556}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 16:45:41,476] Trial 16 finished with value: 0.42104986279734546 and parameters: {'sigma_noise': 0.36053033308679294, 'A_repulsion': 0.25307330623714364, 'gamma': 0.22981949553295183, 'sigma_update': 0.3991058343648252, 'eta_learning': 0.4819908637413678, 'sigma_boundary': 7.647171212605746, 'alpha': 0.29910679609956775}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 16:47:30,372] Trial 17 finished with value: 0.7514349916946186 and parameters: {'sigma_noise': 0.2835504085934108, 'A_repulsion': 0.08838869905934135, 'gamma': 0.8402626828153026, 'sigma_update': 0.29293320888374824, 'eta_learning': 0.667412750320777, 'sigma_boundary': 5.541317762186733, 'alpha': 0.004388702903121026}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 16:49:58,310] Trial 18 finished with value: 0.06378686983404039 and parameters: {'sigma_noise': 0.36540485206263884, 'A_repulsion': 0.1662671144901824, 'gamma': 0.7259671427804568, 'sigma_update': 0.04773794302314738, 'eta_learning': 0.10754528548254015, 'sigma_boundary': 8.083455829450278, 'alpha': 0.42300209154810464}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 16:52:13,619] Trial 19 finished with value: 0.3985165087560877 and parameters: {'sigma_noise': 0.2979276225670946, 'A_repulsion': 0.3127451949881198, 'gamma': 0.9967484890261972, 'sigma_update': 0.1877624241256422, 'eta_learning': 0.2845515395134635, 'sigma_boundary': 6.056870332205594, 'alpha': 0.19630951385971077}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 16:54:12,445] Trial 20 finished with value: 0.09015543201316392 and parameters: {'sigma_noise': 0.37995973110357945, 'A_repulsion': 0.07564700713185964, 'gamma': 0.35870054984552147, 'sigma_update': 0.42481204406134543, 'eta_learning': 0.2111847166061493, 'sigma_boundary': 2.1963579095067725, 'alpha': 0.5996462427613471}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 16:56:14,180] Trial 21 finished with value: 0.04620328720606825 and parameters: {'sigma_noise': 0.3253497703765395, 'A_repulsion': 0.16410728783317471, 'gamma': 0.9187250403239936, 'sigma_update': 0.3301132588401721, 'eta_learning': 0.12161127791416577, 'sigma_boundary': 6.531519004687425, 'alpha': 0.4829419909675827}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 16:58:20,680] Trial 22 finished with value: 0.0579159699513337 and parameters: {'sigma_noise': 0.3183874315888833, 'A_repulsion': 0.20542765901158028, 'gamma': 0.9933722716963889, 'sigma_update': 0.34516555865218174, 'eta_learning': 0.22084743211956964, 'sigma_boundary': 8.12499130479649, 'alpha': 0.7480384519662859}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:00:18,212] Trial 23 finished with value: 0.06607805738071926 and parameters: {'sigma_noise': 0.25861548310642374, 'A_repulsion': 0.2227712321031881, 'gamma': 0.892116151013887, 'sigma_update': 0.22881947169426212, 'eta_learning': 0.07465577565803098, 'sigma_boundary': 4.498969727545366, 'alpha': 0.8860941189057107}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:02:01,648] Trial 24 finished with value: 0.042472635576669894 and parameters: {'sigma_noise': 0.20526115797804523, 'A_repulsion': 0.1557586493684301, 'gamma': 0.881422875489762, 'sigma_update': 0.3108801143510356, 'eta_learning': 0.41001323271651735, 'sigma_boundary': 6.356886181095825, 'alpha': 0.5903934857928499}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:03:41,264] Trial 25 finished with value: 0.0548071291527853 and parameters: {'sigma_noise': 0.19662974023024776, 'A_repulsion': 0.14583602329163575, 'gamma': 0.7332206078512755, 'sigma_update': 0.09957037455726808, 'eta_learning': 0.5618318560445941, 'sigma_boundary': 5.335888211842631, 'alpha': 0.6288315525861835}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:05:03,028] Trial 26 finished with value: 0.059452081096168785 and parameters: {'sigma_noise': 0.1134112833399364, 'A_repulsion': 0.05856914260117621, 'gamma': 0.8774856629684659, 'sigma_update': 0.43689255081867173, 'eta_learning': 0.8430722438554117, 'sigma_boundary': 8.496458726398986, 'alpha': 0.8068678229085173}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:07:00,018] Trial 27 finished with value: 0.08335312074222503 and parameters: {'sigma_noise': 0.23163143890927004, 'A_repulsion': 0.28508944581314166, 'gamma': 0.785013424874147, 'sigma_update': 0.5599658626371599, 'eta_learning': 0.3885031651452398, 'sigma_boundary': 6.125954569529094, 'alpha': 0.42454658189923933}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:08:40,898] Trial 28 finished with value: 0.16371419754171243 and parameters: {'sigma_noise': 0.1578334419175219, 'A_repulsion': 0.23932060641265734, 'gamma': 0.9077981439107645, 'sigma_update': 0.37436828676478584, 'eta_learning': 0.6052929212700927, 'sigma_boundary': 7.588520539774857, 'alpha': 0.24977283937978098}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:10:09,051] Trial 29 finished with value: 0.05535215120593433 and parameters: {'sigma_noise': 0.10557260021309177, 'A_repulsion': 0.146466008244994, 'gamma': 0.7004360198412767, 'sigma_update': 0.11930777597106274, 'eta_learning': 0.43541645974036175, 'sigma_boundary': 4.836996090393104, 'alpha': 0.3755949553210616}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:12:20,293] Trial 30 finished with value: 0.5474045672874106 and parameters: {'sigma_noise': 0.2639297851744123, 'A_repulsion': 0.332888676044292, 'gamma': 0.8471058215382149, 'sigma_update': 0.29861959742542016, 'eta_learning': 0.2713167806856962, 'sigma_boundary': 2.5458419570381867, 'alpha': 0.11397901268218424}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:14:29,784] Trial 31 finished with value: 0.05136928981015973 and parameters: {'sigma_noise': 0.3274547366131397, 'A_repulsion': 0.2207889402129249, 'gamma': 0.991479727102698, 'sigma_update': 0.32453971447035584, 'eta_learning': 0.15512182048679424, 'sigma_boundary': 6.2964578829545825, 'alpha': 0.5619882127583781}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:16:10,401] Trial 32 finished with value: 0.05592167939981284 and parameters: {'sigma_noise': 0.202742105841119, 'A_repulsion': 0.12759898708763928, 'gamma': 0.94884439127564, 'sigma_update': 0.22587596819968478, 'eta_learning': 0.3058137151600546, 'sigma_boundary': 7.145630705518764, 'alpha': 0.6737647983108281}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:17:27,754] Trial 33 finished with value: 0.08326363484133371 and parameters: {'sigma_noise': 0.03158842781925064, 'A_repulsion': 0.18015393130617252, 'gamma': 0.7753105761135579, 'sigma_update': 0.3925708709003659, 'eta_learning': 0.07327011771037212, 'sigma_boundary': 6.783940308689286, 'alpha': 0.4563262002364701}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:19:20,821] Trial 34 finished with value: 0.044013835960166066 and parameters: {'sigma_noise': 0.31262427037797896, 'A_repulsion': 0.10165230771092255, 'gamma': 0.9412519618167139, 'sigma_update': 0.26667685346604675, 'eta_learning': 0.20778420347400087, 'sigma_boundary': 7.300796293670181, 'alpha': 0.5254512117317391}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:21:04,082] Trial 35 finished with value: 0.03767371027721505 and parameters: {'sigma_noise': 0.2411049678131485, 'A_repulsion': 0.10363408536250893, 'gamma': 0.6446718279257935, 'sigma_update': 0.25717698328770233, 'eta_learning': 0.11782321936461645, 'sigma_boundary': 7.46003336736198, 'alpha': 0.27182110228384176}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:22:43,773] Trial 36 finished with value: 0.05103626496411069 and parameters: {'sigma_noise': 0.23209151842853792, 'A_repulsion': 0.06623426588734735, 'gamma': 0.6055974847630844, 'sigma_update': 0.14879785521627, 'eta_learning': 0.13266497901796154, 'sigma_boundary': 9.890047459154577, 'alpha': 0.06517907526488717}. Best is trial 13 with value: 0.03642645817167751.
[I 2026-07-01 17:24:21,738] Trial 37 finished with value: 0.035344826472979055 and parameters: {'sigma_noise': 0.2708245840674603, 'A_repulsion': 0.0033144265686984586, 'gamma': 0.6540291640695738, 'sigma_update': 0.20242040337949363, 'eta_learning': 0.06254345941893656, 'sigma_boundary': 8.888921124422392, 'alpha': 0.2794770853131812}. Best is trial 37 with value: 0.035344826472979055.
[I 2026-07-01 17:26:02,369] Trial 38 finished with value: 0.036356197804836204 and parameters: {'sigma_noise': 0.27685777414069124, 'A_repulsion': 0.017156939894182044, 'gamma': 0.38660161551408456, 'sigma_update': 0.21090077233891585, 'eta_learning': 0.06745006903918835, 'sigma_boundary': 8.971028012473496, 'alpha': 0.25345833429965114}. Best is trial 37 with value: 0.035344826472979055.
[I 2026-07-01 17:27:40,827] Trial 39 finished with value: 0.03290859975543259 and parameters: {'sigma_noise': 0.2685417296492669, 'A_repulsion': 0.01569557071217216, 'gamma': 0.39276247100270145, 'sigma_update': 0.15706729337528644, 'eta_learning': 0.027449649960430093, 'sigma_boundary': 9.288976477989754, 'alpha': 0.20975238518412762}. Best is trial 39 with value: 0.03290859975543259.
[I 2026-07-01 17:29:19,882] Trial 40 finished with value: 0.03542158788909221 and parameters: {'sigma_noise': 0.27833559862286295, 'A_repulsion': 0.0036768504971156774, 'gamma': 0.36291351370256997, 'sigma_update': 0.18880132100909938, 'eta_learning': 0.08219152979505075, 'sigma_boundary': 9.150177006178607, 'alpha': 0.1616682212991399}. Best is trial 39 with value: 0.03290859975543259.
[I 2026-07-01 17:30:58,305] Trial 41 finished with value: 0.033183891239456614 and parameters: {'sigma_noise': 0.2714729078595389, 'A_repulsion': 0.0002205847460861679, 'gamma': 0.38039834642346965, 'sigma_update': 0.1421712460690452, 'eta_learning': 0.0731958335829287, 'sigma_boundary': 9.132517453483675, 'alpha': 0.16878415437272867}. Best is trial 39 with value: 0.03290859975543259.

[calc_choice] WARNING trial=497, stim=0.1783, bin_idx=2838, x[2838]=0.1785, A=0.000e+00, B=0.000e+00, sum=0.000e+00

[I 2026-07-01 17:32:36,928] Trial 42 finished with value: 0.03420005960437928 and parameters: {'sigma_noise': 0.2748996039439612, 'A_repulsion': 0.0019959342058175015, 'gamma': 0.327701191759336, 'sigma_update': 0.1257015403833602, 'eta_learning': 0.07729204718842149, 'sigma_boundary': 8.949970462078687, 'alpha': 0.1741123882549589}. Best is trial 39 with value: 0.03290859975543259.
[I 2026-07-01 17:34:29,023] Trial 43 finished with value: 0.053730113181826425 and parameters: {'sigma_noise': 0.2620645972804364, 'A_repulsion': 0.0014725519720310907, 'gamma': 0.2856139894946576, 'sigma_update': 0.01298973010097626, 'eta_learning': 0.16362318507043838, 'sigma_boundary': 9.339531453697965, 'alpha': 0.16411296200644215}. Best is trial 39 with value: 0.03290859975543259.
[I 2026-07-01 17:36:12,471] Trial 44 finished with value: 0.045021404864805464 and parameters: {'sigma_noise': 0.2794104331209243, 'A_repulsion': 0.04516746521449178, 'gamma': 0.23897605991641807, 'sigma_update': 0.14422796252347533, 'eta_learning': 0.10634365985889432, 'sigma_boundary': 8.73365452389602, 'alpha': 0.31301676962913194}. Best is trial 39 with value: 0.03290859975543259.
[I 2026-07-01 17:37:41,673] Trial 45 finished with value: 0.04300533552650912 and parameters: {'sigma_noise': 0.1796550047596465, 'A_repulsion': 0.0057318195854245794, 'gamma': 0.3997942303152293, 'sigma_update': 0.08617742837572252, 'eta_learning': 0.3245566691741905, 'sigma_boundary': 9.470266342015034, 'alpha': 0.21530318696384254}. Best is trial 39 with value: 0.03290859975543259.
[I 2026-07-01 17:39:16,807] Trial 46 finished with value: 0.05281232749283044 and parameters: {'sigma_noise': 0.21954659552206185, 'A_repulsion': 0.041119291587741164, 'gamma': 0.3241931251292503, 'sigma_update': 0.1707061489352956, 'eta_learning': 0.24356986700021271, 'sigma_boundary': 9.850702685999561, 'alpha': 0.1753157692594767}. Best is trial 39 with value: 0.03290859975543259.
[I 2026-07-01 17:41:01,257] Trial 47 finished with value: 0.035076425456173704 and parameters: {'sigma_noise': 0.2982460015362826, 'A_repulsion': 0.030371752434875887, 'gamma': 0.4858587303861241, 'sigma_update': 0.12108449510440983, 'eta_learning': 0.058365274190345706, 'sigma_boundary': 8.335559538981192, 'alpha': 0.1220332517455683}. Best is trial 39 with value: 0.03290859975543259.
[I 2026-07-01 17:42:53,999] Trial 48 finished with value: 0.031056163244708435 and parameters: {'sigma_noise': 0.3000383622057586, 'A_repulsion': 0.030283643222987218, 'gamma': 0.45746462819229217, 'sigma_update': 0.05447164139511236, 'eta_learning': 0.039556966307992984, 'sigma_boundary': 8.29210069260219, 'alpha': 0.10669945554407823}. Best is trial 48 with value: 0.031056163244708435.
[I 2026-07-01 17:44:45,727] Trial 49 finished with value: 0.029679478966987766 and parameters: {'sigma_noise': 0.29918075287538015, 'A_repulsion': 0.032602072167461006, 'gamma': 0.5066804184210829, 'sigma_update': 0.059533855795049676, 'eta_learning': 0.03027793611288008, 'sigma_boundary': 8.395461330867144, 'alpha': 0.12439148817799005}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 17:46:52,996] Trial 50 finished with value: 0.03369743839046918 and parameters: {'sigma_noise': 0.34438904041115903, 'A_repulsion': 0.05271387401129474, 'gamma': 0.43751947794157797, 'sigma_update': 0.03260034556008086, 'eta_learning': 0.013437523877320355, 'sigma_boundary': 7.9170500099799135, 'alpha': 0.07009655804447817}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 17:49:06,300] Trial 51 finished with value: 0.033943734994926734 and parameters: {'sigma_noise': 0.3459685957578288, 'A_repulsion': 0.0503179218731998, 'gamma': 0.5361547022878315, 'sigma_update': 0.011743404491714241, 'eta_learning': 0.014427461499417815, 'sigma_boundary': 8.028285372472274, 'alpha': 0.08386989709265759}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 17:51:22,420] Trial 52 finished with value: 0.04848316822805278 and parameters: {'sigma_noise': 0.40467957355993267, 'A_repulsion': 0.05698080728820994, 'gamma': 0.532814838031201, 'sigma_update': 0.04695474383995418, 'eta_learning': 0.019982815377413386, 'sigma_boundary': 7.952954331343832, 'alpha': 0.08422841433227721}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 17:53:40,953] Trial 53 finished with value: 0.03557026059670976 and parameters: {'sigma_noise': 0.3496138409237667, 'A_repulsion': 0.0739964370701732, 'gamma': 0.44922966775864254, 'sigma_update': 0.011208626299324453, 'eta_learning': 0.014005833376389602, 'sigma_boundary': 8.521560282470743, 'alpha': 0.055495492037264074}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 17:55:38,701] Trial 54 finished with value: 0.10797148663466352 and parameters: {'sigma_noise': 0.33640622736011305, 'A_repulsion': 0.03221034577449512, 'gamma': 0.42654244939706204, 'sigma_update': 0.05539075825958377, 'eta_learning': 0.16858391462896502, 'sigma_boundary': 7.960065691004835, 'alpha': 0.12628945231581612}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 17:58:00,780] Trial 55 finished with value: 0.25323109011499284 and parameters: {'sigma_noise': 0.3883705573436798, 'A_repulsion': 0.08536784467636072, 'gamma': 0.5606657722396143, 'sigma_update': 0.031797678712349814, 'eta_learning': 0.03895149642551753, 'sigma_boundary': 0.05335261577613437, 'alpha': 0.22002293582916893}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 17:59:51,720] Trial 56 finished with value: 0.06632285470802926 and parameters: {'sigma_noise': 0.30225140921863547, 'A_repulsion': 0.05419072021226745, 'gamma': 0.16119234360355736, 'sigma_update': 0.07703189303915023, 'eta_learning': 0.0986305396634657, 'sigma_boundary': 9.549737958651523, 'alpha': 0.04150036782179395}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:01:58,077] Trial 57 finished with value: 0.16323841914889942 and parameters: {'sigma_noise': 0.44043060312267324, 'A_repulsion': 0.024271477485723697, 'gamma': 0.4900315235609253, 'sigma_update': 0.09245276490732171, 'eta_learning': 0.13384452924987825, 'sigma_boundary': 8.52493426396143, 'alpha': 0.09444244323370841}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:05:13,363] Trial 58 finished with value: 0.07888351834254366 and parameters: {'sigma_noise': 0.35626885809940134, 'A_repulsion': 0.4567003037005565, 'gamma': 0.5206510210969371, 'sigma_update': 0.03665399927241972, 'eta_learning': 0.01362663437231143, 'sigma_boundary': 7.743711201203029, 'alpha': 0.3501264600901573}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:07:26,148] Trial 59 finished with value: 0.27974347491380935 and parameters: {'sigma_noise': 0.34034481628650426, 'A_repulsion': 0.1262818446708766, 'gamma': 0.5772696469359218, 'sigma_update': 0.059170724083638104, 'eta_learning': 0.18336377027316617, 'sigma_boundary': 7.0281086432775615, 'alpha': 0.0004706026652998019}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:09:27,551] Trial 60 finished with value: 0.05197483297912599 and parameters: {'sigma_noise': 0.372537936372966, 'A_repulsion': 0.09344756269730743, 'gamma': 0.4216862132491159, 'sigma_update': 0.15323925991425372, 'eta_learning': 0.05033834597412232, 'sigma_boundary': 9.278448456272873, 'alpha': 0.14332898169398364}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:11:05,806] Trial 61 finished with value: 0.03469683487804694 and parameters: {'sigma_noise': 0.2500241381016699, 'A_repulsion': 0.023194819124300853, 'gamma': 0.3051910423708082, 'sigma_update': 0.10439647845395171, 'eta_learning': 0.09313706176640818, 'sigma_boundary': 9.986064015847795, 'alpha': 0.20128877256121458}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:12:51,393] Trial 62 finished with value: 0.03254353433404981 and parameters: {'sigma_noise': 0.29367135554739465, 'A_repulsion': 0.04597593064005914, 'gamma': 0.45462643367113137, 'sigma_update': 0.12933482651094919, 'eta_learning': 0.04363227043972741, 'sigma_boundary': 8.764095909489418, 'alpha': 0.08241151256128293}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:14:44,704] Trial 63 finished with value: 0.03386157924347123 and parameters: {'sigma_noise': 0.3087278480749478, 'A_repulsion': 0.04498111453140515, 'gamma': 0.47428130450239514, 'sigma_update': 0.06976803127025051, 'eta_learning': 0.0416350713941315, 'sigma_boundary': 8.313738928965138, 'alpha': 0.09252253156277135}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:16:41,546] Trial 64 finished with value: 0.04195058629823298 and parameters: {'sigma_noise': 0.3065432852891895, 'A_repulsion': 0.08139356268352615, 'gamma': 0.4603922964461234, 'sigma_update': 0.07392860173167287, 'eta_learning': 0.04638566614593999, 'sigma_boundary': 8.716699449059266, 'alpha': 0.033145724436216786}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:18:28,990] Trial 65 finished with value: 0.6270280477335014 and parameters: {'sigma_noise': 0.2904144329885358, 'A_repulsion': 0.06635191935094233, 'gamma': 0.3938441746372893, 'sigma_update': 0.12306125663501755, 'eta_learning': 0.8235568772918018, 'sigma_boundary': 8.212717864182268, 'alpha': 0.10289419804202109}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:20:08,367] Trial 66 finished with value: 0.06697202629325558 and parameters: {'sigma_noise': 0.2490821922360668, 'A_repulsion': 0.03227697579966096, 'gamma': 0.5006185194815015, 'sigma_update': 0.6993033213044784, 'eta_learning': 0.1396557339415406, 'sigma_boundary': 9.651836969226096, 'alpha': 0.07096087064387663}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:22:09,117] Trial 67 finished with value: 0.041590662273968126 and parameters: {'sigma_noise': 0.29213050652552475, 'A_repulsion': 0.11765040285166384, 'gamma': 0.3636275534683292, 'sigma_update': 0.06551698198046432, 'eta_learning': 0.10454099933279806, 'sigma_boundary': 7.746059607407753, 'alpha': 0.2354305633630139}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:23:56,894] Trial 68 finished with value: 0.09975742043975724 and parameters: {'sigma_noise': 0.3336147826973952, 'A_repulsion': 0.020020634409474512, 'gamma': 0.4508735656464445, 'sigma_update': 0.10761594831775985, 'eta_learning': 0.18650007013134562, 'sigma_boundary': 9.097150654802723, 'alpha': 0.13885562189349987}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:25:58,214] Trial 69 finished with value: 0.038598620262504976 and parameters: {'sigma_noise': 0.3145074838854837, 'A_repulsion': 0.04283547748377379, 'gamma': 0.2667883231129911, 'sigma_update': 0.03335073647871683, 'eta_learning': 0.04375700214734767, 'sigma_boundary': 8.586571734021168, 'alpha': 0.04314601760249509}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:27:45,564] Trial 70 finished with value: 0.04844161492263986 and parameters: {'sigma_noise': 0.2895521111474997, 'A_repulsion': 0.06722567590678571, 'gamma': 0.4182059517761549, 'sigma_update': 0.13851551625888353, 'eta_learning': 0.12933724836269153, 'sigma_boundary': 8.305452854880588, 'alpha': 0.18695779006610336}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:30:03,050] Trial 71 finished with value: 0.05585665462403038 and parameters: {'sigma_noise': 0.39398446020518135, 'A_repulsion': 0.04558747454627128, 'gamma': 0.5821703186076373, 'sigma_update': 0.023615204348657076, 'eta_learning': 0.03841241048738526, 'sigma_boundary': 8.030268230544038, 'alpha': 0.0914016594921372}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:32:03,788] Trial 72 finished with value: 0.05953661107099868 and parameters: {'sigma_noise': 0.3523751470699498, 'A_repulsion': 0.05280241675205052, 'gamma': 0.514094043127042, 'sigma_update': 0.07769864010331605, 'eta_learning': 0.0800696160456319, 'sigma_boundary': 7.438028870623713, 'alpha': 0.13004776341905838}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:34:05,449] Trial 73 finished with value: 0.036611805625609124 and parameters: {'sigma_noise': 0.36895696152100704, 'A_repulsion': 0.015902012116335615, 'gamma': 0.547280646352713, 'sigma_update': 0.04981535410996392, 'eta_learning': 0.010771358013495505, 'sigma_boundary': 4.289679262687092, 'alpha': 0.072477765414717}. Best is trial 49 with value: 0.029679478966987766.

[calc_choice] WARNING trial=5833, stim=0.3807, bin_idx=3814, x[3814]=0.3806, A=0.000e+00, B=0.000e+00, sum=0.000e+00

[I 2026-07-01 18:35:58,965] Trial 74 finished with value: 0.09332504913907792 and parameters: {'sigma_noise': 0.31754802372077384, 'A_repulsion': 0.09102791886508102, 'gamma': 0.4642736131186332, 'sigma_update': 0.6423826238763307, 'eta_learning': 0.09560847475699613, 'sigma_boundary': 8.832780191772358, 'alpha': 0.025247790702470047}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:38:27,500] Trial 75 finished with value: 0.057528819531673714 and parameters: {'sigma_noise': 0.3291731376442564, 'A_repulsion': 0.37551588660451873, 'gamma': 0.4810997424793729, 'sigma_update': 0.16158273879784116, 'eta_learning': 0.042763427938431756, 'sigma_boundary': 9.289219609911523, 'alpha': 0.149348467386479}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:40:13,828] Trial 76 finished with value: 0.14661481281686448 and parameters: {'sigma_noise': 0.3028920035291189, 'A_repulsion': 0.03677111877410229, 'gamma': 0.641110446145326, 'sigma_update': 0.09517185307538557, 'eta_learning': 0.23342079047645026, 'sigma_boundary': 7.857080741838446, 'alpha': 0.1079292592462072}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:41:56,326] Trial 77 finished with value: 0.052741467376577054 and parameters: {'sigma_noise': 0.2177078028440948, 'A_repulsion': 0.061362133269940285, 'gamma': 0.3767111508702031, 'sigma_update': 0.060797400120100833, 'eta_learning': 0.14994473147989257, 'sigma_boundary': 8.347575065250766, 'alpha': 0.05866612658978449}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:43:35,128] Trial 78 finished with value: 0.034371594570764774 and parameters: {'sigma_noise': 0.2649351217351394, 'A_repulsion': 0.014049883153968441, 'gamma': 0.3361910933205216, 'sigma_update': 0.469717302554012, 'eta_learning': 0.060583919670002415, 'sigma_boundary': 6.983560235330548, 'alpha': 0.20003399795279098}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:45:34,325] Trial 79 finished with value: 0.055372739445478034 and parameters: {'sigma_noise': 0.24171628990091337, 'A_repulsion': 0.10646176441599939, 'gamma': 0.4118923863195719, 'sigma_update': 0.023537340389052537, 'eta_learning': 0.03152426105763886, 'sigma_boundary': 7.269811428951605, 'alpha': 0.3172903281521189}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:47:26,497] Trial 80 finished with value: 0.12927758906921466 and parameters: {'sigma_noise': 0.3423152067482391, 'A_repulsion': 0.050211216468683595, 'gamma': 0.5126582051341068, 'sigma_update': 0.1805294120002658, 'eta_learning': 0.12366452970624267, 'sigma_boundary': 9.089405029764048, 'alpha': 0.0028830715353009018}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:49:06,020] Trial 81 finished with value: 0.03436864586231748 and parameters: {'sigma_noise': 0.2726991756543068, 'A_repulsion': 0.01296913867149525, 'gamma': 0.33924638479789027, 'sigma_update': 0.1333959457414717, 'eta_learning': 0.07805888717871998, 'sigma_boundary': 8.899506697816125, 'alpha': 0.1750392871268427}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:50:42,033] Trial 82 finished with value: 0.0302840516552062 and parameters: {'sigma_noise': 0.2564642679529743, 'A_repulsion': 0.001433282602274242, 'gamma': 0.4397260105036172, 'sigma_update': 0.11370545502714507, 'eta_learning': 0.06823338251683359, 'sigma_boundary': 9.65526625647983, 'alpha': 0.10603951913604359}. Best is trial 49 with value: 0.029679478966987766.
[I 2026-07-01 18:52:23,655] Trial 83 finished with value: 0.02437343844684706 and parameters: {'sigma_noise': 0.25302353163632285, 'A_repulsion': 0.03311362968767994, 'gamma': 0.43948671707666925, 'sigma_update': 0.08664316579280636, 'eta_learning': 0.012572780700998749, 'sigma_boundary': 9.661715008487107, 'alpha': 0.09175397872520176}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 18:54:03,498] Trial 84 finished with value: 0.030259612207732774 and parameters: {'sigma_noise': 0.2582429977635653, 'A_repulsion': 0.030916683261570304, 'gamma': 0.442691834636225, 'sigma_update': 0.10655586767625805, 'eta_learning': 0.06064685728223941, 'sigma_boundary': 9.815716029575958, 'alpha': 0.11544104689711289}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 18:55:41,923] Trial 85 finished with value: 0.03487711045144338 and parameters: {'sigma_noise': 0.2525284434713167, 'A_repulsion': 0.02938616352223748, 'gamma': 0.4511759014008286, 'sigma_update': 0.10497280781152876, 'eta_learning': 0.10241380528790012, 'sigma_boundary': 9.4961468939917, 'alpha': 0.13863008403178184}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 18:57:14,028] Trial 86 finished with value: 0.029916621785348096 and parameters: {'sigma_noise': 0.2171177590190207, 'A_repulsion': 0.0008081117627719604, 'gamma': 0.43467477498807783, 'sigma_update': 0.16249872157195455, 'eta_learning': 0.06521796700483468, 'sigma_boundary': 9.78286624357527, 'alpha': 0.15489143803570143}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 18:58:43,191] Trial 87 finished with value: 0.07534206191252775 and parameters: {'sigma_noise': 0.19100630742987862, 'A_repulsion': 0.012024448729714875, 'gamma': 0.4072650314317436, 'sigma_update': 0.19926686157636056, 'eta_learning': 0.5240101561060823, 'sigma_boundary': 9.758555288037227, 'alpha': 0.23225329906437317}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:00:15,665] Trial 88 finished with value: 0.0295098604333792 and parameters: {'sigma_noise': 0.2232442494605547, 'A_repulsion': 0.003968730979745608, 'gamma': 0.36114661591033936, 'sigma_update': 0.23832704552753142, 'eta_learning': 0.06947356231506611, 'sigma_boundary': 9.686602578614062, 'alpha': 0.154930971071912}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:01:49,204] Trial 89 finished with value: 0.02745739520750336 and parameters: {'sigma_noise': 0.2127210901340173, 'A_repulsion': 0.021955903647954668, 'gamma': 0.35251489192831353, 'sigma_update': 0.24186381362188158, 'eta_learning': 0.06455285598517424, 'sigma_boundary': 9.702126554826831, 'alpha': 0.11602532818322361}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:03:27,257] Trial 90 finished with value: 0.05620674242609099 and parameters: {'sigma_noise': 0.21248393350833142, 'A_repulsion': 0.07440823107068312, 'gamma': 0.18882210166193403, 'sigma_update': 0.24190270821332888, 'eta_learning': 0.18718321977321198, 'sigma_boundary': 9.986182956993495, 'alpha': 0.11245153839348435}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:05:03,451] Trial 91 finished with value: 0.029517370546059123 and parameters: {'sigma_noise': 0.23609098305604914, 'A_repulsion': 0.026484662057600927, 'gamma': 0.4338446509386221, 'sigma_update': 0.21936273932552613, 'eta_learning': 0.0634251496855424, 'sigma_boundary': 9.684900904771414, 'alpha': 0.15414540592529832}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:06:38,139] Trial 92 finished with value: 0.028886829062948538 and parameters: {'sigma_noise': 0.22968165978876953, 'A_repulsion': 0.02540972218983778, 'gamma': 0.4317110642150805, 'sigma_update': 0.21902196102245902, 'eta_learning': 0.06856101080445066, 'sigma_boundary': 9.699243170628584, 'alpha': 0.12048368016839392}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:08:13,908] Trial 93 finished with value: 0.03695135952481028 and parameters: {'sigma_noise': 0.2313754339514303, 'A_repulsion': 0.027767843599275158, 'gamma': 0.349551772900778, 'sigma_update': 0.23154894495250003, 'eta_learning': 0.12294046771406808, 'sigma_boundary': 9.686962861471514, 'alpha': 0.15392133561941243}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:09:41,836] Trial 94 finished with value: 0.03396478799413109 and parameters: {'sigma_noise': 0.17364241466715172, 'A_repulsion': 0.022040316447141866, 'gamma': 0.3076577921428265, 'sigma_update': 0.21578042961005217, 'eta_learning': 0.06879529202342072, 'sigma_boundary': 9.45337108769647, 'alpha': 0.19086785981799267}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:11:16,708] Trial 95 finished with value: 0.046674278912000634 and parameters: {'sigma_noise': 0.22440513181879962, 'A_repulsion': 0.03517105009933296, 'gamma': 0.4302872849256462, 'sigma_update': 0.2769968874944431, 'eta_learning': 0.15412072061595772, 'sigma_boundary': 9.736782470804341, 'alpha': 0.12003973995254986}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:12:50,381] Trial 96 finished with value: 0.0384469431638179 and parameters: {'sigma_noise': 0.2365416780178553, 'A_repulsion': 0.0005491451914708956, 'gamma': 0.3707772875439329, 'sigma_update': 0.17037120161172173, 'eta_learning': 0.08931033597230115, 'sigma_boundary': 9.634669674455912, 'alpha': 0.2834455263238188}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:14:20,084] Trial 97 finished with value: 0.03134353299097757 and parameters: {'sigma_noise': 0.18597333399882007, 'A_repulsion': 0.00987316266226387, 'gamma': 0.43384441110289496, 'sigma_update': 0.28667687738968745, 'eta_learning': 0.10961895511844816, 'sigma_boundary': 9.936356828212071, 'alpha': 0.04832862913797111}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:15:52,982] Trial 98 finished with value: 0.028075143955299867 and parameters: {'sigma_noise': 0.20412617843057249, 'A_repulsion': 0.03339414200911946, 'gamma': 0.4860329609554863, 'sigma_update': 0.26178900299256636, 'eta_learning': 0.06514797170006359, 'sigma_boundary': 9.429986012090717, 'alpha': 0.1449029437162064}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:17:29,127] Trial 99 finished with value: 0.057247047427410894 and parameters: {'sigma_noise': 0.20820160144846944, 'A_repulsion': 0.06403747151373991, 'gamma': 0.49571242388662606, 'sigma_update': 0.25161650220081966, 'eta_learning': 0.06101769465447125, 'sigma_boundary': 9.322703642682274, 'alpha': 0.9915834662243976}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:18:52,435] Trial 100 finished with value: 0.11085779330215427 and parameters: {'sigma_noise': 0.14316275110497548, 'A_repulsion': 0.020507440879111348, 'gamma': 0.39010073378093507, 'sigma_update': 0.19639005799325937, 'eta_learning': 0.6541471190208887, 'sigma_boundary': 9.485119871135579, 'alpha': 0.15303259698461064}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:20:25,120] Trial 101 finished with value: 0.028496814960780444 and parameters: {'sigma_noise': 0.20072752283536327, 'A_repulsion': 0.03716082276247977, 'gamma': 0.5234768897664169, 'sigma_update': 0.3068102071272843, 'eta_learning': 0.0800205255284856, 'sigma_boundary': 9.764961781869946, 'alpha': 0.12412612283270211}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:22:01,348] Trial 102 finished with value: 0.03224737836842426 and parameters: {'sigma_noise': 0.22548541390646454, 'A_repulsion': 0.03734931112766186, 'gamma': 0.5873391680955544, 'sigma_update': 0.3038148077780879, 'eta_learning': 0.08984884546204695, 'sigma_boundary': 9.731769676667057, 'alpha': 0.18320666199466853}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:23:26,534] Trial 103 finished with value: 0.028077811066236164 and parameters: {'sigma_noise': 0.16553645444903495, 'A_repulsion': 0.009894763121203052, 'gamma': 0.5247404478225227, 'sigma_update': 0.2704736723824789, 'eta_learning': 0.061642833638644444, 'sigma_boundary': 9.853424828612189, 'alpha': 0.12617419400411134}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:24:52,921] Trial 104 finished with value: 0.03520865728253947 and parameters: {'sigma_noise': 0.16663823052511703, 'A_repulsion': 0.011716926653690132, 'gamma': 0.5549187150153613, 'sigma_update': 0.26548948444668846, 'eta_learning': 0.11799153353945727, 'sigma_boundary': 9.967385115760385, 'alpha': 0.2452030267403862}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:26:16,242] Trial 105 finished with value: 0.03811808140022236 and parameters: {'sigma_noise': 0.1338152058560666, 'A_repulsion': 0.02581759914278396, 'gamma': 0.5236865719718927, 'sigma_update': 0.24165286577028072, 'eta_learning': 0.14233325252139992, 'sigma_boundary': 9.18193128100234, 'alpha': 0.21574905667649605}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:27:49,397] Trial 106 finished with value: 0.04297871607828356 and parameters: {'sigma_noise': 0.1954456308820693, 'A_repulsion': 0.03735454059747177, 'gamma': 0.47612027197758094, 'sigma_update': 0.3123800772172385, 'eta_learning': 0.17288629584906592, 'sigma_boundary': 9.480603031452137, 'alpha': 0.1323183397882135}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:29:25,874] Trial 107 finished with value: 0.029445539103678354 and parameters: {'sigma_noise': 0.20522548856272568, 'A_repulsion': 0.07943422330656566, 'gamma': 0.6315750256264913, 'sigma_update': 0.22320320182215614, 'eta_learning': 0.06275107066185893, 'sigma_boundary': 9.83580457724901, 'alpha': 0.16635622252751706}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:31:01,504] Trial 108 finished with value: 0.026035329502248225 and parameters: {'sigma_noise': 0.20144288217140652, 'A_repulsion': 0.07584483925668772, 'gamma': 0.6737616092487956, 'sigma_update': 0.35932893905748786, 'eta_learning': 0.02563850531495932, 'sigma_boundary': 9.045882875907752, 'alpha': 0.1560529919402971}. Best is trial 83 with value: 0.02437343844684706.
[I 2026-07-01 19:32:38,601] Trial 109 finished with value: 0.0240354826528279 and parameters: {'sigma_noise': 0.20055529459243301, 'A_repulsion': 0.08409264302124553, 'gamma': 0.6203444222063645, 'sigma_update': 0.3587367673798936, 'eta_learning': 0.029631906220426163, 'sigma_boundary': 3.198987552572532, 'alpha': 0.1702228318748545}. Best is trial 109 with value: 0.0240354826528279.
[I 2026-07-01 19:34:12,101] Trial 110 finished with value: 0.023377029800863192 and parameters: {'sigma_noise': 0.18065347880189273, 'A_repulsion': 0.08441943404214644, 'gamma': 0.659804737268598, 'sigma_update': 0.36902726324241875, 'eta_learning': 0.031250683449436926, 'sigma_boundary': 1.8793832111597752, 'alpha': 0.17676800784815777}. Best is trial 110 with value: 0.023377029800863192.
[I 2026-07-01 19:35:48,344] Trial 111 finished with value: 0.18473118832309848 and parameters: {'sigma_noise': 0.18043769958783176, 'A_repulsion': 0.11425311660285839, 'gamma': 0.6787151753713763, 'sigma_update': 0.3620785348741995, 'eta_learning': 0.9977096189042085, 'sigma_boundary': 2.641122633828981, 'alpha': 0.2573880718987285}. Best is trial 110 with value: 0.023377029800863192.
[I 2026-07-01 19:37:26,459] Trial 112 finished with value: 0.02237024347929606 and parameters: {'sigma_noise': 0.20230266232725932, 'A_repulsion': 0.08581135694255985, 'gamma': 0.6263184133030156, 'sigma_update': 0.3459505907858344, 'eta_learning': 0.029285776875253647, 'sigma_boundary': 1.8227506548737349, 'alpha': 0.17280877474648954}. Best is trial 112 with value: 0.02237024347929606.
[I 2026-07-01 19:39:05,500] Trial 113 finished with value: 0.03507936556258245 and parameters: {'sigma_noise': 0.20437287589496078, 'A_repulsion': 0.09966730099352515, 'gamma': 0.728503100865588, 'sigma_update': 0.38286548865514985, 'eta_learning': 0.02128834380865153, 'sigma_boundary': 1.3976760770852983, 'alpha': 0.3794658811564894}. Best is trial 112 with value: 0.02237024347929606.
[I 2026-07-01 19:40:36,063] Trial 114 finished with value: 0.023941079033381257 and parameters: {'sigma_noise': 0.1610088996310686, 'A_repulsion': 0.07767543981139444, 'gamma': 0.6243849745441474, 'sigma_update': 0.3472933614532652, 'eta_learning': 0.030969942376166272, 'sigma_boundary': 1.7705470022359342, 'alpha': 0.1726049763831868}. Best is trial 112 with value: 0.02237024347929606.
[I 2026-07-01 19:42:11,351] Trial 115 finished with value: 0.029879051146551504 and parameters: {'sigma_noise': 0.16534331019434037, 'A_repulsion': 0.13501933228729288, 'gamma': 0.6216159391494113, 'sigma_update': 0.34982949002592967, 'eta_learning': 0.03747628008720741, 'sigma_boundary': 1.7785830052270253, 'alpha': 0.22868225141255402}. Best is trial 112 with value: 0.02237024347929606.
[I 2026-07-01 19:43:48,515] Trial 116 finished with value: 0.018911796927561425 and parameters: {'sigma_noise': 0.1981998780822339, 'A_repulsion': 0.0878331605761849, 'gamma': 0.6788185931773487, 'sigma_update': 0.3364492187563282, 'eta_learning': 0.010789503024848913, 'sigma_boundary': 1.0435310774119055, 'alpha': 0.19607970930952576}. Best is trial 116 with value: 0.018911796927561425.
[I 2026-07-01 19:45:19,900] Trial 117 finished with value: 0.017821319156999534 and parameters: {'sigma_noise': 0.1573464240654501, 'A_repulsion': 0.08563096777434162, 'gamma': 0.6788423246658635, 'sigma_update': 0.4094012452528291, 'eta_learning': 0.026598738911896118, 'sigma_boundary': 0.981018956657485, 'alpha': 0.19831642385489767}. Best is trial 117 with value: 0.017821319156999534.
[I 2026-07-01 19:46:52,761] Trial 118 finished with value: 0.019927983645496365 and parameters: {'sigma_noise': 0.15373878865397983, 'A_repulsion': 0.11248545711323481, 'gamma': 0.7532408725664679, 'sigma_update': 0.4126500721848103, 'eta_learning': 0.02848754197225229, 'sigma_boundary': 0.9996962308693114, 'alpha': 0.19882745966287108}. Best is trial 117 with value: 0.017821319156999534.
[I 2026-07-01 19:48:24,444] Trial 119 finished with value: 0.01378805119619218 and parameters: {'sigma_noise': 0.1489378194917775, 'A_repulsion': 0.0996939513670874, 'gamma': 0.7672903303711289, 'sigma_update': 0.41029034435854006, 'eta_learning': 0.024208668693388884, 'sigma_boundary': 0.6232748682076041, 'alpha': 0.19358023828768745}. Best is trial 119 with value: 0.01378805119619218.
[I 2026-07-01 19:49:54,181] Trial 120 finished with value: 0.01751495831614366 and parameters: {'sigma_noise': 0.1432748162426692, 'A_repulsion': 0.11139548189336913, 'gamma': 0.7533509849611062, 'sigma_update': 0.41752061855723205, 'eta_learning': 0.02654004882151292, 'sigma_boundary': 0.8249023216395048, 'alpha': 0.20395027110643843}. Best is trial 119 with value: 0.01378805119619218.
[I 2026-07-01 19:51:26,337] Trial 121 finished with value: 0.015844984975319918 and parameters: {'sigma_noise': 0.15258367229395134, 'A_repulsion': 0.10954973602602838, 'gamma': 0.7644381027054173, 'sigma_update': 0.4042800771991701, 'eta_learning': 0.015357102370662283, 'sigma_boundary': 0.7006196604269769, 'alpha': 0.20647606811663047}. Best is trial 119 with value: 0.01378805119619218.
[I 2026-07-01 19:52:58,712] Trial 122 finished with value: 0.016200031080471168 and parameters: {'sigma_noise': 0.1476751845213133, 'A_repulsion': 0.11028057304854999, 'gamma': 0.7704664526067908, 'sigma_update': 0.41336706026561004, 'eta_learning': 0.027968883044260023, 'sigma_boundary': 0.71003377470865, 'alpha': 0.20863492217207322}. Best is trial 119 with value: 0.01378805119619218.
[I 2026-07-01 19:54:26,943] Trial 123 finished with value: 0.022129000639118948 and parameters: {'sigma_noise': 0.11863151315809209, 'A_repulsion': 0.11157736809217125, 'gamma': 0.7654080482103804, 'sigma_update': 0.4171544541688835, 'eta_learning': 0.012011143947824026, 'sigma_boundary': 0.7252788640890362, 'alpha': 0.2696421934954364}. Best is trial 119 with value: 0.01378805119619218.
[I 2026-07-01 19:55:57,707] Trial 124 finished with value: 0.028702978808431524 and parameters: {'sigma_noise': 0.12075044448958232, 'A_repulsion': 0.15401206727980266, 'gamma': 0.7583373098231663, 'sigma_update': 0.4208745160028458, 'eta_learning': 0.010150390682377044, 'sigma_boundary': 0.7434131794281922, 'alpha': 0.2959544636484117}. Best is trial 119 with value: 0.01378805119619218.

--- Repetition 1/1, Fold 2/2 ---

[I 2026-07-01 21:56:09,130] A new study created in memory with name: no-name-440a8cfb-5602-4822-9da6-d219bd028c40
[I 2026-07-01 21:58:05,287] Trial 0 finished with value: 0.09291900098219455 and parameters: {'sigma_noise': 0.23130453864636627, 'A_repulsion': 0.18301128532134425, 'gamma': 0.452841141347309, 'sigma_update': 0.25970184790431533, 'eta_learning': 0.6392867793009408, 'sigma_boundary': 5.401778771013789, 'alpha': 0.3486167982943438}. Best is trial 0 with value: 0.09291900098219455.
[I 2026-07-01 21:59:27,166] Trial 1 finished with value: 0.11314662177708065 and parameters: {'sigma_noise': 0.017208828667492883, 'A_repulsion': 0.2707457972784512, 'gamma': 0.03587961860841644, 'sigma_update': 0.07793997913386755, 'eta_learning': 0.8483468574108974, 'sigma_boundary': 8.303441021774777, 'alpha': 0.8837563487755918}. Best is trial 0 with value: 0.09291900098219455.
[I 2026-07-01 22:01:12,323] Trial 2 finished with value: 0.15026499974149043 and parameters: {'sigma_noise': 0.26940948843115053, 'A_repulsion': 0.015399236752296985, 'gamma': 0.5950977163681339, 'sigma_update': 0.1358747586738585, 'eta_learning': 0.6310765168478065, 'sigma_boundary': 1.9789875957328684, 'alpha': 0.2576627621396542}. Best is trial 0 with value: 0.09291900098219455.
[I 2026-07-01 22:03:58,961] Trial 3 finished with value: 0.11388722249541763 and parameters: {'sigma_noise': 0.44216332964682853, 'A_repulsion': 0.19876785919484746, 'gamma': 0.5496606567532344, 'sigma_update': 0.11209988747342718, 'eta_learning': 0.6660281605276116, 'sigma_boundary': 9.469043245402597, 'alpha': 0.6087678738096705}. Best is trial 0 with value: 0.09291900098219455.
[I 2026-07-01 22:06:13,332] Trial 4 finished with value: 0.6522587189557434 and parameters: {'sigma_noise': 0.4113685825474536, 'A_repulsion': 0.026287693760968123, 'gamma': 0.9423902250678173, 'sigma_update': 0.07200514621890475, 'eta_learning': 0.8927644828019287, 'sigma_boundary': 7.801905612035644, 'alpha': 0.265395331341275}. Best is trial 0 with value: 0.09291900098219455.
[I 2026-07-01 22:08:08,406] Trial 5 finished with value: 0.06810258771686682 and parameters: {'sigma_noise': 0.16223811750247244, 'A_repulsion': 0.23904398873571586, 'gamma': 0.1896154616659259, 'sigma_update': 0.06833875913914035, 'eta_learning': 0.5965238587565677, 'sigma_boundary': 7.9000484349431535, 'alpha': 0.3249140746842085}. Best is trial 5 with value: 0.06810258771686682.
[I 2026-07-01 22:09:54,524] Trial 6 finished with value: 0.04878300359761915 and parameters: {'sigma_noise': 0.2856376173228588, 'A_repulsion': 0.005124619365729943, 'gamma': 0.8263659342490774, 'sigma_update': 0.5059137610156367, 'eta_learning': 0.186235886327391, 'sigma_boundary': 5.268062090462645, 'alpha': 0.9590535762624828}. Best is trial 6 with value: 0.04878300359761915.
[I 2026-07-01 22:12:16,572] Trial 7 finished with value: 0.18495761886898865 and parameters: {'sigma_noise': 0.13791631535468357, 'A_repulsion': 0.4597502378098518, 'gamma': 0.30695984904051493, 'sigma_update': 0.030936483705504315, 'eta_learning': 0.4128121235401722, 'sigma_boundary': 5.445400302506103, 'alpha': 0.8202384808476303}. Best is trial 6 with value: 0.04878300359761915.
[I 2026-07-01 22:14:00,817] Trial 8 finished with value: 0.05493474193187477 and parameters: {'sigma_noise': 0.254513211956344, 'A_repulsion': 0.028885375339675223, 'gamma': 0.2660296925829004, 'sigma_update': 0.36664134287997496, 'eta_learning': 0.2979458415184891, 'sigma_boundary': 5.635151654744328, 'alpha': 0.5365402330536179}. Best is trial 6 with value: 0.04878300359761915.
[I 2026-07-01 22:16:42,140] Trial 9 finished with value: 0.5943075170186559 and parameters: {'sigma_noise': 0.42824183694393003, 'A_repulsion': 0.2541568971192354, 'gamma': 0.5167176213814652, 'sigma_update': 0.3375229907487427, 'eta_learning': 0.6644727315721212, 'sigma_boundary': 7.0399563075468645, 'alpha': 0.30676327687408156}. Best is trial 6 with value: 0.04878300359761915.
[I 2026-07-01 22:19:24,767] Trial 10 finished with value: 0.11142676879422382 and parameters: {'sigma_noise': 0.3230602465952246, 'A_repulsion': 0.4284469378605788, 'gamma': 0.9600597037230895, 'sigma_update': 0.6095365356007312, 'eta_learning': 0.03489439212843576, 'sigma_boundary': 2.412420878685662, 'alpha': 0.009252752344869108}. Best is trial 6 with value: 0.04878300359761915.
[I 2026-07-01 22:21:27,723] Trial 11 finished with value: 0.04392004093720506 and parameters: {'sigma_noise': 0.33341264751952226, 'A_repulsion': 0.09668937676976526, 'gamma': 0.7704367854387265, 'sigma_update': 0.5571217275468114, 'eta_learning': 0.19391881685991363, 'sigma_boundary': 3.8472327990395727, 'alpha': 0.6724251715508237}. Best is trial 11 with value: 0.04392004093720506.
[I 2026-07-01 22:23:33,790] Trial 12 finished with value: 0.05547072211474514 and parameters: {'sigma_noise': 0.34587720235650915, 'A_repulsion': 0.10909710170078371, 'gamma': 0.793967286939011, 'sigma_update': 0.5845242573406834, 'eta_learning': 0.14329050762837126, 'sigma_boundary': 3.5885817245766427, 'alpha': 0.9948876239751794}. Best is trial 11 with value: 0.04392004093720506.
[I 2026-07-01 22:25:39,663] Trial 13 finished with value: 0.04882648883431593 and parameters: {'sigma_noise': 0.3455689906090124, 'A_repulsion': 0.11234960863375829, 'gamma': 0.7453922470728771, 'sigma_update': 0.4952829800880818, 'eta_learning': 0.22774465995036947, 'sigma_boundary': 0.21565408059537017, 'alpha': 0.7402718916707607}. Best is trial 11 with value: 0.04392004093720506.
[I 2026-07-01 22:27:19,806] Trial 14 finished with value: 0.04012235159163557 and parameters: {'sigma_noise': 0.16726397242916663, 'A_repulsion': 0.10309484652006817, 'gamma': 0.7654319353041705, 'sigma_update': 0.6899587265656146, 'eta_learning': 0.39009739145708694, 'sigma_boundary': 3.8775208258822254, 'alpha': 0.6965856640904357}. Best is trial 14 with value: 0.04012235159163557.
[I 2026-07-01 22:29:16,320] Trial 15 finished with value: 0.04558469846536255 and parameters: {'sigma_noise': 0.16033681466489946, 'A_repulsion': 0.33961143911316755, 'gamma': 0.6855659472039781, 'sigma_update': 0.6890270960800843, 'eta_learning': 0.39413059686526397, 'sigma_boundary': 3.5513687607554827, 'alpha': 0.6654168706490279}. Best is trial 14 with value: 0.04012235159163557.
[I 2026-07-01 22:30:44,210] Trial 16 finished with value: 0.060941706012273736 and parameters: {'sigma_noise': 0.09330173203438857, 'A_repulsion': 0.12261102155005715, 'gamma': 0.8545798010994686, 'sigma_update': 0.6972684589069165, 'eta_learning': 0.028171877384412125, 'sigma_boundary': 3.684945860158167, 'alpha': 0.506859333284707}. Best is trial 14 with value: 0.04012235159163557.
[I 2026-07-01 22:32:26,897] Trial 17 finished with value: 0.04177064660833724 and parameters: {'sigma_noise': 0.20262176101832047, 'A_repulsion': 0.08013568165080849, 'gamma': 0.6626549045351998, 'sigma_update': 0.4883950499706965, 'eta_learning': 0.43455755382094924, 'sigma_boundary': 0.9194586814383578, 'alpha': 0.7327005859740192}. Best is trial 14 with value: 0.04012235159163557.
[I 2026-07-01 22:34:15,179] Trial 18 finished with value: 0.05276127142428136 and parameters: {'sigma_noise': 0.19007867759183894, 'A_repulsion': 0.1731839913101728, 'gamma': 0.6271467119215174, 'sigma_update': 0.42387299882027585, 'eta_learning': 0.45262649979303343, 'sigma_boundary': 0.32409517894518514, 'alpha': 0.7833360890150429}. Best is trial 14 with value: 0.04012235159163557.
[I 2026-07-01 22:35:37,784] Trial 19 finished with value: 0.060322177315538454 and parameters: {'sigma_noise': 0.08521969759422687, 'A_repulsion': 0.07249577135914567, 'gamma': 0.42007842011273033, 'sigma_update': 0.23574170640463138, 'eta_learning': 0.5348816294259973, 'sigma_boundary': 1.6813791908945364, 'alpha': 0.43154064175897944}. Best is trial 14 with value: 0.04012235159163557.
[I 2026-07-01 22:37:48,114] Trial 20 finished with value: 0.0583541177347108 and parameters: {'sigma_noise': 0.2099828104175746, 'A_repulsion': 0.360988372372639, 'gamma': 0.6761039128974189, 'sigma_update': 0.6259982494841587, 'eta_learning': 0.786107531476691, 'sigma_boundary': 1.1252468773812954, 'alpha': 0.8854423585125637}. Best is trial 14 with value: 0.04012235159163557.
[I 2026-07-01 22:39:14,191] Trial 21 finished with value: 0.059636384292074004 and parameters: {'sigma_noise': 0.09774296251703204, 'A_repulsion': 0.0756115125009243, 'gamma': 0.8915778901810605, 'sigma_update': 0.5341562141393078, 'eta_learning': 0.2996234487285502, 'sigma_boundary': 4.204652996898185, 'alpha': 0.6794631765652736}. Best is trial 14 with value: 0.04012235159163557.
[I 2026-07-01 22:41:20,499] Trial 22 finished with value: 0.04603862272896965 and parameters: {'sigma_noise': 0.30210112556866686, 'A_repulsion': 0.1509309804126131, 'gamma': 0.707354341416907, 'sigma_update': 0.4201931603256284, 'eta_learning': 0.32649541201076815, 'sigma_boundary': 2.681805062311817, 'alpha': 0.5999062821787959}. Best is trial 14 with value: 0.04012235159163557.
[I 2026-07-01 22:43:25,623] Trial 23 finished with value: 0.04800512732967788 and parameters: {'sigma_noise': 0.37001798320326085, 'A_repulsion': 0.06846876500629431, 'gamma': 0.7828558125571526, 'sigma_update': 0.560778637948136, 'eta_learning': 0.11215257357346368, 'sigma_boundary': 4.463224965563509, 'alpha': 0.7166821576919651}. Best is trial 14 with value: 0.04012235159163557.
[I 2026-07-01 22:45:17,071] Trial 24 finished with value: 0.03770967780382931 and parameters: {'sigma_noise': 0.2303346417242322, 'A_repulsion': 0.1322131729952376, 'gamma': 0.999216263953022, 'sigma_update': 0.637788987236999, 'eta_learning': 0.5114556103665931, 'sigma_boundary': 6.390665477816462, 'alpha': 0.5939376726424954}. Best is trial 24 with value: 0.03770967780382931.
[I 2026-07-01 22:47:07,366] Trial 25 finished with value: 0.10076376786132685 and parameters: {'sigma_noise': 0.21868582004461756, 'A_repulsion': 0.14917366624774991, 'gamma': 0.991860407377563, 'sigma_update': 0.6515862450721177, 'eta_learning': 0.5314632319703579, 'sigma_boundary': 6.0565358942022645, 'alpha': 0.4187383397890697}. Best is trial 24 with value: 0.03770967780382931.
[I 2026-07-01 22:48:51,136] Trial 26 finished with value: 0.04423206996389769 and parameters: {'sigma_noise': 0.13481235292990548, 'A_repulsion': 0.22211383275214655, 'gamma': 0.8694625361819568, 'sigma_update': 0.6501093994855225, 'eta_learning': 0.48951276828749607, 'sigma_boundary': 6.2373083389651836, 'alpha': 0.5800467400200495}. Best is trial 24 with value: 0.03770967780382931.
[I 2026-07-01 22:50:28,571] Trial 27 finished with value: 0.05147448371247972 and parameters: {'sigma_noise': 0.18405180829503925, 'A_repulsion': 0.05115288089287834, 'gamma': 0.9268763617599508, 'sigma_update': 0.43002401764895515, 'eta_learning': 0.9900162341308334, 'sigma_boundary': 6.956296979109644, 'alpha': 0.8397791826300245}. Best is trial 24 with value: 0.03770967780382931.
[I 2026-07-01 22:52:22,835] Trial 28 finished with value: 0.04695618129857347 and parameters: {'sigma_noise': 0.24125165750082656, 'A_repulsion': 0.1430497585097001, 'gamma': 0.6257362262776277, 'sigma_update': 0.46942740554769546, 'eta_learning': 0.3660235505100883, 'sigma_boundary': 0.9082452340692615, 'alpha': 0.4915609934091736}. Best is trial 24 with value: 0.03770967780382931.
[I 2026-07-01 22:53:52,213] Trial 29 finished with value: 0.11299070839769355 and parameters: {'sigma_noise': 0.04331310754981445, 'A_repulsion': 0.28392750682969325, 'gamma': 0.3945660847091773, 'sigma_update': 0.6001225473114518, 'eta_learning': 0.5534360005577327, 'sigma_boundary': 4.564287900252425, 'alpha': 0.11745500118938218}. Best is trial 24 with value: 0.03770967780382931.
[I 2026-07-01 22:55:46,181] Trial 30 finished with value: 0.05276179804362061 and parameters: {'sigma_noise': 0.21286857751027843, 'A_repulsion': 0.1919670178547449, 'gamma': 0.49001820125525697, 'sigma_update': 0.32047438387836225, 'eta_learning': 0.7391635028921044, 'sigma_boundary': 9.931742907122388, 'alpha': 0.7533491801062728}. Best is trial 24 with value: 0.03770967780382931.
[I 2026-07-01 22:57:58,457] Trial 31 finished with value: 0.06019544046544148 and parameters: {'sigma_noise': 0.39022070048485724, 'A_repulsion': 0.09207261101586628, 'gamma': 0.7605081228422815, 'sigma_update': 0.5605341795286923, 'eta_learning': 0.4531185080205125, 'sigma_boundary': 2.744476201060415, 'alpha': 0.6524085268873884}. Best is trial 24 with value: 0.03770967780382931.
[I 2026-07-01 22:59:42,785] Trial 32 finished with value: 0.03719547204798698 and parameters: {'sigma_noise': 0.24018466924156473, 'A_repulsion': 0.041188491242246585, 'gamma': 0.7169316188301791, 'sigma_update': 0.6590972868335805, 'eta_learning': 0.2401777545209403, 'sigma_boundary': 6.522116844463895, 'alpha': 0.702374026543645}. Best is trial 32 with value: 0.03719547204798698.
[I 2026-07-01 23:01:29,926] Trial 33 finished with value: 0.044964406617211045 and parameters: {'sigma_noise': 0.2604113220596005, 'A_repulsion': 0.03265601497602348, 'gamma': 0.5856679883447354, 'sigma_update': 0.6473323244162065, 'eta_learning': 0.3411805214607727, 'sigma_boundary': 6.771059504237088, 'alpha': 0.8790261940606856}. Best is trial 32 with value: 0.03719547204798698.
[I 2026-07-01 23:03:16,234] Trial 34 finished with value: 0.0416341779439488 and parameters: {'sigma_noise': 0.23293210190941638, 'A_repulsion': 0.054481303012207494, 'gamma': 0.6641428301202771, 'sigma_update': 0.6887531656914729, 'eta_learning': 0.2623013478002584, 'sigma_boundary': 8.947194665953852, 'alpha': 0.5739069651712584}. Best is trial 32 with value: 0.03719547204798698.
[I 2026-07-01 23:04:56,912] Trial 35 finished with value: 0.09919752925447578 and parameters: {'sigma_noise': 0.23374754204318965, 'A_repulsion': 0.0012006615028718332, 'gamma': 0.012966144336098606, 'sigma_update': 0.6856842035944225, 'eta_learning': 0.2440736095030936, 'sigma_boundary': 8.831208650925978, 'alpha': 0.4395349138877282}. Best is trial 32 with value: 0.03719547204798698.
[I 2026-07-01 23:06:48,199] Trial 36 finished with value: 0.03683309367806614 and parameters: {'sigma_noise': 0.2835754969694522, 'A_repulsion': 0.04904425542745269, 'gamma': 0.9969090802989231, 'sigma_update': 0.660710104016506, 'eta_learning': 0.10640593964266676, 'sigma_boundary': 8.56107400849454, 'alpha': 0.589618868087848}. Best is trial 36 with value: 0.03683309367806614.
[I 2026-07-01 23:08:38,827] Trial 37 finished with value: 0.039610689317168046 and parameters: {'sigma_noise': 0.2921541857423611, 'A_repulsion': 0.04083047639679971, 'gamma': 0.9986160465779705, 'sigma_update': 0.6400634151967356, 'eta_learning': 0.09410946894732275, 'sigma_boundary': 8.190848343989513, 'alpha': 0.6367948124195043}. Best is trial 36 with value: 0.03683309367806614.
[I 2026-07-01 23:10:29,052] Trial 38 finished with value: 0.04922783589422042 and parameters: {'sigma_noise': 0.2881593548889006, 'A_repulsion': 0.04146977647989856, 'gamma': 0.9197121372336082, 'sigma_update': 0.18745458536956106, 'eta_learning': 0.09187336457906187, 'sigma_boundary': 7.673572910159873, 'alpha': 0.6236722548675058}. Best is trial 36 with value: 0.03683309367806614.
[I 2026-07-01 23:12:16,336] Trial 39 finished with value: 0.03097430383682502 and parameters: {'sigma_noise': 0.2762722916247949, 'A_repulsion': 0.025733961991008664, 'gamma': 0.9717984300167513, 'sigma_update': 0.638536929458431, 'eta_learning': 0.06507857768550246, 'sigma_boundary': 8.26220744552508, 'alpha': 0.37530627896753066}. Best is trial 39 with value: 0.03097430383682502.
[I 2026-07-01 23:14:06,403] Trial 40 finished with value: 0.08296529419885962 and parameters: {'sigma_noise': 0.3148470329665502, 'A_repulsion': 0.0048819022445100585, 'gamma': 0.1002066005057799, 'sigma_update': 0.5213725886085863, 'eta_learning': 0.16077729593253748, 'sigma_boundary': 7.442245256647296, 'alpha': 0.37435500543429634}. Best is trial 39 with value: 0.03097430383682502.
[I 2026-07-01 23:15:53,577] Trial 41 finished with value: 0.03213630061783558 and parameters: {'sigma_noise': 0.27754935540606174, 'A_repulsion': 0.030492725365842112, 'gamma': 0.9953639749859519, 'sigma_update': 0.6321329918686689, 'eta_learning': 0.08338232438084833, 'sigma_boundary': 8.406207832903403, 'alpha': 0.22256408092887736}. Best is trial 39 with value: 0.03097430383682502.
[I 2026-07-01 23:17:41,614] Trial 42 finished with value: 0.030730687137336652 and parameters: {'sigma_noise': 0.28207239362691205, 'A_repulsion': 0.02716164530406901, 'gamma': 0.8376580792436901, 'sigma_update': 0.5904364696544291, 'eta_learning': 0.05072786876715342, 'sigma_boundary': 8.914408727852006, 'alpha': 0.22445304800711163}. Best is trial 42 with value: 0.030730687137336652.
[I 2026-07-01 23:19:27,385] Trial 43 finished with value: 0.03126545955200847 and parameters: {'sigma_noise': 0.27371171158955243, 'A_repulsion': 0.018027936164522994, 'gamma': 0.8248807155956412, 'sigma_update': 0.6033330763056034, 'eta_learning': 0.06393977026151185, 'sigma_boundary': 8.841854530165007, 'alpha': 0.20677570876856655}. Best is trial 42 with value: 0.030730687137336652.
[I 2026-07-01 23:21:16,129] Trial 44 finished with value: 0.029668345820185196 and parameters: {'sigma_noise': 0.28372080341383027, 'A_repulsion': 0.02423661341601019, 'gamma': 0.8393766813980459, 'sigma_update': 0.58707031244834, 'eta_learning': 0.04092675358212884, 'sigma_boundary': 8.799131619608946, 'alpha': 0.17369296056027195}. Best is trial 44 with value: 0.029668345820185196.
[I 2026-07-01 23:23:02,687] Trial 45 finished with value: 0.03364794606336698 and parameters: {'sigma_noise': 0.2690086913418366, 'A_repulsion': 0.00891096930004027, 'gamma': 0.8246620378524986, 'sigma_update': 0.5917560216986838, 'eta_learning': 0.08607102418819193, 'sigma_boundary': 9.221638270192845, 'alpha': 0.1949264522965038}. Best is trial 44 with value: 0.029668345820185196.
[I 2026-07-01 23:24:52,889] Trial 46 finished with value: 0.03173544240374642 and parameters: {'sigma_noise': 0.31099090925534295, 'A_repulsion': 0.017461649318654772, 'gamma': 0.8990620704764173, 'sigma_update': 0.5724622248683965, 'eta_learning': 0.035131138358614034, 'sigma_boundary': 9.720967074325308, 'alpha': 0.20188660666882913}. Best is trial 44 with value: 0.029668345820185196.
[I 2026-07-01 23:26:47,649] Trial 47 finished with value: 0.03575966140971084 and parameters: {'sigma_noise': 0.36323156033530646, 'A_repulsion': 0.0006303119537487377, 'gamma': 0.833103360247346, 'sigma_update': 0.5467889000633281, 'eta_learning': 0.015130147094502232, 'sigma_boundary': 9.884623720318249, 'alpha': 0.13546723391714588}. Best is trial 44 with value: 0.029668345820185196.
[I 2026-07-01 23:28:37,874] Trial 48 finished with value: 0.03311947167007362 and parameters: {'sigma_noise': 0.3105920269874595, 'A_repulsion': 0.01845031997443797, 'gamma': 0.8981029021607521, 'sigma_update': 0.5702460048026149, 'eta_learning': 0.03992847636160457, 'sigma_boundary': 9.535523925493019, 'alpha': 0.2920380703611535}. Best is trial 44 with value: 0.029668345820185196.
[I 2026-07-01 23:30:34,922] Trial 49 finished with value: 0.1775039287307988 and parameters: {'sigma_noise': 0.3269600714721795, 'A_repulsion': 0.06084722472018515, 'gamma': 0.9536512481406378, 'sigma_update': 0.46754107046093674, 'eta_learning': 0.18542772327309892, 'sigma_boundary': 9.242986044662732, 'alpha': 0.03458824152484338}. Best is trial 44 with value: 0.029668345820185196.
[I 2026-07-01 23:32:27,506] Trial 50 finished with value: 0.030337173802102203 and parameters: {'sigma_noise': 0.26351414013187474, 'A_repulsion': 0.09146681943265303, 'gamma': 0.8322338260480684, 'sigma_update': 0.605993925365272, 'eta_learning': 0.049642599305198626, 'sigma_boundary': 7.322231998197029, 'alpha': 0.16197345949716005}. Best is trial 44 with value: 0.029668345820185196.

==============================
Running variant: Hybrid_alpha0_BE
==============================

--- Repetition 1/1, Fold 1/2 ---

[I 2026-07-02 04:00:10,956] A new study created in memory with name: no-name-fc09ed16-2cc5-4924-8fa4-9a1bc2e2140d
[I 2026-07-02 04:01:46,796] Trial 0 finished with value: 0.4642812994441634 and parameters: {'sigma_noise': 0.08159018215585934, 'A_repulsion': 0.37739043882567497, 'eta_learning': 0.5677678301612995, 'sigma_boundary': 2.2603914995438967}. Best is trial 0 with value: 0.4642812994441634.
[I 2026-07-02 04:03:15,963] Trial 1 finished with value: 0.08882224852242503 and parameters: {'sigma_noise': 0.16015518523419017, 'A_repulsion': 0.0762456134605396, 'eta_learning': 0.3517393035221001, 'sigma_boundary': 0.42633209995629456}. Best is trial 1 with value: 0.08882224852242503.
[I 2026-07-02 04:04:53,682] Trial 2 finished with value: 0.6801376191610515 and parameters: {'sigma_noise': 0.11909376460804462, 'A_repulsion': 0.2998864037784978, 'eta_learning': 0.9712617163345879, 'sigma_boundary': 7.023618694914987}. Best is trial 1 with value: 0.08882224852242503.
[I 2026-07-02 04:06:49,578] Trial 3 finished with value: 0.7985735736439772 and parameters: {'sigma_noise': 0.3267775293777396, 'A_repulsion': 0.09880909744250538, 'eta_learning': 0.5008435317223655, 'sigma_boundary': 2.1018301929518968}. Best is trial 1 with value: 0.08882224852242503.
[I 2026-07-02 04:09:28,564] Trial 4 finished with value: 0.42941100747208943 and parameters: {'sigma_noise': 0.3574582734868774, 'A_repulsion': 0.40919430081607444, 'eta_learning': 0.1411806041584652, 'sigma_boundary': 9.26022671518514}. Best is trial 1 with value: 0.08882224852242503.
[I 2026-07-02 04:10:53,760] Trial 5 finished with value: 0.0326749906638734 and parameters: {'sigma_noise': 0.04936763428732499, 'A_repulsion': 0.2746590027338448, 'eta_learning': 0.09086713200888086, 'sigma_boundary': 4.610328204003842}. Best is trial 5 with value: 0.0326749906638734.
[I 2026-07-02 04:12:40,435] Trial 6 finished with value: 0.663656957076298 and parameters: {'sigma_noise': 0.17940623902781755, 'A_repulsion': 0.24433360359810447, 'eta_learning': 0.47918166793129985, 'sigma_boundary': 2.5871382402701117}. Best is trial 5 with value: 0.0326749906638734.
[I 2026-07-02 04:15:06,620] Trial 7 finished with value: 0.8964952639831871 and parameters: {'sigma_noise': 0.4481755238991748, 'A_repulsion': 0.19224766240446378, 'eta_learning': 0.43624790131316343, 'sigma_boundary': 9.165706358414651}. Best is trial 5 with value: 0.0326749906638734.
[I 2026-07-02 04:18:10,975] Trial 8 finished with value: 0.9063419475359134 and parameters: {'sigma_noise': 0.4205988166956639, 'A_repulsion': 0.48267417324344636, 'eta_learning': 0.5299969500627982, 'sigma_boundary': 8.980488092706864}. Best is trial 5 with value: 0.0326749906638734.
[I 2026-07-02 04:20:15,094] Trial 9 finished with value: 0.8887380816552982 and parameters: {'sigma_noise': 0.2434816178733748, 'A_repulsion': 0.3012709148892999, 'eta_learning': 0.7138351848729305, 'sigma_boundary': 9.869860135285233}. Best is trial 5 with value: 0.0326749906638734.
[I 2026-07-02 04:21:20,805] Trial 10 finished with value: 0.054958934962127136 and parameters: {'sigma_noise': 0.03223326075523472, 'A_repulsion': 0.014965546694533177, 'eta_learning': 0.0296359583001155, 'sigma_boundary': 5.188627214833757}. Best is trial 5 with value: 0.0326749906638734.
[I 2026-07-02 04:22:30,422] Trial 11 finished with value: 0.06998895503474054 and parameters: {'sigma_noise': 0.010786795030699882, 'A_repulsion': 0.15442159483666734, 'eta_learning': 0.015647286836952552, 'sigma_boundary': 5.1489519114163995}. Best is trial 5 with value: 0.0326749906638734.
[I 2026-07-02 04:23:34,661] Trial 12 finished with value: 0.04170070812727747 and parameters: {'sigma_noise': 0.02103330016162034, 'A_repulsion': 0.023372799952104378, 'eta_learning': 0.19560978303068954, 'sigma_boundary': 5.301778103019326}. Best is trial 5 with value: 0.0326749906638734.
[I 2026-07-02 04:24:46,309] Trial 13 finished with value: 0.03796477126110864 and parameters: {'sigma_noise': 0.0808013354415905, 'A_repulsion': 0.011866364908733135, 'eta_learning': 0.23954160731205215, 'sigma_boundary': 6.839747588549498}. Best is trial 5 with value: 0.0326749906638734.
[I 2026-07-02 04:26:16,768] Trial 14 finished with value: 0.06836518482871505 and parameters: {'sigma_noise': 0.09547140252894121, 'A_repulsion': 0.21140743341282522, 'eta_learning': 0.25412384430064927, 'sigma_boundary': 7.120542107452215}. Best is trial 5 with value: 0.0326749906638734.
[I 2026-07-02 04:28:18,499] Trial 15 finished with value: 0.5200257022294434 and parameters: {'sigma_noise': 0.22237014017161533, 'A_repulsion': 0.3133639835296824, 'eta_learning': 0.2863405173827279, 'sigma_boundary': 7.20354996295209}. Best is trial 5 with value: 0.0326749906638734.
[I 2026-07-02 04:29:37,434] Trial 16 finished with value: 0.028545869446624156 and parameters: {'sigma_noise': 0.06701819912444502, 'A_repulsion': 0.1413096259280565, 'eta_learning': 0.10918019822492844, 'sigma_boundary': 3.7340146659025644}. Best is trial 16 with value: 0.028545869446624156.
[I 2026-07-02 04:31:10,009] Trial 17 finished with value: 0.044684146853810905 and parameters: {'sigma_noise': 0.15468115000452815, 'A_repulsion': 0.13104640613821839, 'eta_learning': 0.12065146914162098, 'sigma_boundary': 3.7999781090783724}. Best is trial 16 with value: 0.028545869446624156.
[I 2026-07-02 04:32:58,991] Trial 18 finished with value: 0.808375988484923 and parameters: {'sigma_noise': 0.23571538113044888, 'A_repulsion': 0.1769908958006113, 'eta_learning': 0.6950424910706555, 'sigma_boundary': 3.7218354061210395}. Best is trial 16 with value: 0.028545869446624156.
[I 2026-07-02 04:34:28,767] Trial 19 finished with value: 0.11650060831133144 and parameters: {'sigma_noise': 0.05248013190429232, 'A_repulsion': 0.36212034030923734, 'eta_learning': 0.3532807790072278, 'sigma_boundary': 3.666490418282812}. Best is trial 16 with value: 0.028545869446624156.
[I 2026-07-02 04:36:34,864] Trial 20 finished with value: 0.19853610292953006 and parameters: {'sigma_noise': 0.2899394241936973, 'A_repulsion': 0.24263437924460496, 'eta_learning': 0.0809182577674129, 'sigma_boundary': 0.5295826996398025}. Best is trial 16 with value: 0.028545869446624156.
[I 2026-07-02 04:37:50,307] Trial 21 finished with value: 0.03418417324440105 and parameters: {'sigma_noise': 0.07134619113389574, 'A_repulsion': 0.0795234527694251, 'eta_learning': 0.1900941697129927, 'sigma_boundary': 6.114578082082733}. Best is trial 16 with value: 0.028545869446624156.
[I 2026-07-02 04:39:13,731] Trial 22 finished with value: 0.03536215772237709 and parameters: {'sigma_noise': 0.12825906874015566, 'A_repulsion': 0.0677909368389821, 'eta_learning': 0.14918747155556655, 'sigma_boundary': 6.195755602678515}. Best is trial 16 with value: 0.028545869446624156.
[I 2026-07-02 04:40:31,051] Trial 23 finished with value: 0.06440733685489582 and parameters: {'sigma_noise': 0.06824608193871398, 'A_repulsion': 0.12097276546748026, 'eta_learning': 0.33884176447512115, 'sigma_boundary': 4.1725215857595535}. Best is trial 16 with value: 0.028545869446624156.
[I 2026-07-02 04:42:05,813] Trial 24 finished with value: 0.0654172488515028 and parameters: {'sigma_noise': 0.1180536310757136, 'A_repulsion': 0.22000129297052243, 'eta_learning': 0.19902504944649335, 'sigma_boundary': 6.123421318035104}. Best is trial 16 with value: 0.028545869446624156.
[I 2026-07-02 04:43:47,005] Trial 25 finished with value: 0.059597677574636916 and parameters: {'sigma_noise': 0.19724548416441265, 'A_repulsion': 0.15494809776555488, 'eta_learning': 0.09475264744479261, 'sigma_boundary': 2.9156561415369397}. Best is trial 16 with value: 0.028545869446624156.
[I 2026-07-02 04:44:57,450] Trial 26 finished with value: 0.019100571625684543 and parameters: {'sigma_noise': 0.04891958929906114, 'A_repulsion': 0.051727801600827905, 'eta_learning': 0.016550524205673323, 'sigma_boundary': 1.4898917558089062}. Best is trial 26 with value: 0.019100571625684543.
[I 2026-07-02 04:46:19,376] Trial 27 finished with value: 0.03590446715211954 and parameters: {'sigma_noise': 0.038801938454700424, 'A_repulsion': 0.2879741850661989, 'eta_learning': 0.015842232260846884, 'sigma_boundary': 1.8109876863826644}. Best is trial 26 with value: 0.019100571625684543.
[I 2026-07-02 04:47:42,772] Trial 28 finished with value: 0.018264054946412964 and parameters: {'sigma_noise': 0.1393092826396361, 'A_repulsion': 0.0490275224231807, 'eta_learning': 0.0687340513884153, 'sigma_boundary': 1.0715231205348408}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 04:49:01,486] Trial 29 finished with value: 0.1431504825455815 and parameters: {'sigma_noise': 0.10395684105007896, 'A_repulsion': 0.056040024739481754, 'eta_learning': 0.611509789453889, 'sigma_boundary': 1.081840069744748}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 04:50:26,980] Trial 30 finished with value: 0.44644591725227645 and parameters: {'sigma_noise': 0.1525707042391278, 'A_repulsion': 0.045798445933859566, 'eta_learning': 0.9619047516521761, 'sigma_boundary': 1.371018486353079}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 04:51:42,841] Trial 31 finished with value: 0.029463232436618775 and parameters: {'sigma_noise': 0.05520537732148171, 'A_repulsion': 0.10755904538276449, 'eta_learning': 0.06771557524554732, 'sigma_boundary': 2.9420487129286315}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 04:53:04,226] Trial 32 finished with value: 0.023632852946734367 and parameters: {'sigma_noise': 0.08945418429243972, 'A_repulsion': 0.11003947396648753, 'eta_learning': 0.05874043632355823, 'sigma_boundary': 3.2905580221088817}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 04:54:27,677] Trial 33 finished with value: 0.03885273981583577 and parameters: {'sigma_noise': 0.14073379374990788, 'A_repulsion': 0.04287130412153062, 'eta_learning': 0.16850597489513847, 'sigma_boundary': 1.0287511230481492}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 04:55:48,448] Trial 34 finished with value: 0.17939578388250582 and parameters: {'sigma_noise': 0.0983723201009999, 'A_repulsion': 0.09574750430251651, 'eta_learning': 0.06142973367905316, 'sigma_boundary': 0.1295234515689332}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 04:57:27,838] Trial 35 finished with value: 0.2916097352491484 and parameters: {'sigma_noise': 0.18705335420278915, 'A_repulsion': 0.13425999008581363, 'eta_learning': 0.31563620024010286, 'sigma_boundary': 1.7540831332888174}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 04:58:50,079] Trial 36 finished with value: 0.14326605954668853 and parameters: {'sigma_noise': 0.11676949237823589, 'A_repulsion': 0.0796672728819599, 'eta_learning': 0.41181868427797447, 'sigma_boundary': 3.1839245371971696}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 05:00:09,187] Trial 37 finished with value: 0.02663414854846236 and parameters: {'sigma_noise': 0.06711734029738836, 'A_repulsion': 0.15872892000441602, 'eta_learning': 0.12928019862040446, 'sigma_boundary': 2.2937867279079063}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 05:01:21,662] Trial 38 finished with value: 0.03317416397476201 and parameters: {'sigma_noise': 0.08823842756546502, 'A_repulsion': 0.0009605468579624299, 'eta_learning': 0.22616336102625034, 'sigma_boundary': 2.2938986075510353}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 05:03:00,562] Trial 39 finished with value: 0.08762358891828044 and parameters: {'sigma_noise': 0.1692981667859493, 'A_repulsion': 0.17752361234110592, 'eta_learning': 0.13886490582196945, 'sigma_boundary': 0.8541957355366794}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 05:04:39,125] Trial 40 finished with value: 0.6853925483129528 and parameters: {'sigma_noise': 0.20477492430822714, 'A_repulsion': 0.1038038324396888, 'eta_learning': 0.9156010625993163, 'sigma_boundary': 2.3252064510049837}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 05:05:57,290] Trial 41 finished with value: 0.021212124037079068 and parameters: {'sigma_noise': 0.0616968825395037, 'A_repulsion': 0.15353474214296986, 'eta_learning': 0.11014140738818647, 'sigma_boundary': 1.5877234028723368}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 05:07:05,313] Trial 42 finished with value: 0.025521407709507317 and parameters: {'sigma_noise': 0.03422300234709935, 'A_repulsion': 0.03683400152144148, 'eta_learning': 0.05330809624817149, 'sigma_boundary': 1.7219196431214534}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 05:08:10,393] Trial 43 finished with value: 0.02499492627091592 and parameters: {'sigma_noise': 0.02440903156170897, 'A_repulsion': 0.029474432945860274, 'eta_learning': 0.03435902378340483, 'sigma_boundary': 1.5865250911031723}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 05:09:16,541] Trial 44 finished with value: 0.028615581314175527 and parameters: {'sigma_noise': 0.012854233175810581, 'A_repulsion': 0.0738739673507225, 'eta_learning': 0.024556299484192017, 'sigma_boundary': 0.3508910611471716}. Best is trial 28 with value: 0.018264054946412964.
[I 2026-07-02 05:10:23,093] Trial 45 finished with value: 0.017922730246306237 and parameters: {'sigma_noise': 0.03579108836164098, 'A_repulsion': 0.025246398565739805, 'eta_learning': 0.012391052879386247, 'sigma_boundary': 1.3783321929895747}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:12:08,340] Trial 46 finished with value: 0.10272538069087746 and parameters: {'sigma_noise': 0.2610024847111865, 'A_repulsion': 0.09535836497382073, 'eta_learning': 0.09051767986741294, 'sigma_boundary': 0.7334106764664536}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:13:41,986] Trial 47 finished with value: 0.038601438905146696 and parameters: {'sigma_noise': 0.04337427702525359, 'A_repulsion': 0.49547925574905927, 'eta_learning': 0.010804712767539498, 'sigma_boundary': 1.2802660720979127}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:15:05,865] Trial 48 finished with value: 0.3223426934569387 and parameters: {'sigma_noise': 0.13291923707441855, 'A_repulsion': 0.06359642066614297, 'eta_learning': 0.27793543907204515, 'sigma_boundary': 0.0728443512901269}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:16:19,043] Trial 49 finished with value: 0.026201433510298466 and parameters: {'sigma_noise': 0.08710211149680314, 'A_repulsion': 0.019399718238171042, 'eta_learning': 0.1635748902403523, 'sigma_boundary': 2.037134171660011}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:17:34,843] Trial 50 finished with value: 0.023933339805762177 and parameters: {'sigma_noise': 0.11136597160778966, 'A_repulsion': 0.0006170434785115961, 'eta_learning': 0.1041116053241753, 'sigma_boundary': 2.821072071402297}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:18:44,577] Trial 51 finished with value: 0.02842322063641003 and parameters: {'sigma_noise': 0.05431148798357964, 'A_repulsion': 0.052950782398663555, 'eta_learning': 0.0676215083552599, 'sigma_boundary': 2.5590809255965308}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:20:34,156] Trial 52 finished with value: 0.1416631326505607 and parameters: {'sigma_noise': 0.374136994344774, 'A_repulsion': 0.003645877659201426, 'eta_learning': 0.10945769352569347, 'sigma_boundary': 3.330590677700104}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:21:52,925] Trial 53 finished with value: 0.041702905924717384 and parameters: {'sigma_noise': 0.11716404858067898, 'A_repulsion': 0.030911904559607573, 'eta_learning': 0.21873511482215646, 'sigma_boundary': 1.3736733759607689}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:23:41,836] Trial 54 finished with value: 0.02985893596519435 and parameters: {'sigma_noise': 0.1036767544795435, 'A_repulsion': 0.45330158535718407, 'eta_learning': 0.050584310879822535, 'sigma_boundary': 4.30048597166087}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:24:59,288] Trial 55 finished with value: 0.22424620625988553 and parameters: {'sigma_noise': 0.0810611954888239, 'A_repulsion': 0.08233942503058404, 'eta_learning': 0.8364435213986585, 'sigma_boundary': 2.708778179217288}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:26:29,225] Trial 56 finished with value: 0.054084578141909936 and parameters: {'sigma_noise': 0.14123115287183902, 'A_repulsion': 0.11643180753869017, 'eta_learning': 0.16798830338969295, 'sigma_boundary': 0.48342975534297405}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:27:39,579] Trial 57 finished with value: 0.023980872014164965 and parameters: {'sigma_noise': 0.05536958825883388, 'A_repulsion': 0.01488067685470812, 'eta_learning': 0.11264327557884561, 'sigma_boundary': 2.0189772572513016}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:28:47,037] Trial 58 finished with value: 0.04079239259755789 and parameters: {'sigma_noise': 0.02896845472041281, 'A_repulsion': 0.05505185913847266, 'eta_learning': 0.2572052889326527, 'sigma_boundary': 8.144975026922872}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:30:00,296] Trial 59 finished with value: 0.02684808735615937 and parameters: {'sigma_noise': 0.07516623790290045, 'A_repulsion': 0.03590409492886214, 'eta_learning': 0.08940400574805987, 'sigma_boundary': 3.2297169250131854}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:31:54,096] Trial 60 finished with value: 0.026231887858769964 and parameters: {'sigma_noise': 0.17030731879169922, 'A_repulsion': 0.34974550406604055, 'eta_learning': 0.01133315169780447, 'sigma_boundary': 4.517761011454399}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:33:02,875] Trial 61 finished with value: 0.024384762164351207 and parameters: {'sigma_noise': 0.054860323613682344, 'A_repulsion': 0.017232098315764992, 'eta_learning': 0.1391475358640306, 'sigma_boundary': 1.991495586162586}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:34:10,114] Trial 62 finished with value: 0.01928985476086953 and parameters: {'sigma_noise': 0.0424408020564074, 'A_repulsion': 0.006720195567314386, 'eta_learning': 0.10642872824019192, 'sigma_boundary': 1.4467602140728881}. Best is trial 45 with value: 0.017922730246306237.
[I 2026-07-02 05:35:16,347] Trial 63 finished with value: 0.012801201268919992 and parameters: {'sigma_noise': 0.012383465804705646, 'A_repulsion': 0.08934237714147247, 'eta_learning': 0.19258784111155938, 'sigma_boundary': 0.7573848333806642}. Best is trial 63 with value: 0.012801201268919992.
[I 2026-07-02 05:36:24,245] Trial 64 finished with value: 0.010868313590876272 and parameters: {'sigma_noise': 0.020228644503161808, 'A_repulsion': 0.08930595530428698, 'eta_learning': 0.05287971445876508, 'sigma_boundary': 0.7195137410775165}. Best is trial 64 with value: 0.010868313590876272.
[I 2026-07-02 05:37:31,315] Trial 65 finished with value: 0.013541313926736106 and parameters: {'sigma_noise': 0.012390620467308065, 'A_repulsion': 0.08840518646790535, 'eta_learning': 0.18661776252920853, 'sigma_boundary': 0.8120360186411192}. Best is trial 64 with value: 0.010868313590876272.
[I 2026-07-02 05:38:38,136] Trial 66 finished with value: 0.012255575948266198 and parameters: {'sigma_noise': 0.013292167305455429, 'A_repulsion': 0.0930032440244153, 'eta_learning': 0.19797339227643745, 'sigma_boundary': 0.7215038952071255}. Best is trial 64 with value: 0.010868313590876272.

--- Repetition 1/1, Fold 2/2 ---

[I 2026-07-02 08:26:26,527] A new study created in memory with name: no-name-737db451-27f7-48b0-a7d1-6f7333e25892
[I 2026-07-02 08:28:20,541] Trial 0 finished with value: 0.6928765012391387 and parameters: {'sigma_noise': 0.23130453864636627, 'A_repulsion': 0.18301128532134425, 'eta_learning': 0.452841141347309, 'sigma_boundary': 3.625248493571174}. Best is trial 0 with value: 0.6928765012391387.
[I 2026-07-02 08:30:34,510] Trial 1 finished with value: 0.40501127036648765 and parameters: {'sigma_noise': 0.2896830130226404, 'A_repulsion': 0.26985879734803747, 'eta_learning': 0.35513063031140035, 'sigma_boundary': 0.17367317815512254}. Best is trial 1 with value: 0.40501127036648765.
[I 2026-07-02 08:32:13,719] Trial 2 finished with value: 0.049330111484760034 and parameters: {'sigma_noise': 0.2482563016050371, 'A_repulsion': 0.01307051444869517, 'eta_learning': 0.10747910049641866, 'sigma_boundary': 8.469681924782693}. Best is trial 2 with value: 0.049330111484760034.
[I 2026-07-02 08:35:06,186] Trial 3 finished with value: 0.9171146095634967 and parameters: {'sigma_noise': 0.37527668163972994, 'A_repulsion': 0.4418781743877959, 'eta_learning': 0.5936713489700887, 'sigma_boundary': 0.31767675031089376}. Best is trial 2 with value: 0.049330111484760034.
[I 2026-07-02 08:36:56,235] Trial 4 finished with value: 0.7583687418539997 and parameters: {'sigma_noise': 0.27004342949694843, 'A_repulsion': 0.09121359324192646, 'eta_learning': 0.6310765168478065, 'sigma_boundary': 1.9789875957328684}. Best is trial 2 with value: 0.049330111484760034.
[I 2026-07-02 08:38:52,883] Trial 5 finished with value: 0.6170827839518129 and parameters: {'sigma_noise': 0.12337161534144786, 'A_repulsion': 0.49109469278048695, 'eta_learning': 0.40356036120579797, 'sigma_boundary': 5.455666627237184}. Best is trial 2 with value: 0.049330111484760034.
[I 2026-07-02 08:40:28,037] Trial 6 finished with value: 0.4922545065073777 and parameters: {'sigma_noise': 0.07510717462073618, 'A_repulsion': 0.33132735380182404, 'eta_learning': 0.9473826639588159, 'sigma_boundary': 6.091591059358608}. Best is trial 2 with value: 0.049330111484760034.
[I 2026-07-02 08:42:28,670] Trial 7 finished with value: 0.8549923676332749 and parameters: {'sigma_noise': 0.4113685825474536, 'A_repulsion': 0.026287693760968123, 'eta_learning': 0.9423902250678173, 'sigma_boundary': 0.9077266822128384}. Best is trial 2 with value: 0.049330111484760034.
[I 2026-07-02 08:45:16,956] Trial 8 finished with value: 0.9104711363127875 and parameters: {'sigma_noise': 0.40233977013419053, 'A_repulsion': 0.38998526586764987, 'eta_learning': 0.2727413780278623, 'sigma_boundary': 3.466497258749317}. Best is trial 2 with value: 0.049330111484760034.
[I 2026-07-02 08:47:00,203] Trial 9 finished with value: 0.045410974297168186 and parameters: {'sigma_noise': 0.22035871008742997, 'A_repulsion': 0.09071487962925551, 'eta_learning': 0.09370343702572312, 'sigma_boundary': 5.9285589383617285}. Best is trial 9 with value: 0.045410974297168186.
[I 2026-07-02 08:48:35,742] Trial 10 finished with value: 0.044857569118091946 and parameters: {'sigma_noise': 0.14574066016644016, 'A_repulsion': 0.15961320786779631, 'eta_learning': 0.14854906742184681, 'sigma_boundary': 9.945083428327376}. Best is trial 10 with value: 0.044857569118091946.
[I 2026-07-02 08:50:10,387] Trial 11 finished with value: 0.028358938245503725 and parameters: {'sigma_noise': 0.13920889542549425, 'A_repulsion': 0.15678894017698886, 'eta_learning': 0.019160224821420435, 'sigma_boundary': 9.600020361295279}. Best is trial 11 with value: 0.028358938245503725.
[I 2026-07-02 08:51:49,816] Trial 12 finished with value: 0.02803179614306038 and parameters: {'sigma_noise': 0.14530094414495298, 'A_repulsion': 0.19359388290164065, 'eta_learning': 0.012137938340453621, 'sigma_boundary': 9.657894678096234}. Best is trial 12 with value: 0.02803179614306038.
[I 2026-07-02 08:53:11,170] Trial 13 finished with value: 0.058526870168551924 and parameters: {'sigma_noise': 0.03241516845456971, 'A_repulsion': 0.22640959049223497, 'eta_learning': 0.0330356848203127, 'sigma_boundary': 8.237344284029199}. Best is trial 12 with value: 0.02803179614306038.
[I 2026-07-02 08:54:57,581] Trial 14 finished with value: 0.14483027902079323 and parameters: {'sigma_noise': 0.1472241855528878, 'A_repulsion': 0.30021720276510155, 'eta_learning': 0.23479657910129176, 'sigma_boundary': 9.568142610348861}. Best is trial 12 with value: 0.02803179614306038.
[I 2026-07-02 08:56:40,685] Trial 15 finished with value: 0.023087137691365927 and parameters: {'sigma_noise': 0.1905498259561096, 'A_repulsion': 0.1305727636724736, 'eta_learning': 0.016675257202362903, 'sigma_boundary': 7.275730311628976}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 08:58:40,745] Trial 16 finished with value: 0.8586874189146743 and parameters: {'sigma_noise': 0.32359753764432064, 'A_repulsion': 0.11555057944224828, 'eta_learning': 0.7669391626678903, 'sigma_boundary': 7.170021133591278}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:00:29,661] Trial 17 finished with value: 0.17823014751845878 and parameters: {'sigma_noise': 0.18723792539090578, 'A_repulsion': 0.22447541689115225, 'eta_learning': 0.23182786875562367, 'sigma_boundary': 7.566094441296283}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:01:49,189] Trial 18 finished with value: 0.032804634409804065 and parameters: {'sigma_noise': 0.0772032526986942, 'A_repulsion': 0.05812029852375636, 'eta_learning': 0.17763443062137477, 'sigma_boundary': 6.984557562766412}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:03:35,474] Trial 19 finished with value: 0.3079996172632389 and parameters: {'sigma_noise': 0.18802776632671375, 'A_repulsion': 0.18729575556004383, 'eta_learning': 0.3338428905972617, 'sigma_boundary': 8.561227787458288}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:06:08,447] Trial 20 finished with value: 0.9168674165949101 and parameters: {'sigma_noise': 0.3260549791328252, 'A_repulsion': 0.35343484769447275, 'eta_learning': 0.7599998035523554, 'sigma_boundary': 9.091478561845447}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:07:37,798] Trial 21 finished with value: 0.03408112868058334 and parameters: {'sigma_noise': 0.11004455210880662, 'A_repulsion': 0.13332251275903872, 'eta_learning': 0.01256145933273718, 'sigma_boundary': 7.93530101117991}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:09:24,577] Trial 22 finished with value: 0.02809113698055246 and parameters: {'sigma_noise': 0.18396720913977743, 'A_repulsion': 0.2065963009932077, 'eta_learning': 0.05184225283116218, 'sigma_boundary': 9.909285608076997}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:11:15,330] Trial 23 finished with value: 0.06944347782377683 and parameters: {'sigma_noise': 0.1796507520311703, 'A_repulsion': 0.25644077193079995, 'eta_learning': 0.11343493788628262, 'sigma_boundary': 4.449998836694485}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:12:31,263] Trial 24 finished with value: 0.04135174458999115 and parameters: {'sigma_noise': 0.011136883425206884, 'A_repulsion': 0.21257431321339773, 'eta_learning': 0.1923171859692062, 'sigma_boundary': 6.794764083240912}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:14:28,448] Trial 25 finished with value: 0.06212034108598255 and parameters: {'sigma_noise': 0.20709956425356682, 'A_repulsion': 0.279270699385904, 'eta_learning': 0.09148667672213645, 'sigma_boundary': 9.939238910773767}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:15:48,559] Trial 26 finished with value: 0.04848250273312636 and parameters: {'sigma_noise': 0.08880030730189249, 'A_repulsion': 0.06549264498111285, 'eta_learning': 0.28759455992199084, 'sigma_boundary': 9.081831381082385}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:17:24,397] Trial 27 finished with value: 0.024338584476191374 and parameters: {'sigma_noise': 0.16162155661754804, 'A_repulsion': 0.12622339602647353, 'eta_learning': 0.054257104269728504, 'sigma_boundary': 9.076222564488098}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:18:59,447] Trial 28 finished with value: 0.06198502502290686 and parameters: {'sigma_noise': 0.1573356981280657, 'A_repulsion': 0.13148757405485925, 'eta_learning': 0.18149609803217742, 'sigma_boundary': 8.821744403204402}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:20:54,386] Trial 29 finished with value: 0.7218208195108307 and parameters: {'sigma_noise': 0.24890468528353704, 'A_repulsion': 0.16906426880402517, 'eta_learning': 0.4817566709052783, 'sigma_boundary': 6.483975131437082}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:22:08,890] Trial 30 finished with value: 0.07257934130200647 and parameters: {'sigma_noise': 0.05276109207226132, 'A_repulsion': 0.045695176290361614, 'eta_learning': 0.547953767262526, 'sigma_boundary': 7.702053088092676}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:23:54,135] Trial 31 finished with value: 0.030050621902349365 and parameters: {'sigma_noise': 0.1758488643606758, 'A_repulsion': 0.2005117184991041, 'eta_learning': 0.06657989011818784, 'sigma_boundary': 9.191500328275456}. Best is trial 15 with value: 0.023087137691365927.
[I 2026-07-02 09:25:36,588] Trial 32 finished with value: 0.022682240171280205 and parameters: {'sigma_noise': 0.2118318431771812, 'A_repulsion': 0.0984570188765133, 'eta_learning': 0.014272583857814167, 'sigma_boundary': 8.199407175026053}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:27:22,218] Trial 33 finished with value: 0.07644999555232362 and parameters: {'sigma_noise': 0.2353750878700265, 'A_repulsion': 0.09802630434700818, 'eta_learning': 0.13263095749068932, 'sigma_boundary': 8.03041553029016}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:29:04,525] Trial 34 finished with value: 0.026183451413608977 and parameters: {'sigma_noise': 0.27883018693870093, 'A_repulsion': 0.005153803073926114, 'eta_learning': 0.01792905572582669, 'sigma_boundary': 8.494937464251674}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:30:48,842] Trial 35 finished with value: 0.05035870546493415 and parameters: {'sigma_noise': 0.27928352590411015, 'A_repulsion': 0.01928738301340613, 'eta_learning': 0.0841632249034816, 'sigma_boundary': 7.392416283949762}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:32:33,067] Trial 36 finished with value: 0.4742777719124492 and parameters: {'sigma_noise': 0.31136213215475067, 'A_repulsion': 6.086486086892551e-05, 'eta_learning': 0.4130791357742309, 'sigma_boundary': 4.544782724167794}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:34:17,827] Trial 37 finished with value: 0.10548474192670078 and parameters: {'sigma_noise': 0.253387521496746, 'A_repulsion': 0.07122328983462974, 'eta_learning': 0.16031891337433155, 'sigma_boundary': 8.108914615806643}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:35:53,951] Trial 38 finished with value: 0.10814926803523345 and parameters: {'sigma_noise': 0.20926691499133632, 'A_repulsion': 0.03512226780511013, 'eta_learning': 0.22543785423709584, 'sigma_boundary': 5.348497907254492}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:37:57,803] Trial 39 finished with value: 0.1707168580851741 and parameters: {'sigma_noise': 0.356903145676653, 'A_repulsion': 0.10247081145839758, 'eta_learning': 0.12391939382543297, 'sigma_boundary': 8.560184604211369}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:39:57,271] Trial 40 finished with value: 0.8483254325410027 and parameters: {'sigma_noise': 0.2980384296427725, 'A_repulsion': 0.13642059052504804, 'eta_learning': 0.7004754081438058, 'sigma_boundary': 6.128773364948651}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:42:12,212] Trial 41 finished with value: 0.06743902088753287 and parameters: {'sigma_noise': 0.4493276154811531, 'A_repulsion': 0.07650648921451174, 'eta_learning': 0.012347160785187182, 'sigma_boundary': 9.314395159100691}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:43:45,315] Trial 42 finished with value: 0.025607899318463166 and parameters: {'sigma_noise': 0.1277462379987703, 'A_repulsion': 0.1515868810183169, 'eta_learning': 0.0702075029612477, 'sigma_boundary': 8.71548460947213}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:45:14,754] Trial 43 finished with value: 0.0249350599267735 and parameters: {'sigma_noise': 0.10627283506375054, 'A_repulsion': 0.15392288250302727, 'eta_learning': 0.0752172702507098, 'sigma_boundary': 2.9098014233481426}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:46:47,544] Trial 44 finished with value: 0.025233429371407063 and parameters: {'sigma_noise': 0.11612486235621454, 'A_repulsion': 0.15642080230880245, 'eta_learning': 0.07253622292158327, 'sigma_boundary': 2.732379942577915}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:48:13,971] Trial 45 finished with value: 0.0984733365395704 and parameters: {'sigma_noise': 0.10304992803196839, 'A_repulsion': 0.11702247329318957, 'eta_learning': 0.32440929093340104, 'sigma_boundary': 2.2273691348373683}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:49:55,898] Trial 46 finished with value: 0.06888249173420272 and parameters: {'sigma_noise': 0.16297956610242925, 'A_repulsion': 0.1763750853005941, 'eta_learning': 0.13385514113369545, 'sigma_boundary': 2.8712128232706657}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:51:35,081] Trial 47 finished with value: 0.026761817922067662 and parameters: {'sigma_noise': 0.12296940482407565, 'A_repulsion': 0.24019738846386934, 'eta_learning': 0.06447800353554937, 'sigma_boundary': 3.6677175927703147}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:52:56,237] Trial 48 finished with value: 0.14540593253423578 and parameters: {'sigma_noise': 0.05071186973177694, 'A_repulsion': 0.1499979919617956, 'eta_learning': 0.8695554368721976, 'sigma_boundary': 0.9653568022974439}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:54:39,640] Trial 49 finished with value: 0.2310876374655795 and parameters: {'sigma_noise': 0.20301259547465114, 'A_repulsion': 0.11525059363557968, 'eta_learning': 0.2593475684013405, 'sigma_boundary': 1.9690550325328013}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:57:01,167] Trial 50 finished with value: 0.4585541183313919 and parameters: {'sigma_noise': 0.2293397770099627, 'A_repulsion': 0.4670826600552419, 'eta_learning': 0.19008652802985065, 'sigma_boundary': 2.9802437626711673}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 09:58:34,251] Trial 51 finished with value: 0.02499481971313691 and parameters: {'sigma_noise': 0.12636668221749314, 'A_repulsion': 0.16018061798367722, 'eta_learning': 0.06278447563558127, 'sigma_boundary': 1.642459282175748}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 10:00:02,401] Trial 52 finished with value: 0.024428602496847477 and parameters: {'sigma_noise': 0.08626746975448665, 'A_repulsion': 0.17691411336637278, 'eta_learning': 0.0896373171006828, 'sigma_boundary': 1.4793917718795988}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 10:01:30,552] Trial 53 finished with value: 0.026213451076319585 and parameters: {'sigma_noise': 0.08809842833349671, 'A_repulsion': 0.18065445548477096, 'eta_learning': 0.104796203692203, 'sigma_boundary': 1.1766135413164536}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 10:02:48,448] Trial 54 finished with value: 0.025923350336580237 and parameters: {'sigma_noise': 0.06138604328836054, 'A_repulsion': 0.0817519937859961, 'eta_learning': 0.04547993880556493, 'sigma_boundary': 0.5297878093962098}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 10:04:21,117] Trial 55 finished with value: 0.04804533380599895 and parameters: {'sigma_noise': 0.1299504010038774, 'A_repulsion': 0.1319317870477874, 'eta_learning': 0.14257089258712316, 'sigma_boundary': 1.8354689362369827}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 10:05:56,572] Trial 56 finished with value: 0.025133194216450605 and parameters: {'sigma_noise': 0.1624533908643268, 'A_repulsion': 0.11164540044329867, 'eta_learning': 0.04001521226702957, 'sigma_boundary': 1.2862351421501248}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 10:07:39,185] Trial 57 finished with value: 0.12124948121280789 and parameters: {'sigma_noise': 0.14471054390778498, 'A_repulsion': 0.2205869243265724, 'eta_learning': 0.21827371598812134, 'sigma_boundary': 0.2005277075458629}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 10:09:00,110] Trial 58 finished with value: 0.023613737169812226 and parameters: {'sigma_noise': 0.1000897322141404, 'A_repulsion': 0.05236684748679068, 'eta_learning': 0.10866306057051622, 'sigma_boundary': 1.5822566292845992}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 10:10:19,923] Trial 59 finished with value: 0.025530365899592365 and parameters: {'sigma_noise': 0.09018907329740763, 'A_repulsion': 0.057354633395227644, 'eta_learning': 0.10199131529323986, 'sigma_boundary': 2.4384583656523375}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 10:11:33,179] Trial 60 finished with value: 0.03613519670864687 and parameters: {'sigma_noise': 0.029814383203476208, 'A_repulsion': 0.08976389351980715, 'eta_learning': 0.16070132775729234, 'sigma_boundary': 3.312547829817616}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 10:13:02,156] Trial 61 finished with value: 0.035574883784923794 and parameters: {'sigma_noise': 0.10518794363141878, 'A_repulsion': 0.13604879643683399, 'eta_learning': 0.04173248083687003, 'sigma_boundary': 0.5514846571038188}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 10:14:49,519] Trial 62 finished with value: 0.09384808121251104 and parameters: {'sigma_noise': 0.1963052035836821, 'A_repulsion': 0.1900862890689691, 'eta_learning': 0.10660664849376685, 'sigma_boundary': 1.6942304299213222}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 10:16:05,049] Trial 63 finished with value: 0.022891443665329313 and parameters: {'sigma_noise': 0.0673236243632803, 'A_repulsion': 0.033987766381003995, 'eta_learning': 0.057434684008491006, 'sigma_boundary': 1.4294282417577384}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 10:17:21,541] Trial 64 finished with value: 0.029128766534142408 and parameters: {'sigma_noise': 0.07548672825847211, 'A_repulsion': 0.029362428328777442, 'eta_learning': 0.012845011246231, 'sigma_boundary': 2.333088956377016}. Best is trial 32 with value: 0.022682240171280205.
[I 2026-07-02 10:18:36,576] Trial 65 finished with value: 0.02229914435132662 and parameters: {'sigma_noise': 0.06672739210063465, 'A_repulsion': 0.0374678064851191, 'eta_learning': 0.09999366268769994, 'sigma_boundary': 1.3279468813004665}. Best is trial 65 with value: 0.02229914435132662.
[I 2026-07-02 10:19:48,363] Trial 66 finished with value: 0.02721980751516593 and parameters: {'sigma_noise': 0.03711163697561745, 'A_repulsion': 0.054633980822915595, 'eta_learning': 0.20194002275259082, 'sigma_boundary': 1.3951058950929625}. Best is trial 65 with value: 0.02229914435132662.
[I 2026-07-02 10:21:05,113] Trial 67 finished with value: 0.020661349543273453 and parameters: {'sigma_noise': 0.07684111938839223, 'A_repulsion': 0.035635692251965376, 'eta_learning': 0.13533309987692368, 'sigma_boundary': 0.6753943983976276}. Best is trial 67 with value: 0.020661349543273453.

KeyboardInterrupt:

In [26]:
import pandas as pd
import pickle 

with open('Data_rat_first_dists_V2.pkl', 'rb') as file:
    data = pickle.load(file)


df = pd.DataFrame(data)

C:\Users\Akrami_Lab5\AppData\Local\Temp\ipykernel_16464\1389835061.py:5: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  data = pickle.load(file)

In [27]:
df['Distribution'].unique()

array(['Asym_right', 'Uniform', 'Asym_left'], dtype=object)

In [28]:
df['Distribution'].isna().sum()

np.int64(0)

In [29]:
df.loc[df['Distribution'].isna(), 'Participant_ID']

Series([], Name: Participant_ID, dtype: object)

In [30]:
with pd.option_context('display.max_columns', None, 'display.max_rows', None):
    print(df[df['Distribution'].isna()])

Empty DataFrame
Columns: [Participant_ID, savetime, stimulus, correct, Answer, Distribution, stim_dur, prestim_time, time_a1_go_cue, go_cue_dur, stimulation, choice, Trial, valid, sessiondate, rule, gocue_rewardsound, Response, stim_relative, Reaction Time, performance, block, iti, stim_bin, stim_bin_inc, previous, previous_bin, next_bin, previous2, pre_correct, next, next_correct, previous_choice, diff, diff_bin, Previous_dist, No_response]
Index: []

In [51]:
import os

print(os.cpu_count())

8

In [52]:
import multiprocessing

print(multiprocessing.cpu_count())

8

In [53]:
import os

print(f"PID = {os.getpid()}")

PID = 16464

In [54]:
pip install psutil

Requirement already satisfied: psutil in c:\users\akrami_lab5\appdata\roaming\python\python314\site-packages (7.1.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [55]:
import psutil
import time

while True:
    print(psutil.cpu_percent(percpu=True))
    time.sleep(1)

[24.1, 25.0, 32.6, 18.4, 28.8, 19.5, 28.1, 24.6]
[66.7, 59.4, 60.9, 48.4, 59.4, 51.6, 65.6, 59.4]
[51.5, 42.2, 59.1, 53.1, 51.6, 39.1, 47.7, 53.1]
[49.3, 50.0, 47.7, 34.4, 62.5, 48.4, 60.9, 45.3]
[55.9, 64.1, 65.6, 54.7, 60.0, 68.8, 61.5, 56.2]
[39.7, 38.5, 43.9, 23.1, 37.5, 21.9, 46.2, 29.7]
[48.5, 36.9, 43.1, 37.5, 49.2, 31.2, 48.4, 25.0]
[47.1, 46.2, 50.7, 33.8, 51.5, 56.9, 50.8, 33.8]
[75.4, 78.1, 81.5, 71.9, 78.5, 67.2, 82.8, 71.9]
[47.1, 25.4, 42.4, 21.5, 43.1, 27.0, 35.4, 25.4]
[47.1, 27.7, 49.3, 39.1, 33.8, 38.5, 56.1, 26.2]
[36.2, 26.6, 34.4, 23.4, 37.5, 21.9, 38.5, 23.4]
[40.6, 26.2, 41.5, 35.9, 39.4, 33.3, 43.9, 26.6]
[40.6, 35.4, 35.4, 29.7, 34.4, 34.4, 42.2, 30.8]
[45.6, 32.8, 47.8, 23.4, 37.5, 25.0, 26.6, 30.8]
[43.3, 45.3, 41.8, 37.5, 46.9, 26.2, 42.2, 37.5]
[27.7, 28.1, 43.8, 28.1, 29.2, 20.3, 35.9, 26.2]
[53.6, 48.4, 55.4, 37.5, 57.6, 47.7, 46.9, 45.3]
[38.8, 39.1, 35.8, 23.1, 38.5, 16.9, 38.5, 17.2]

KeyboardInterrupt:

In [56]:
import psutil

print(psutil.cpu_percent(interval=1))

54.8

In [1]:
import time

import binned_Hybrid_hpc_utils as hpc

start = time.time()

save_path = r"D:\sc_modelling-amir-2025\Final-Hybrid - Copy\human_test.pkl"


hpc.run_pid_repeated_cv(
    species="human",
    p_id=6266630.0,
    save_path=save_path,
    model_mode="all",
    repetition_seeds=[1,2],
    cv_folds=2,
    optuna_trials=20,
    sampler_type="TPE",
    model_seed_count=5,
    fit_with="conditional",
    parallel_jobs=6,
)



elapsed = time.time() - start

print(f"\nFinished in {elapsed/60:.2f} minutes")

  ✱ Running repeated CV
  ✱ Species: human
  ✱ Subject: 6266630.0
  ✱ ID column: Participant_Private_ID
  ✱ Data path: D:\sc_modelling-amir-2025\Final-Hybrid - Copy\Data_human_first_dists_V2.pkl
  ✱ Model mode: all
  ✱ Custom alpha: None
  ✱ Repetitions: 2
  ✱ Folds: 2
  ✱ Model seeds per objective: 5
  ✱ Sampler: TPE
  ✔ Results saved to D:\sc_modelling-amir-2025\Final-Hybrid - Copy\human_test.pkl
  ✔ Completed human subject 6266630.0
run_pid_repeated_cv executed in 530.00 seconds.

Finished in 8.83 minutes

In [4]:
import pickle 

with open('human_test.pkl', 'rb') as file:
    data = pickle.load(file)

In [12]:
data['variants']['Hybrid']['partitions'][1]

{'repetition_idx': 2,
 'partition_seed': 2,
 'blocks_in_folds': [[np.int64(17),
   np.int64(16),
   np.int64(5),
   np.int64(14),
   np.int64(15),
   np.int64(10),
   np.int64(3),
   np.int64(21),
   np.int64(20),
   np.int64(1),
   np.int64(4),
   np.int64(11)],
  [np.int64(9),
   np.int64(18),
   np.int64(22),
   np.int64(13),
   np.int64(0),
   np.int64(19),
   np.int64(8),
   np.int64(23),
   np.int64(2),
   np.int64(6),
   np.int64(12),
   np.int64(7)]]}

In [3]:
import time

import binned_Hybrid_hpc_utils as hpc

start = time.time()

save_path = r"D:\sc_modelling-amir-2025\Final-Hybrid - Copy\mouse_test.pkl"


hpc.run_pid_repeated_cv(
    species="mouse",
    p_id="QP0101",
    save_path=save_path,
    model_mode="all",
    repetition_seeds=[1,2],
    cv_folds=2,
    optuna_trials=3,
    sampler_type="TPE",
    model_seed_count=5,
    fit_with="conditional",
    parallel_jobs=6,
)



elapsed = time.time() - start

print(f"\nFinished in {elapsed/60:.2f} minutes")

  ✱ Running repeated CV
  ✱ Species: mouse
  ✱ Subject: QP0101
  ✱ ID column: Participant_ID
  ✱ Data path: D:\sc_modelling-amir-2025\Final-Hybrid - Copy\SC_Data_Cleaned.pkl
  ✱ Model mode: all
  ✱ Custom alpha: None
  ✱ Repetitions: 2
  ✱ Folds: 2
  ✱ Model seeds per objective: 5
  ✱ Sampler: TPE
PID=20888  Memory=0.07 GB
PID=17592  Memory=0.07 GB
PID=19212  Memory=0.07 GB
PID=19604  Memory=0.07 GB
PID=16396  Memory=0.07 GB
PID=21932  Memory=0.07 GB

ValueError: too many values to unpack (expected 2, got 4)

In [1]:
import time
import importlib
import binned_Hybrid_hpc_utils as hpc

importlib.reload(hpc)

start = time.time()

save_path = r"D:\sc_modelling-amir-2025\Final-Hybrid - Copy\test_full_alpha_scan.pkl"

hpc.run_pid_repeated_cv(
    species="human",
    p_id=6266630.0,
    save_path=save_path,
    fit_mode="full_alpha_scan",
    model_mode="fixed_alpha",
    alpha_values=[0.1, 0.2],   # test only 2 alphas first
    optuna_trials=5,           # tiny test
    sampler_type="TPE",
    model_seed_count=2,
    fit_with="conditional",
    parallel_jobs=2,
)

elapsed = time.time() - start
print(f"\nFinished in {elapsed/60:.2f} minutes")

  ✱ Running model fitting
  ✱ Fit mode: full_alpha_scan
  ✱ Species: human
  ✱ Subject: 6266630.0
  ✱ ID column: Participant_Private_ID
  ✱ Data path: D:\sc_modelling-amir-2025\Final-Hybrid - Copy\Data_human_first_dists_V2.pkl
  ✱ Model mode: fixed_alpha
  ✱ Custom alpha: None
  ✱ Alpha values: [0.1, 0.2]
  ✱ Repetitions: 10
  ✱ Folds: 2
  ✱ Trials: 5
  ✱ Model seeds: 2
  ✱ Sampler: TPE
  ✱ Parallel jobs: 2
  ✔ Results saved to D:\sc_modelling-amir-2025\Final-Hybrid - Copy\test_full_alpha_scan.pkl
  ✔ Completed full_alpha_scan fitting for human subject 6266630.0
run_pid_repeated_cv executed in 29.27 seconds.

Finished in 0.49 minutes